begin;
select no_plan();
insert into auth.users(id,email) values(md5('quota-owner')::uuid,'quota-owner@example.test');
select set_config('test.quota_org',(select id::text from public.organizations where personal_owner_id=md5('quota-owner')::uuid),true);
insert into public.quests(id,creator_id,organization_id,title,is_open)
select md5('quota-quest-'||n)::uuid,md5('quota-owner')::uuid,current_setting('test.quota_org')::uuid,'Quota test',false from generate_series(1,3)n;
select is((select active_quest_quota_enabled from public.organization_subscriptions where organization_id=current_setting('test.quota_org')::uuid),false,'квоты выключены по умолчанию');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1),active_quest_quota_enabled=true where organization_id=current_setting('test.quota_org')::uuid;
select set_config('request.jwt.claim.sub',md5('quota-owner')::uuid::text,true);
set local role authenticated;
select is(public.get_organization_billing_state(current_setting('test.quota_org')::uuid)->>'enforcement_enabled','true','RPC показывает включённую квоту');
select lives_ok($$update public.quests set is_open=true where id=md5('quota-quest-1')::uuid$$,'последний слот доступен');
select lives_ok($$update public.quests set is_open=true where id=md5('quota-quest-1')::uuid$$,'повтор открытия не расходует слот');
select throws_ok($$update public.quests set is_open=true where id=md5('quota-quest-2')::uuid$$,'P0001','active quest quota exceeded','прямой UPDATE не обходит квоту');
select throws_ok($$insert into public.quests(creator_id,organization_id,title,is_open) values(md5('quota-owner')::uuid,current_setting('test.quota_org')::uuid,'Quota insert',true)$$,'P0001','active quest quota exceeded','прямой INSERT не обходит квоту');
select lives_ok($$update public.quests set is_open=false where id=md5('quota-quest-1')::uuid$$,'закрытие разрешено');
select lives_ok($$update public.quests set is_open=true where id=md5('quota-quest-2')::uuid$$,'закрытие освободило слот');
select throws_ok($$update public.organization_subscriptions set active_quest_quota_enabled=false$$,'42501',null,'клиент не отключает enforcement');
reset role;
update public.organization_subscriptions set status='transition',plan_version_id=null where organization_id=current_setting('test.quota_org')::uuid;
select is(public.get_organization_billing_state(current_setting('test.quota_org')::uuid)->>'enforcement_enabled','false','RPC показывает исключение переходного режима');
select lives_ok($$update public.quests set is_open=true where organization_id=current_setting('test.quota_org')::uuid$$,'переходные организации не ограничиваются');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1) where organization_id=current_setting('test.quota_org')::uuid;
select is((select count(*) from public.quests where organization_id=current_setting('test.quota_org')::uuid and is_open),3::bigint,'смена тарифа не закрыла существующие квесты');
select lives_ok($$update public.quests set title='Quota renamed' where id=md5('quota-quest-1')::uuid$$,'редактирование сверх лимита разрешено');
update public.quests set is_open=false where organization_id=current_setting('test.quota_org')::uuid;
select throws_ok($$update public.quests set is_open=true where organization_id=current_setting('test.quota_org')::uuid$$,'P0001','active quest quota exceeded','multi-row открытие атомарно отклонено');
select is((select count(*) from public.quests where organization_id=current_setting('test.quota_org')::uuid and is_open),0::bigint,'после multi-row отказа нет частичного открытия');
update public.quests set is_open=true where id=md5('quota-quest-1')::uuid;
select lives_ok($$insert into public.quests(id,creator_id,organization_id,title,is_open) values(md5('quota-quest-1')::uuid,md5('quota-owner')::uuid,current_setting('test.quota_org')::uuid,'Retry',true) on conflict(id) do update set is_open=excluded.is_open$$,'upsert уже открытого квеста не расходует слот');
insert into public.organizations(id,name) values(md5('quota-target-org')::uuid,'Quota target');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1),active_quest_quota_enabled=true where organization_id=md5('quota-target-org')::uuid;
select lives_ok($$update public.quests set organization_id=md5('quota-target-org')::uuid where id=md5('quota-quest-1')::uuid$$,'перенос занимает свободный слот назначения');
update public.quests set is_open=true where id=md5('quota-quest-2')::uuid;
select throws_ok($$update public.quests set organization_id=md5('quota-target-org')::uuid where id=md5('quota-quest-2')::uuid$$,'P0001','active quest quota exceeded','перенос в заполненную организацию запрещён');
select is((select organization_id from public.quests where id=md5('quota-quest-2')::uuid),current_setting('test.quota_org')::uuid,'отказ переноса сохраняет исходную организацию');
select * from finish();
rollback;
