begin;
select no_plan();
insert into auth.users(id,email) values(md5('discount-issuer')::uuid,'discount-issuer@example.test');
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('discount-issuer')::uuid,'owner','platform');
select set_config('request.jwt.claim.sub',md5('discount-issuer')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.deadline',(now()+interval '1 day')::text,true);
set local role authenticated;
select set_config('test.issued',public.issue_organization_discount(current_setting('test.org')::uuid,'pro',10000,2,1,current_setting('test.deadline')::timestamptz,md5('issue-discount')::uuid)::text,true);
select is(length(current_setting('test.issued')::jsonb->>'code'),32,'случайный код возвращён при выпуске');
select is(public.issue_organization_discount(current_setting('test.org')::uuid,'pro',10000,2,1,current_setting('test.deadline')::timestamptz,md5('issue-discount')::uuid)->>'code',null::text,'retry не возвращает открытый код');
select throws_ok($t$select public.issue_organization_discount(current_setting('test.org')::uuid,'pro',5000,2,1,current_setting('test.deadline')::timestamptz,md5('issue-discount')::uuid)$t$,'22023','discount command conflict','команда не меняет процент');
select is(public.preview_organization_discount(current_setting('test.org')::uuid,lower(current_setting('test.issued')::jsonb->>'code'),'pro',1)->>'ok','true','проверка корректного кода');
select is(public.preview_organization_discount(current_setting('test.org')::uuid,current_setting('test.issued')::jsonb->>'code','pro',12)->>'ok','false','месячная акция не даёт годовой период');
select is(public.preview_organization_discount(current_setting('test.org')::uuid,current_setting('test.issued')::jsonb->>'code','business',1)->>'ok','false','другой тариф не получает скидку');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select throws_ok($t$select public.issue_organization_discount(current_setting('test.org')::uuid,'pro',10000,2,1,current_setting('test.deadline')::timestamptz,md5('another-issue')::uuid)$t$,'42501','platform owner required','выпуск требует MFA');
select public.preview_organization_discount(current_setting('test.org')::uuid,'invalid','pro',1) from generate_series(1,7);
select is(public.preview_organization_discount(current_setting('test.org')::uuid,current_setting('test.issued')::jsonb->>'code','pro',1)->>'reason','rate_limited','одиннадцатая проверка ограничена');
reset role;
select is((select count(*) from public.billing_discount_codes where issuer_id=auth.uid()),1::bigint,'retry не создаёт второй код');
select is((select code_hash from public.billing_discount_codes where issuer_id=auth.uid()),encode(extensions.digest(current_setting('test.issued')::jsonb->>'code','sha256'),'hex'),'хранится только хеш');
select is((select count(*) from public.billing_trial_access where organization_id=current_setting('test.org')::uuid),0::bigint,'проверка не выдаёт доступ');
select * from finish();
rollback;
