begin;
select no_plan();
insert into auth.users(id,email) values(md5('free-ui-owner')::uuid,'free-ui-owner@example.test'),(md5('free-ui-other')::uuid,'free-ui-other@example.test');
create function pg_temp.org() returns uuid language sql as $$select id from public.organizations where personal_owner_id=md5('free-ui-owner')::uuid$$;
select set_config('test.promo',public.issue_organization_promotion(pg_temp.org(),(select id from public.billing_plan_versions where plan_key='business' and version=1),21,now()+interval '7 days',md5('free-ui-issuer')::uuid,gen_random_uuid())::text,true);
select set_config('request.jwt.claim.sub',md5('free-ui-owner')::text,true);
set local role authenticated;
select is(public.get_organization_free_access_controls(pg_temp.org(),repeat('a',64))->>'available','true','владелец видит доступные действия');
select is(jsonb_array_length(public.get_organization_free_access_controls(pg_temp.org(),repeat('a',64))->'targets'),2,'доступны платные тарифы');
select is(public.get_organization_free_access_controls(pg_temp.org(),null)->'targets'->0->>'eligible','false','без браузерной метки trial недоступен');
select throws_ok($$select public.get_organization_free_access_controls(pg_temp.org(),'bad')$$,'22023','invalid browser key','проверка формы метки');
select is(public.preview_organization_promotion(pg_temp.org(),current_setting('test.promo')::jsonb->>'code')->>'ok','true','владелец получает условия промокода');
reset role;
select is((select count(*) from public.billing_trial_access where organization_id=pg_temp.org()),0::bigint,'предпросмотр не активирует доступ');
set local role authenticated;
select set_config('test.receipt',public.redeem_organization_promotion(pg_temp.org(),current_setting('test.promo')::jsonb->>'code',md5('free-ui-command')::uuid,0)::text,true);
select is(current_setting('test.receipt')::jsonb->>'ok','true','активация работает под authenticated с billing.manage');
select is(public.get_free_access_command_result(pg_temp.org(),'promotion',md5('free-ui-command')::uuid)->'receipt',current_setting('test.receipt')::jsonb,'восстановление результата без кода');
select is(public.get_free_access_command_result(pg_temp.org(),'trial',md5('free-ui-command')::uuid)->>'found','false','пространства команд разделены');
select is(public.get_organization_free_access_controls(pg_temp.org(),repeat('a',64))->'current_access'->>'kind','promotion','кабинет отличает promo от trial');
select is(public.get_organization_free_access_controls(pg_temp.org(),repeat('a',64))->>'available','false','новый доступ не суммируется');
select set_config('request.jwt.claim.sub',md5('free-ui-other')::text,true);
select throws_ok($$select public.get_organization_free_access_controls(pg_temp.org(),null)$$,'42501','billing management denied','чужие условия закрыты');
select throws_ok($$select public.preview_organization_promotion(pg_temp.org(),'code')$$,'42501','billing management denied','чужой промокод не проверяется');
select throws_ok($$select public.get_free_access_command_result(pg_temp.org(),'promotion',md5('free-ui-command')::uuid)$$,'42501','billing management denied','чужой receipt закрыт');
reset role;
select ok(not has_function_privilege('anon','public.get_free_access_command_result(uuid,text,uuid)','execute'),'анонимный receipt закрыт');
select ok(not has_function_privilege('authenticated','public.issue_organization_promotion(uuid,uuid,integer,timestamptz,uuid,uuid)','execute'),'выпуск закрыт для организации');
select ok(not has_table_privilege('authenticated','public.billing_promotions','select'),'хеши кодов не выдаются клиенту');
select * from finish();
rollback;
