begin;
select no_plan();
insert into auth.users(id,email) values(md5('expiry-owner')::uuid,'expiry@example.test');
select set_config('test.exp_org',(select id::text from public.organizations where personal_owner_id=md5('expiry-owner')::uuid),true);
select is(public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,0)->>'recorded','false','unconfigured untouched');
update public.organization_subscriptions set status='active',plan_version_id=(select id from public.billing_plan_versions where plan_key='pro' and version=1),period_start=now()-interval '2 days',period_end=now()-interval '1 day' where organization_id=current_setting('test.exp_org')::uuid;
select set_config('test.exp_before',(select to_jsonb(s)::text from public.organization_subscriptions s where organization_id=current_setting('test.exp_org')::uuid),true);
set local role service_role;
select set_config('test.exp_receipt',public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,1)::text,true);
select is(current_setting('test.exp_receipt')::jsonb->>'recorded','true','due recorded');
select is(public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,1),current_setting('test.exp_receipt')::jsonb,'exact retry');
reset role;
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.exp_org')::uuid),'expired','status materialized');
select is((select to_jsonb(s)-'status'-'revision' from public.organization_subscriptions s where organization_id=current_setting('test.exp_org')::uuid),current_setting('test.exp_before')::jsonb-'status'-'revision','all other subscription data retained');
select is((select count(*)::int from public.billing_expiration_events where organization_id=current_setting('test.exp_org')::uuid),1,'one event');
update public.organization_subscriptions set status='active',period_end=now()+interval '1 month' where organization_id=current_setting('test.exp_org')::uuid;
select is(public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,1),current_setting('test.exp_receipt')::jsonb,'late retry returns historical result');
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.exp_org')::uuid),'active','retry cannot expire renewal');
select throws_ok($$select public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,2)$$,'40001','billing revision conflict','stale job rejected');
select is(public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,3)->>'recorded','false','future period untouched');
update public.organization_subscriptions set status='trial',period_end=now()-interval '1 hour' where organization_id=current_setting('test.exp_org')::uuid;
select is(public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,4)->>'recorded','true','existing trial expiration');
select set_config('request.jwt.claim.sub',md5('expiry-owner')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,5)$$,'42501',null,'owner cannot execute server transition');
select throws_ok($$select * from public.billing_expiration_events$$,'42501',null,'audit closed');
set local role anon;
select throws_ok($$select public.record_organization_subscription_expiration(current_setting('test.exp_org')::uuid,5)$$,'42501',null,'anon denied');
reset role;
select * from finish();
rollback;
