begin;
select no_plan();
insert into auth.users(id,email) values(md5('cancel-binding')::uuid,'cancel-binding@example.test');
select set_config('test.cancel_org',(select id::text from public.organizations where personal_owner_id=md5('cancel-binding')::uuid),true);
update public.organization_subscriptions set status='active',plan_version_id=(select id from public.billing_plan_versions where plan_key='pro' and version=1),period_start=now()-interval '1 day',period_end=now()+interval '29 days' where organization_id=current_setting('test.cancel_org')::uuid;
select set_config('request.jwt.claim.sub',md5('cancel-binding')::uuid::text,true);
set local role authenticated;
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.cancel_org')::uuid,md5('cancel-command')::uuid,1,'cancel_renewal')$$,'owner requests cancellation');
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','scheduled','cancellation bound');
reset role;
update public.organization_subscriptions set period_end=period_end+interval '1 month' where organization_id=current_setting('test.cancel_org')::uuid;
set local role authenticated;
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','stale','renewal invalidates cancellation');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.cancel_org')::uuid,md5('cancel-command')::uuid,1,'cancel_renewal')$$,'old receipt still retryable');
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','stale','retry cannot revive cancellation');
reset role;
update public.organization_subscriptions set period_end=period_end-interval '1 month' where organization_id=current_setting('test.cancel_org')::uuid;
set local role authenticated;
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','stale','restoring period does not revive');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.cancel_org')::uuid,md5('resume-command')::uuid,4,'resume_renewal')$$,'explicit resume');
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','none','resume clears');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.cancel_org')::uuid,md5('cancel-new')::uuid,5,'cancel_renewal')$$,'fresh cancellation');
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','scheduled','fresh source');
reset role;
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.cancel_org')::uuid),'active','no payment/status mutation');
update public.organization_subscriptions set plan_version_id=(select id from public.billing_plan_versions where plan_key='business' and version=1) where organization_id=current_setting('test.cancel_org')::uuid;
set local role authenticated;
select is(public.get_organization_billing_intent(current_setting('test.cancel_org')::uuid)->>'cancel_intent_state','stale','plan change invalidates');
select * from finish();
rollback;
