begin;
select no_plan();
insert into auth.users(id,email) values(md5('intent-owner')::uuid,'intent-owner@example.test'),(md5('intent-other')::uuid,'intent-other@example.test');
select set_config('test.intent_org',(select id::text from public.organizations where personal_owner_id=md5('intent-owner')::uuid),true);
select set_config('test.intent_plan',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
update public.organization_subscriptions set status='active',plan_version_id=current_setting('test.intent_plan')::uuid,
  period_start=now()-interval '1 day',period_end=now()+interval '29 days' where organization_id=current_setting('test.intent_org')::uuid;
select set_config('test.intent_revision',(select revision::text from public.organization_subscriptions where organization_id=current_setting('test.intent_org')::uuid),true);
select set_config('request.jwt.claim.sub',md5('intent-owner')::uuid::text,true);
set local role authenticated;
select is((public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)->>'revision')::bigint,1::bigint,'server changes advance revision');
select set_config('test.intent_receipt',public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('cancel')::uuid,1,'cancel_renewal')::text,true);
select is(public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('cancel')::uuid,1,'cancel_renewal'),current_setting('test.intent_receipt')::jsonb,'same command returns same receipt despite old revision');
select is((public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)->>'revision')::bigint,2::bigint,'retry does not advance revision');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('cancel')::uuid,1,'resume_renewal')$$,'22023','billing command conflict','same key cannot change action');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('stale')::uuid,1,'resume_renewal')$$,'40001','billing revision conflict','stale command cannot overwrite intent');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('both')::uuid,2,'schedule_downgrade',(select id from public.billing_plan_versions where plan_key='free' and version=1))$$,'P0001','billing intent conflict','cancel and downgrade do not silently override each other');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('resume')::uuid,2,'resume_renewal')$$,'resume intent');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('upgrade')::uuid,3,'schedule_downgrade',(select id from public.billing_plan_versions where plan_key='business' and version=1))$$,'22023','target is not a downgrade','upgrade cannot masquerade as downgrade');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('downgrade')::uuid,3,'schedule_downgrade',(select id from public.billing_plan_versions where plan_key='free' and version=1))$$,'schedule Free at boundary');
select is((select plan_version_id from public.organization_subscriptions where organization_id=current_setting('test.intent_org')::uuid),current_setting('test.intent_plan')::uuid,'current plan unchanged');
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.intent_org')::uuid),'active','current status unchanged');
select ok((select scheduled_effective_at=period_end and period_end=now()+interval '29 days' from public.organization_subscriptions where organization_id=current_setting('test.intent_org')::uuid),'schedule keeps paid boundary');
select throws_ok($$update public.organization_subscriptions set status='free' where organization_id=current_setting('test.intent_org')::uuid$$,'42501',null,'owner cannot directly assign subscription');
select throws_ok('select * from public.billing_intent_commands','42501',null,'closed command journal');
select lives_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('clear')::uuid,4,'clear_downgrade')$$,'clear scheduled change');
select is(public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)->>'scheduled_plan_version_id',null::text,'schedule cleared');
reset role;
select is((select count(*) from public.billing_intent_commands where organization_id=current_setting('test.intent_org')::uuid),4::bigint,'only successful distinct commands recorded');
select ok((select relrowsecurity from pg_class where oid='public.billing_intent_commands'::regclass),'journal RLS enabled');
select set_config('request.jwt.claim.sub',md5('intent-other')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)$$,'42501','billing access denied','foreign org cannot read');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('foreign')::uuid,5,'cancel_renewal')$$,'42501','billing management denied','foreign org cannot manage');
reset role;
update public.organization_subscriptions set period_end=now()-interval '1 hour' where organization_id=current_setting('test.intent_org')::uuid;
select set_config('request.jwt.claim.sub',md5('intent-owner')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('expired')::uuid,6,'cancel_renewal')$$,'P0001','billing period not active','expired period cannot be extended by intent');
select is(public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('cancel')::uuid,1,'cancel_renewal'),current_setting('test.intent_receipt')::jsonb,'old receipt is returned without reapplying old command');
select is((public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)->>'revision')::bigint,6::bigint,'receipt does not roll back current state');
reset role;
insert into public.organization_memberships(id,organization_id,user_id,status)
values(md5('intent-reader-member')::uuid,current_setting('test.intent_org')::uuid,md5('intent-other')::uuid,'active');
insert into public.membership_roles(membership_id,role_id)
select md5('intent-reader-member')::uuid,id from public.roles where key='sales_manager';
select set_config('request.jwt.claim.sub',md5('intent-other')::uuid::text,true);
set local role authenticated;
select lives_ok($$select public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)$$,'billing.read can inspect intent');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('reader-command')::uuid,6,'resume_renewal')$$,'42501','billing management denied','billing.read does not grant management');
reset role;
set local role anon;
select throws_ok($$select public.get_organization_billing_intent(current_setting('test.intent_org')::uuid)$$,'42501',null,'anonymous read denied');
select throws_ok($$select public.request_organization_billing_intent(current_setting('test.intent_org')::uuid,md5('anon-command')::uuid,6,'resume_renewal')$$,'42501',null,'anonymous mutation denied');
reset role;
select * from finish();
rollback;
