begin;
select no_plan();
insert into auth.users(id,email) values(md5('offer-owner')::uuid,'offer-owner@example.test'),(md5('offer-other')::uuid,'offer-other@example.test');
select set_config('request.jwt.claim.sub',md5('offer-owner')::uuid::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',now(),now()+interval '1 month')->>'id',true);
set local role authenticated;
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'amount_minor','100','сумма из серверного заказа');
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'environment','sandbox','режим обозначен явно');
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'state','reserved','просмотр не начинает отправку');
select ok(not (public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid) ?| array['shop_id','idempotency_key','actor_id','return_url']),'внутренние поля не выдаются');
select throws_ok($$select public.get_sandbox_order_offer(current_setting('test.org')::uuid,gen_random_uuid())$$,'42501','sandbox order unavailable','неизвестный заказ закрыт');
select set_config('request.jwt.claim.sub',md5('offer-other')::uuid::text,true);
select throws_ok($$select public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)$$,'42501','billing management denied','чужая организация закрыта');
select throws_ok($$select public.get_sandbox_order_offer((select id from public.organizations where personal_owner_id=auth.uid()),current_setting('test.order')::uuid)$$,'42501','sandbox order unavailable','заказ нельзя перенести в свою организацию');
reset role;
select ok(not has_function_privilege('anon','public.get_sandbox_order_offer(uuid,uuid)','execute'),'anon закрыт');
select ok(not has_table_privilege('authenticated','public.billing_sandbox_orders','select'),'прямое чтение таблицы остаётся закрыто');
select set_config('request.jwt.claim.sub',md5('offer-owner')::uuid::text,true);
set local role authenticated;
select is(public.find_pending_sandbox_order(current_setting('test.org')::uuid),current_setting('test.order')::uuid,'поиск восстанавливает свой заказ');
select set_config('request.jwt.claim.sub',md5('offer-other')::uuid::text,true);
select throws_ok($$select public.find_pending_sandbox_order(current_setting('test.org')::uuid)$$,'42501','billing management denied','поиск чужого заказа запрещён');
select is(public.find_pending_sandbox_order((select id from public.organizations where personal_owner_id=auth.uid())),null::uuid,'нет заказа — null');
reset role;
select ok(not has_function_privilege('anon','public.find_pending_sandbox_order(uuid)','execute'),'поиск закрыт для anon');
select set_config('request.jwt.claim.sub',md5('offer-owner')::uuid::text,true);
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'payment_status',null::text,'неотправленный заказ не объявлен оплаченным');
select set_config('test.subscription',(select to_jsonb(s)::text from public.organization_subscriptions s where organization_id=current_setting('test.org')::uuid),true);
select public.begin_sandbox_payment_send(current_setting('test.order')::uuid);
select public.record_sandbox_payment_result(current_setting('test.order')::uuid,md5('offer-payment')::uuid,'canceled',false,true,null);
set local role authenticated;
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'payment_status','canceled','отмена видна при новом чтении');
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'payment_requires_review','false','отмена без конфликта');
reset role;
select is((select to_jsonb(s)::text from public.organization_subscriptions s where organization_id=current_setting('test.org')::uuid),current_setting('test.subscription'),'отмена не меняет подписку');
select public.record_sandbox_payment_result(current_setting('test.order')::uuid,md5('offer-payment')::uuid,'succeeded',true,true,null);
set local role authenticated;
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'payment_requires_review','true','противоречивый финал виден как проверка');
reset role;
select * from finish();
rollback;
