begin;
select no_plan();
create function pg_temp.make_order(k text, starts timestamptz default now(), ends timestamptz default now()+interval '1 day') returns uuid language plpgsql as $$
declare o uuid;
begin
 insert into auth.users(id,email) values(md5(k)::uuid,k||'@example.test');
 perform set_config('request.jwt.claim.sub',md5(k)::uuid::text,true);
 o:=(public.reserve_sandbox_payment_order((select id from public.organizations where personal_owner_id=auth.uid()),gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',starts,ends)->>'id')::uuid;
 perform public.begin_sandbox_payment_send(o);
 return o;
end;$$;
select set_config('test.current',pg_temp.make_order('inbox-current')::text,true);
select set_config('test.future',pg_temp.make_order('inbox-future',now()+interval '1 day',now()+interval '2 days')::text,true);
select set_config('test.conflict',pg_temp.make_order('inbox-revision')::text,true);
insert into public.billing_sandbox_application_scope(organization_id) select organization_id from public.billing_sandbox_orders where id in (current_setting('test.future')::uuid,current_setting('test.conflict')::uuid);
update public.organization_subscriptions set cancel_at_period_end=true where organization_id=(select organization_id from public.billing_sandbox_orders where id=current_setting('test.conflict')::uuid);
select set_config('request.jwt.claim.sub','',true);
set local role service_role;
select is(public.read_sandbox_reconciliation_order('other',current_setting('test.current')::uuid),null::jsonb,'не тот магазин закрыт');
select set_config('test.event',public.enqueue_sandbox_payment_event('123',current_setting('test.current')::uuid,md5('payment-current')::uuid,'payment.succeeded')::text,true);
select is(public.enqueue_sandbox_payment_event('123',current_setting('test.current')::uuid,md5('payment-current')::uuid,'payment.succeeded')::text,current_setting('test.event'),'дубль уведомления имеет тот же ID');
select throws_ok($$select public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','succeeded','paid',true,'test',false))$$,'22023','invalid sandbox payment result','боевой платёж не принимается');
select throws_ok($$select public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',gen_random_uuid(),'status','succeeded','paid',true,'test',true))$$,'22023','sandbox event payment mismatch','подмена ID запрещена');
select is(public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','succeeded','paid',true,'test',true))->>'reason','sandbox_scope_disabled','по умолчанию подписка не выдаётся');
reset role;
select is((select status from public.organization_subscriptions where organization_id=(select organization_id from public.billing_sandbox_orders where id=current_setting('test.current')::uuid)),'unconfigured','неразрешённая организация не изменилась');
insert into public.billing_sandbox_application_scope select organization_id from public.billing_sandbox_orders where id=current_setting('test.current')::uuid;
set local role service_role;
select is(public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','succeeded','paid',true,'test',true))->>'fulfillmentState','applied','серверное подтверждение применено без auth.uid');
select is(public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','succeeded','paid',true,'test',true))->>'fulfillmentState','applied','дубль не продлевает период');
select is(public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','pending','paid',false,'test',true))->>'fulfillmentState','applied','поздний pending не откатывает успех');
reset role;
select is((select count(*) from public.billing_period_confirmations where confirmation_id=current_setting('test.current')::uuid),1::bigint,'один receipt');
select is((select revision from public.organization_subscriptions where organization_id=(select organization_id from public.billing_sandbox_orders where id=current_setting('test.current')::uuid)),1::bigint,'одна смена revision');
select is((select state from public.billing_sandbox_orders where id=current_setting('test.current')::uuid),'finished','заказ закрыт после применения');
set local role service_role;
select is(public.apply_sandbox_payment_event(current_setting('test.event')::uuid,jsonb_build_object('paymentId',md5('payment-current')::uuid,'status','canceled','paid',false,'test',true))->>'reason','payment_conflict','противоречивый финал только на проверку');
select set_config('test.future_event',public.enqueue_sandbox_payment_event('123',current_setting('test.future')::uuid,md5('payment-future')::uuid,'payment.succeeded')::text,true);
select is(public.apply_sandbox_payment_event(current_setting('test.future_event')::uuid,jsonb_build_object('paymentId',md5('payment-future')::uuid,'status','succeeded','paid',true,'test',true))->>'fulfillmentState','deferred','будущий период отложен');
select is(public.apply_sandbox_payment_event(current_setting('test.future_event')::uuid,jsonb_build_object('paymentId',md5('payment-future')::uuid,'status','canceled','paid',false,'test',true))->>'reason','payment_conflict','конфликт будущего периода сохранён');
select is(public.process_billing_confirmation(current_setting('test.future')::uuid)->>'reason','sandbox_payment_unverified','общий lifecycle не применит конфликтный платёж');
select set_config('test.conflict_event',public.enqueue_sandbox_payment_event('123',current_setting('test.conflict')::uuid,md5('payment-revision')::uuid,'payment.succeeded')::text,true);
select is(public.apply_sandbox_payment_event(current_setting('test.conflict_event')::uuid,jsonb_build_object('paymentId',md5('payment-revision')::uuid,'status','succeeded','paid',true,'test',true))->>'reason','revision_conflict','новое состояние подписки не перезаписывается');
select throws_ok($$select public.claim_sandbox_reconciliation('123',0)$$,'22023','invalid sandbox batch','пачка ограничена');
select ok(jsonb_array_length(public.claim_sandbox_reconciliation('123',10))>0,'worker получает задания');
select is(public.claim_sandbox_reconciliation('123',10),'[]'::jsonb,'аренда защищает параллельный worker');
select throws_ok($$select public.record_sandbox_payment_result_internal(gen_random_uuid(),gen_random_uuid(),'succeeded',true,true,null)$$,'42501',null,'service не обходит внутренний путь');
reset role;
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.billing_sandbox_events'::regclass,'public.billing_sandbox_fulfillments'::regclass,'public.billing_sandbox_reconciliation_jobs'::regclass,'public.billing_sandbox_application_scope'::regclass)),'RLS на всех новых таблицах');
set local role authenticated;
select throws_ok($$select public.apply_sandbox_payment_event(current_setting('test.event')::uuid,'{}')$$,'42501',null,'пользователь не применяет оплату');
select throws_ok($$select public.read_sandbox_reconciliation_order('123',current_setting('test.current')::uuid)$$,'42501',null,'внутренний read закрыт');
select throws_ok($$select * from public.billing_sandbox_events$$,'42501',null,'inbox закрыт');
set local role anon;
select throws_ok($$select public.claim_sandbox_reconciliation('123',5)$$,'42501',null,'anon не запускает worker');
reset role;
-- Старый worker не освобождает аренду нового после повторного захвата.
select set_config('test.job',current_setting('test.future'),true);
select set_config('test.old_lease',(select lease_token::text from public.billing_sandbox_reconciliation_jobs where order_id=current_setting('test.job')::uuid),true);
update public.billing_sandbox_reconciliation_jobs set lease_until=clock_timestamp()-interval '1 second' where order_id=current_setting('test.job')::uuid;
set local role service_role;
select ok(jsonb_array_length(public.claim_sandbox_reconciliation('123',10))=1,'истёкшая аренда повторно захвачена');
select public.finish_sandbox_reconciliation(current_setting('test.job')::uuid,current_setting('test.old_lease')::uuid,null);
reset role;
select ok((select lease_token is not null and lease_token<>current_setting('test.old_lease')::uuid from public.billing_sandbox_reconciliation_jobs where order_id=current_setting('test.job')::uuid),'старый worker не сбросил новую аренду');
select set_config('test.new_lease',(select lease_token::text from public.billing_sandbox_reconciliation_jobs where order_id=current_setting('test.job')::uuid),true);
set local role service_role;
select public.finish_sandbox_reconciliation(current_setting('test.job')::uuid,current_setting('test.new_lease')::uuid,null);
reset role;
select ok((select lease_token is null and lease_until is null from public.billing_sandbox_reconciliation_jobs where order_id=current_setting('test.job')::uuid),'текущий worker освобождает свою аренду');
select * from finish();
rollback;
