begin;
select no_plan();
insert into auth.users(id,email) values(md5('confirm-owner')::uuid,'confirm@example.test');
select set_config('test.confirm_org',(select id::text from public.organizations where personal_owner_id=md5('confirm-owner')::uuid),true);
select set_config('test.confirm_pro',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
set local role service_role;
select lives_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-1')::uuid,0,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '29 days')$$,'trusted activation');
select lives_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-1')::uuid,0,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '29 days')$$,'exact retry');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-1')::uuid,0,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '30 days')$$,'22023','billing confirmation conflict','key cannot change payload');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-old')::uuid,0,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '30 days')$$,'40001','billing revision conflict','old event rejected');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-short')::uuid,1,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '2 days')$$,'22023','billing period regression','cannot shorten');
select lives_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-2')::uuid,1,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '59 days')$$,'trusted extension');
select lives_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('confirmation-1')::uuid,0,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '29 days')$$,'late retry no rollback');
reset role;
select is((select revision from public.organization_subscriptions where organization_id=current_setting('test.confirm_org')::uuid),2::bigint,'two changes only');
select is((select period_end from public.organization_subscriptions where organization_id=current_setting('test.confirm_org')::uuid),now()+interval '59 days','renewal retained');
select is((select count(*)::int from public.billing_period_confirmations where organization_id=current_setting('test.confirm_org')::uuid),2,'two receipts');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('future-confirm')::uuid,2,current_setting('test.confirm_pro')::uuid,now()+interval '60 days',now()+interval '90 days')$$,'22023','confirmed billing period not current','future confirmation cannot replace current period');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('overlap-confirm')::uuid,2,current_setting('test.confirm_pro')::uuid,now(),now()+interval '90 days')$$,'22023','billing overlapping period conflict','partial overlap rejected');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('free-confirm')::uuid,2,(select id from public.billing_plan_versions where plan_key='free' and version=1),now()-interval '1 day',now()+interval '59 days')$$,'22023','invalid confirmed billing plan','Free is not paid confirmation');
select lives_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('upgrade-confirm')::uuid,2,(select id from public.billing_plan_versions where plan_key='business' and version=1),now()-interval '1 day',now()+interval '59 days')$$,'trusted upgrade preserves period');
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('early-downgrade')::uuid,3,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '59 days')$$,'22023','billing overlapping period conflict','no downgrade within paid period');
insert into auth.users(id,email) values(md5('confirm-transition')::uuid,'confirm-transition@example.test');
update public.organization_subscriptions set status='transition' where organization_id=(select id from public.organizations where personal_owner_id=md5('confirm-transition')::uuid);
select throws_ok($$select public.confirm_organization_subscription_period((select id from public.organizations where personal_owner_id=md5('confirm-transition')::uuid),md5('transition-confirm')::uuid,1,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '29 days')$$,'P0001','billing transition requires agreement','existing transition protected');
select set_config('request.jwt.claim.sub',md5('confirm-owner')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('client-confirm')::uuid,2,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '89 days')$$,'42501',null,'owner cannot confirm payment');
select throws_ok($$select * from public.billing_period_confirmations$$,'42501',null,'journal closed');
set local role anon;
select throws_ok($$select public.confirm_organization_subscription_period(current_setting('test.confirm_org')::uuid,md5('anon-confirm')::uuid,2,current_setting('test.confirm_pro')::uuid,now()-interval '1 day',now()+interval '89 days')$$,'42501',null,'anon denied');
reset role;
select * from finish();
rollback;
