begin;
select no_plan();
insert into auth.users(id,email) values(md5('inbox-owner')::uuid,'inbox@example.test');
select set_config('test.inbox_org',(select id::text from public.organizations where personal_owner_id=md5('inbox-owner')::uuid),true);
select set_config('test.inbox_plan',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
set local role service_role;
select lives_ok($$select public.enqueue_billing_confirmation(current_setting('test.inbox_org')::uuid,md5('future-inbox')::uuid,0,current_setting('test.inbox_plan')::uuid,now()+interval '1 day',now()+interval '31 days')$$,'enqueue future');
select is(public.process_billing_confirmation(md5('future-inbox')::uuid)->>'state','deferred','future waits');
select is(public.process_billing_confirmation(md5('future-inbox')::uuid)->>'reason','future_period','retry remains deferred');
select throws_ok($$select public.enqueue_billing_confirmation(current_setting('test.inbox_org')::uuid,md5('future-inbox')::uuid,1,current_setting('test.inbox_plan')::uuid,now()+interval '1 day',now()+interval '31 days')$$,'22023','billing confirmation conflict','cannot rewrite expected revision');
select lives_ok($$select public.enqueue_billing_confirmation(current_setting('test.inbox_org')::uuid,md5('current-inbox')::uuid,0,current_setting('test.inbox_plan')::uuid,now()-interval '1 day',now()+interval '29 days')$$,'enqueue current');
select is(public.process_billing_confirmation(md5('current-inbox')::uuid)->>'state','applied','current applied');
select is(public.process_billing_confirmation(md5('current-inbox')::uuid)->>'state','applied','retry applied');
select is(public.process_billing_confirmation(md5('future-inbox')::uuid)->>'reason','revision_conflict','future cannot overwrite new subscription');
select is(public.process_billing_confirmation(md5('future-inbox')::uuid)->>'state','review','review is stable');
select lives_ok($$select public.enqueue_billing_confirmation(current_setting('test.inbox_org')::uuid,md5('elapsed-inbox')::uuid,1,current_setting('test.inbox_plan')::uuid,now()-interval '31 days',now()-interval '1 day')$$,'elapsed preserved');
select is(public.process_billing_confirmation(md5('elapsed-inbox')::uuid)->>'reason','elapsed_period','elapsed needs review');
reset role;
select is((select revision from public.organization_subscriptions where organization_id=current_setting('test.inbox_org')::uuid),1::bigint,'only current changed subscription');
select is((select count(*)::int from public.billing_period_confirmations where organization_id=current_setting('test.inbox_org')::uuid),1,'one applied receipt');
select set_config('request.jwt.claim.sub',md5('inbox-owner')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.process_billing_confirmation(md5('future-inbox')::uuid)$$,'42501',null,'owner denied');
select throws_ok($$select * from public.billing_confirmation_inbox$$,'42501',null,'inbox private');
set local role anon;
select throws_ok($$select public.process_billing_confirmation(md5('future-inbox')::uuid)$$,'42501',null,'anon denied');
reset role;
select * from finish();
rollback;
