begin;
select no_plan();
insert into auth.users(id,email) values(md5('catalog-owner')::uuid,'catalog-owner@example.test'),(md5('catalog-other')::uuid,'catalog-other@example.test');
select set_config('request.jwt.claim.sub',md5('catalog-owner')::uuid::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
insert into public.billing_sandbox_offers(id,organization_id,plan_version_id,expected_revision,amount_minor,shop_id,return_url,period_start,period_end,valid_until)
values(md5('catalog-offer')::uuid,current_setting('test.org')::uuid,(select id from public.billing_plan_versions where plan_key='pro' and version=1),0,100,'123','https://stage.qvesta.ru',now(),now()+interval '1 day',now()+interval '1 hour'),
(md5('catalog-expired')::uuid,current_setting('test.org')::uuid,(select id from public.billing_plan_versions where plan_key='pro' and version=1),0,100,'123','https://stage.qvesta.ru',now(),now()+interval '1 day',now()-interval '1 hour');
set local role authenticated;
select is(jsonb_array_length(public.list_sandbox_checkout_offers(current_setting('test.org')::uuid)),1,'истёкшие предложения не показываются');
select ok(not (public.list_sandbox_checkout_offers(current_setting('test.org')::uuid)->0 ? 'shop_id'),'магазин не раскрывается');
select throws_ok($$select public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-expired')::uuid,gen_random_uuid())$$,'22023','sandbox offer expired','истёкшее предложение не принимается');
select set_config('test.order',public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-offer')::uuid,md5('catalog-command')::uuid)::text,true);
select is(public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-offer')::uuid,md5('catalog-command')::uuid)::text,current_setting('test.order'),'повтор возвращает тот же заказ');
select throws_ok($$select public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-expired')::uuid,md5('catalog-command')::uuid)$$,'22023','sandbox command conflict','команда не меняет предложение');
select throws_ok($$select public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-offer')::uuid,gen_random_uuid())$$,'P0001','sandbox order already pending','второй заказ блокируется');
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'amount_minor','100','цена берётся с сервера');
select set_config('request.jwt.claim.sub',md5('catalog-other')::uuid::text,true);
select throws_ok($$select public.list_sandbox_checkout_offers(current_setting('test.org')::uuid)$$,'42501','billing management denied','чужой каталог закрыт');
select throws_ok($$select public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-offer')::uuid,gen_random_uuid())$$,'42501','billing management denied','чужое предложение закрыто');
reset role;
select ok(not has_table_privilege('authenticated','public.billing_sandbox_offers','select'),'таблица закрыта');
select ok(not has_function_privilege('anon','public.accept_sandbox_checkout_offer(uuid,uuid,uuid)','execute'),'anon не создаёт заказ');
select throws_ok($$update public.billing_sandbox_offers set amount_minor=200 where id=md5('catalog-offer')::uuid$$,'55000','sandbox offer immutable','цена неизменяема');
select is((select count(*) from public.billing_sandbox_orders where id=current_setting('test.order')::uuid and first_sent_at is null),1::bigint,'подготовка не отправляет платёж');
select set_config('request.jwt.claim.sub',md5('catalog-owner')::uuid::text,true);
set local role authenticated;
select lives_ok($$select public.cancel_unsent_sandbox_order(current_setting('test.org')::uuid,current_setting('test.order')::uuid)$$,'неотправленный заказ отменяется');
select is(public.find_pending_sandbox_order(current_setting('test.org')::uuid),null::uuid,'отмена освобождает слот');
select set_config('test.next',public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-offer')::uuid,gen_random_uuid())::text,true);
reset role;
select public.begin_sandbox_payment_send(current_setting('test.next')::uuid);
set local role authenticated;
select throws_ok($$select public.cancel_unsent_sandbox_order(current_setting('test.org')::uuid,current_setting('test.next')::uuid)$$,'22023','sandbox payment requires reconciliation','начатый платёж нельзя отменить локально');
reset role;
select public.record_sandbox_payment_result(current_setting('test.next')::uuid,gen_random_uuid(),'canceled',false,true,null);
select set_config('test.expired_order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,md5('expired-command')::uuid,0,(select plan_version_id from public.billing_sandbox_offers where id=md5('catalog-expired')::uuid),100,'123','https://stage.qvesta.ru',now(),now()+interval '1 day')->>'id',true);
update public.billing_sandbox_orders set offer_id=md5('catalog-expired')::uuid where id=current_setting('test.expired_order')::uuid;
select throws_ok($$select public.begin_sandbox_payment_send(current_setting('test.expired_order')::uuid)$$,'22023','sandbox offer expired','истечение перед первым POST запрещает отправку');
set local role authenticated;
select is(public.accept_sandbox_checkout_offer(current_setting('test.org')::uuid,md5('catalog-expired')::uuid,md5('expired-command')::uuid)::text,current_setting('test.expired_order'),'после истечения повтор восстанавливает уже созданный заказ');
select lives_ok($$select public.cancel_unsent_sandbox_order(current_setting('test.org')::uuid,current_setting('test.expired_order')::uuid)$$,'неотправленный истёкший заказ безопасно закрывается');
select * from finish();
rollback;
