begin;
select no_plan();
insert into auth.users(id,email) values(md5('refund-owner')::uuid,'refund-owner@example.test'),(md5('refund-operator')::uuid,'refund-operator@example.test');
select set_config('request.jwt.claim.sub',md5('refund-owner')::uuid::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',now(),now()+interval '1 day')->>'id',true);
select public.begin_sandbox_payment_send(current_setting('test.order')::uuid);
select public.record_sandbox_payment_result(current_setting('test.order')::uuid,md5('refund-payment')::uuid,'succeeded',true,true,null);
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
select public.apply_sandbox_payment_event(public.enqueue_sandbox_payment_event('123',current_setting('test.order')::uuid,md5('refund-payment')::uuid,'payment.succeeded'),jsonb_build_object('paymentId',md5('refund-payment')::uuid,'status','succeeded','paid',true,'test',true));
select set_config('test.subscription',(select to_jsonb(s)::text from public.organization_subscriptions s where organization_id=current_setting('test.org')::uuid),true);
set local role service_role;
select throws_ok($$select public.preview_sandbox_refund(current_setting('test.order')::uuid)$$,'42501','platform refund denied','владельца организации недостаточно');
reset role;
insert into public.billing_sandbox_refund_operators values(md5('refund-operator')::uuid);
select set_config('request.jwt.claim.sub',md5('refund-operator')::uuid::text,true);
set local role service_role;
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'available_minor','100','предпросмотр полной суммы');
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'access_effect','unchanged','доступ не изменяется');
select set_config('test.refund',public.reserve_sandbox_refund(current_setting('test.order')::uuid,md5('refund-command')::uuid,40)::text,true);
select is(public.reserve_sandbox_refund(current_setting('test.order')::uuid,md5('refund-command')::uuid,40)::text,current_setting('test.refund'),'повтор команды возвращает тот же возврат');
select throws_ok($$select public.reserve_sandbox_refund(current_setting('test.order')::uuid,md5('refund-command')::uuid,41)$$,'22023','refund command conflict','команда не меняет сумму');
select throws_ok($$select public.reserve_sandbox_refund(current_setting('test.order')::uuid,gen_random_uuid(),61)$$,'22023','refund amount exceeded','резерв ограничивает общую сумму');
select is(public.begin_sandbox_refund(current_setting('test.refund')::uuid)->>'can_send','true','отправка разрешена');
select is(public.record_sandbox_refund(current_setting('test.refund')::uuid,md5('provider-refund')::uuid,'succeeded')->>'state','succeeded','частичный возврат сохранён');
select is(public.record_sandbox_refund(current_setting('test.refund')::uuid,md5('provider-refund')::uuid,'pending')->>'state','succeeded','поздний pending не откатывает возврат');
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'available_minor','60','остаток после частичного возврата');
select set_config('test.second',public.reserve_sandbox_refund(current_setting('test.order')::uuid,gen_random_uuid(),60)::text,true);
select public.begin_sandbox_refund(current_setting('test.second')::uuid);
select is(public.record_sandbox_refund(current_setting('test.second')::uuid,md5('provider-second')::uuid,'canceled')->>'state','canceled','отказ возврата сохранён');
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'available_minor','60','отказ освобождает сумму');
select set_config('test.rejected',public.reserve_sandbox_refund(current_setting('test.order')::uuid,gen_random_uuid(),60)::text,true);
select public.begin_sandbox_refund(current_setting('test.rejected')::uuid);
select is(public.reject_sandbox_refund(current_setting('test.rejected')::uuid)->>'state','rejected','HTTP 400 invalid_request сохранён отдельно от отмены провайдера');
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'available_minor','60','подтверждённый отказ запроса освобождает резерв');
select is(public.begin_sandbox_refund(current_setting('test.rejected')::uuid)->>'can_send','false','отклонённый запрос повторно не отправляется');
select is(public.record_sandbox_refund(current_setting('test.second')::uuid,md5('provider-second')::uuid,'succeeded')->>'state','review','противоречивый финал требует сверки');
select is(public.preview_sandbox_refund(current_setting('test.order')::uuid)->>'available_minor','0','конфликт удерживает резерв');
select throws_ok($$select public.record_sandbox_refund(current_setting('test.refund')::uuid,gen_random_uuid(),'succeeded')$$,'22023','refund identity conflict','ID возврата нельзя подменить');
reset role;
select is((select to_jsonb(s)::text from public.organization_subscriptions s where organization_id=current_setting('test.org')::uuid),current_setting('test.subscription'),'все исходы возврата сохраняют подписку');
select set_config('request.jwt.claim.sub',md5('refund-owner')::uuid::text,true);
set local role authenticated;
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'refunded_minor','40','владелец видит сумму подтверждённого возврата');
select is(public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'refund_requires_review','true','владелец видит необходимость сверки');
select ok(not (public.get_sandbox_order_offer(current_setting('test.org')::uuid,current_setting('test.order')::uuid) ?| array['provider_refund_id','actor_id','command_id']),'сводка не раскрывает внутренние идентификаторы возврата');
reset role;
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.billing_sandbox_refunds'::regclass,'public.billing_sandbox_refund_operators'::regclass)),'RLS включён');
set local role authenticated;
select throws_ok($$select public.reserve_sandbox_refund(current_setting('test.order')::uuid,gen_random_uuid(),1)$$,'42501',null,'клиент не выдаёт возвраты даже с actor оператора');
select throws_ok($$select * from public.billing_sandbox_refunds$$,'42501',null,'клиент не читает журнал');
set local role anon;
select throws_ok($$select public.preview_sandbox_refund(current_setting('test.order')::uuid)$$,'42501',null,'anon закрыт');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role service_role;
select is(public.read_sandbox_refund_reconciliation('other',md5('provider-refund')::uuid),null::jsonb,'сверка не читает возврат другого магазина');
select is(public.read_sandbox_refund_reconciliation('123',md5('provider-refund')::uuid)->'refund'->>'id',current_setting('test.refund'),'callback читает известный возврат без пользовательского JWT');
select is(public.record_verified_sandbox_refund(current_setting('test.refund')::uuid,md5('provider-refund')::uuid,'pending')->>'state','succeeded','сверка не откатывает успех');
select throws_ok($$select public.record_verified_sandbox_refund(current_setting('test.refund')::uuid,gen_random_uuid(),'succeeded')$$,'22023','invalid verified refund','сверка не подменяет привязку');
set local role authenticated;
select throws_ok($$select public.record_verified_sandbox_refund(current_setting('test.refund')::uuid,md5('provider-refund')::uuid,'succeeded')$$,'42501',null,'клиент не вызывает доверенную сверку');
reset role;
select * from finish();
rollback;
