begin;
select no_plan();
insert into auth.users(id,email) values(md5('recurring-owner')::uuid,'recurring-owner@example.test'),(md5('recurring-other')::uuid,'recurring-other@example.test');
select set_config('request.jwt.claim.sub',md5('recurring-owner')::uuid::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('recurring-other')::uuid),true);
select set_config('test.order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',now(),now()+interval '30 days')->>'id',true);
create temporary table subscription_before as select * from public.organization_subscriptions where organization_id=current_setting('test.org')::uuid;
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
set local role authenticated;
select is(public.list_sandbox_recurring_consents(current_setting('test.org')::uuid),'[]'::jsonb,'пустой список');
select set_config('test.consent',public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2')::text,true);
select is(public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)->0->>'state','pending','неподтверждённый метод');
reset role;
insert into public.billing_recurring_methods(consent_id,provider_method_id,verified_payment_id) values((current_setting('test.consent')::jsonb->>'consent_id')::uuid,'synthetic-private-method',gen_random_uuid());
update public.billing_sandbox_orders set state='finished' where id=current_setting('test.order')::uuid;
delete from public.billing_sandbox_application_scope where organization_id=current_setting('test.org')::uuid;
set local role authenticated;
select is(public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)->0->>'state','saved','видно после закрытия заказа и удаления scope');
select is((select count(*) from jsonb_object_keys(public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)->0)),4::bigint,'только четыре безопасных поля');
select ok(not (public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)::text like '%synthetic-private%'),'метод не раскрывается');
select set_config('request.jwt.claim.sub',md5('recurring-other')::uuid::text,true);
select throws_ok($t$select public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)$t$,'42501','billing management denied','чужая организация закрыта');
select set_config('request.jwt.claim.sub',md5('recurring-owner')::uuid::text,true);
select public.revoke_sandbox_recurring_consent(current_setting('test.org')::uuid,(current_setting('test.consent')::jsonb->>'consent_id')::uuid);
select is(public.list_sandbox_recurring_consents(current_setting('test.org')::uuid)->0->>'state','revoked','отзыв отражается');
reset role;
select ok(not has_function_privilege('anon','public.list_sandbox_recurring_consents(uuid)','execute'),'anon закрыт');
select ok((select to_jsonb(s)=to_jsonb(b) from public.organization_subscriptions s join subscription_before b using(organization_id)),'подписка сохранена');
select * from finish(); rollback;