begin;
select no_plan();
insert into auth.users(id,email) values(md5('recurring-owner')::uuid,'recurring-owner@example.test'),(md5('recurring-other')::uuid,'recurring-other@example.test');
select set_config('request.jwt.claim.sub',md5('recurring-owner')::uuid::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('recurring-other')::uuid),true);
select set_config('test.order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',now(),now()+interval '30 days')->>'id',true);
create temporary table subscription_before as select * from public.organization_subscriptions where organization_id=current_setting('test.org')::uuid;
set local role authenticated;
select throws_ok($t$select public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2')$t$,'42501','sandbox organization required','согласие закрыто вне sandbox');
reset role;
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
set local role authenticated;
select throws_ok($t$select public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'unknown')$t$,'22023','invalid recurring consent','неизвестные условия отклонены');
select throws_ok($t$select public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v1')$t$,'22023','invalid recurring consent','старое согласие только на сохранение метода отклонено');
select set_config('test.consent',public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2')::text,true);
select is(current_setting('test.consent')::jsonb->>'state','pending','согласие не включает списание');
select is(public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2'),current_setting('test.consent')::jsonb,'повтор возвращает то же согласие');
select throws_ok('select * from public.billing_recurring_methods','42501',null,'методы не читаются клиентом');
select throws_ok('select * from public.billing_recurring_consents','42501',null,'согласия не читаются напрямую');
select throws_ok('select * from public.billing_recurring_revocations','42501',null,'журнал отзыва закрыт');
select set_config('request.jwt.claim.sub',md5('recurring-other')::uuid::text,true);
select throws_ok($t$select public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2')$t$,'42501','billing management denied','чужая организация недоступна');
select throws_ok($t$select public.revoke_sandbox_recurring_consent(current_setting('test.org')::uuid,(current_setting('test.consent')::jsonb->>'consent_id')::uuid)$t$,'42501','billing management denied','чужое согласие не отзывается');
select throws_ok($t$select public.revoke_sandbox_recurring_consent(current_setting('test.other')::uuid,(current_setting('test.consent')::jsonb->>'consent_id')::uuid)$t$,'42501','recurring consent unavailable','нельзя подставить чужое согласие к своей организации');
select set_config('request.jwt.claim.sub',md5('recurring-owner')::uuid::text,true);
reset role;
select public.begin_sandbox_payment_send(current_setting('test.order')::uuid);
set local role authenticated;
select is(public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2'),current_setting('test.consent')::jsonb,'retry после отправки не создаёт новое согласие');
reset role;
delete from public.billing_sandbox_application_scope where organization_id=current_setting('test.org')::uuid;
set local role authenticated;
select is(public.revoke_sandbox_recurring_consent(current_setting('test.org')::uuid,(current_setting('test.consent')::jsonb->>'consent_id')::uuid),'revoked','отзыв доступен вне sandbox-области');
select is(public.revoke_sandbox_recurring_consent(current_setting('test.org')::uuid,(current_setting('test.consent')::jsonb->>'consent_id')::uuid),'revoked','повтор отзыва идемпотентен');
reset role;
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
set local role authenticated;
select is(public.request_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid,'sandbox-recurring-v2')->>'state','revoked','повтор согласия не отменяет отзыв');
reset role;
select is((select count(*) from public.billing_recurring_consents),1::bigint,'одна запись согласия');
select is((select count(*) from public.billing_recurring_revocations),1::bigint,'одна запись отзыва');
select is((select count(*) from public.billing_recurring_methods),0::bigint,'непроверенный способ оплаты не сохранён');
select ok((select to_jsonb(s)=to_jsonb(b) from public.organization_subscriptions s join subscription_before b using(organization_id)),'согласие и отзыв не меняют подписку');
select ok(not has_table_privilege('service_role','public.billing_recurring_methods','insert'),'service role не подставляет метод напрямую');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.billing_recurring_consents'::regclass,'public.billing_recurring_revocations'::regclass,'public.billing_recurring_methods'::regclass)),'RLS включён на всех новых таблицах');
select throws_ok('delete from public.billing_recurring_consents','55000',null,'аудит согласия неизменяем');
select set_config('request.jwt.claim.sub',md5('recurring-other')::uuid::text,true);
insert into public.billing_sandbox_application_scope values(current_setting('test.other')::uuid);
select set_config('test.late_order',public.reserve_sandbox_payment_order(current_setting('test.other')::uuid,gen_random_uuid(),0,(select id from public.billing_plan_versions where plan_key='pro' and version=1),100,'123','https://stage.qvesta.ru',now(),now()+interval '30 days')->>'id',true);
select public.begin_sandbox_payment_send(current_setting('test.late_order')::uuid);
set local role authenticated;
select throws_ok($t$select public.request_sandbox_recurring_consent(current_setting('test.other')::uuid,current_setting('test.late_order')::uuid,'sandbox-recurring-v2')$t$,'55000','recurring consent too late','нельзя согласиться задним числом после отправки платежа');
reset role;
select ok(not has_function_privilege('anon','public.request_sandbox_recurring_consent(uuid,uuid,text)','execute'),'анонимное согласие запрещено');
select set_config('request.jwt.claim.sub',md5('recurring-owner')::uuid::text,true);
set local role authenticated;
select is(public.read_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid)->>'state','revoked','безопасное чтение показывает отзыв');
select ok(not (public.read_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid) ? 'provider_method_id'),'чтение не возвращает метод');
reset role;
select is(public.begin_sandbox_payment_send(current_setting('test.order')::uuid)#>>'{order,savePaymentMethod}','true','повтор после отзыва сохраняет первоначальное тело платежа');
select is((select count(*) from public.billing_recurring_send_settings where order_id=current_setting('test.order')::uuid),1::bigint,'одна запись параметров отправки');
select set_config('request.jwt.claim.sub',md5('recurring-other')::uuid::text,true);
select is(public.begin_sandbox_payment_send(current_setting('test.late_order')::uuid)#>>'{order,savePaymentMethod}','false','обычный платёж не начинает сохранять способ оплаты');
set local role authenticated;
select throws_ok($t$select public.read_sandbox_recurring_consent(current_setting('test.org')::uuid,current_setting('test.order')::uuid)$t$,'42501','billing management denied','чтение чужого согласия запрещено');
reset role;
select * from finish();
rollback;
