begin;
select no_plan();
insert into auth.users(id,email) values(md5('legacy-permit-owner')::uuid,'legacy-permit@example.test');
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=md5('legacy-permit-owner')::uuid),true);
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1) where organization_id=current_setting('test.org')::uuid;
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public) select md5('legacy-permit-quest-'||n)::uuid,md5('legacy-permit-owner')::uuid,current_setting('test.org')::uuid,'Legacy permit',true,true from generate_series(1,2)n;
select set_config('request.jwt.claim.sub',md5('legacy-permit-owner')::uuid::text,true);
select set_config('test.permit',public.prepare_offline_start_permit(md5('legacy-permit-quest-1')::uuid,md5('legacy-permit-owner')::uuid,md5('legacy-permit-cmd')::uuid)->>'id',true);
create function pg_temp.legacy(local_id text,server_id uuid default null) returns jsonb language sql as $$select public.register_offline_quest_attempt(md5('legacy-permit-quest-1')::uuid,md5('legacy-permit-owner')::uuid,local_id,server_id)$$;
set local role authenticated;
select throws_ok($$select pg_temp.legacy('bypass')$$,'23505','offline permit registration required','старый RPC не погашает reserved');
select throws_ok($$select public.register_offline_quest_attempt(md5('legacy-permit-quest-1')::uuid,md5('legacy-permit-owner')::uuid,'three-arg')$$,'23505','offline permit registration required','трёхаргументный RPC также защищён');
select lives_ok($$select public.register_offline_quest_attempt(md5('legacy-permit-quest-2')::uuid,md5('legacy-permit-owner')::uuid,'old-package')$$,'старый пакет без разрешения работает');
reset role;
select is((select state from public.offline_start_permits where id=current_setting('test.permit')::uuid),'reserved','отказ сохранил резерв');
select is((select count(*) from public.offline_attempt_registrations where quest_id=md5('legacy-permit-quest-1')::uuid),0::bigint,'отказ не оставил привязок');
select set_config('test.attempt',public.register_permitted_offline_attempt(md5('legacy-permit-quest-1')::uuid,md5('legacy-permit-owner')::uuid,'real-local',current_setting('test.permit')::uuid)->>'id',true);
set local role authenticated;
select throws_ok($$select pg_temp.legacy('real-local')$$,'23505','offline permit registration required','удаление permit ID из запроса не обходит новый путь');
select throws_ok($$select pg_temp.legacy('other-local')$$,'23505','offline permit registration required','другая история не присоединяется к активной попытке');
select throws_ok($$select pg_temp.legacy('known-id',current_setting('test.attempt')::uuid)$$,'23505','offline permit registration required','известный server ID не обходит защиту');
reset role;
update public.quest_attempts set finished_at=now() where id=current_setting('test.attempt')::uuid;
select throws_ok($$select pg_temp.legacy('closed-id',current_setting('test.attempt')::uuid)$$,'23505','offline permit registration required','завершённая permit-попытка защищена');
select is((select count(*) from public.offline_attempt_registrations where quest_id=md5('legacy-permit-quest-1')::uuid),1::bigint,'только исходная привязка');
select is(public.register_permitted_offline_attempt(md5('legacy-permit-quest-1')::uuid,md5('legacy-permit-owner')::uuid,'real-local',current_setting('test.permit')::uuid)->>'id',current_setting('test.attempt'),'правильный retry работает');
select * from finish();
rollback;
