begin;
select no_plan();
insert into auth.users(id,email) values(md5('review-owner')::uuid,'review-owner@example.test'),(md5('review-other')::uuid,'review-other@example.test');
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public)
 select md5('review-quest')::uuid,md5('review-owner')::uuid,id,'Review',false,true from public.organizations where personal_owner_id=md5('review-owner')::uuid;
insert into public.tasks(id,quest_id,title,static_code,correct_answer) values(md5('review-task')::uuid,md5('review-quest')::uuid,'Task','CODE','ANSWER');
select set_config('request.jwt.claim.sub',md5('review-owner')::uuid::text,true);
select set_config('test.events',jsonb_build_array(jsonb_build_object('clientEventId',md5('review-event')::uuid,'taskId',md5('review-task')::uuid,'eventType','answer','submittedValue','input'))::text,true);
create function pg_temp.deliver() returns jsonb language sql as $$select public.preserve_closed_offline_events(md5('review-quest')::uuid,md5('review-owner')::uuid,'local-review',current_setting('test.events')::jsonb)$$;
set local role authenticated;
select is(pg_temp.deliver()->>'state','needs_review','закрытый квест принимает архив, не результат');
select set_config('test.receipt',pg_temp.deliver()::text,true);
select is(pg_temp.deliver(),current_setting('test.receipt')::jsonb,'повтор возвращает тот же receipt');
select is(jsonb_array_length(public.list_offline_event_reviews(md5('review-quest')::uuid)),1,'организатор видит очередь');
select throws_ok($$select * from public.offline_event_reviews$$,'42501',null,'прямой доступ закрыт');
reset role;
select is((select count(*) from public.offline_event_reviews where quest_id=md5('review-quest')::uuid),1::bigint,'нет дублей');
select is((select count(*) from public.quest_attempts where quest_id=md5('review-quest')::uuid),0::bigint,'попытка не создаётся');
select is((select is_open from public.quests where id=md5('review-quest')::uuid),false,'квест не открывается');
select set_config('test.events',replace(current_setting('test.events'),'input','changed'),true);
select throws_ok($$select pg_temp.deliver()$$,'23505','offline review event conflict','тот же ID с другим содержимым отклонён');
select set_config('request.jwt.claim.sub',md5('review-other')::uuid::text,true);
set local role authenticated;
select throws_ok($$select pg_temp.deliver()$$,'42501','quest access denied','чужой профиль не подставляется');
select throws_ok($$select public.list_offline_event_reviews(md5('review-quest')::uuid)$$,'42501','quest statistics access denied','чужая очередь закрыта');
reset role;
update public.quests set is_open=true where id=md5('review-quest')::uuid;
select set_config('request.jwt.claim.sub',md5('review-owner')::uuid::text,true);
select set_config('test.events',replace(current_setting('test.events'),'changed','input'),true);
select is(pg_temp.deliver(),current_setting('test.receipt')::jsonb,'повтор после открытия возвращает старый архив');
select throws_ok($$select public.register_offline_quest_attempt(md5('review-quest')::uuid,md5('review-owner')::uuid,'local-review')$$,'P0001','offline attempt requires review','архив не превращается в попытку после открытия');
select set_config('test.events',replace(current_setting('test.events'),md5('review-event')::uuid::text,md5('review-new')::uuid::text),true);
select throws_ok($$select pg_temp.deliver()$$,'23514','quest does not require offline review','новый архив открытого квеста отклонён');
update public.quests set is_open=false where id=md5('review-quest')::uuid;
delete from public.tasks where id=md5('review-task')::uuid;
select is(pg_temp.deliver()->>'state','needs_review','удалённое задание не теряет поздний архив');
select * from finish();
rollback;
