begin;
select no_plan();
insert into auth.users(id,email) select md5('permit-user-'||n)::uuid,'permit-user-'||n||'@example.test' from generate_series(0,2)n;
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=md5('permit-user-0')::uuid),true);
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1) where organization_id=current_setting('test.org')::uuid;
insert into public.participant_profiles(id,display_name,profile_kind,age_group,created_by_user_id) values(md5('permit-child')::uuid,'Synthetic child','dependent','child',md5('permit-user-0')::uuid);
insert into public.participant_supervisions(supervisor_user_id,participant_profile_id) select md5('permit-user-'||n)::uuid,md5('permit-child')::uuid from generate_series(0,1)n;
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public) select md5('permit-quest-'||n)::uuid,md5('permit-user-0')::uuid,current_setting('test.org')::uuid,'Permit fixture',true,true from generate_series(1,3)n;
select set_config('request.jwt.claim.sub',md5('permit-user-0')::uuid::text,true);
create function pg_temp.prepare(command text,quest integer default 1) returns jsonb language sql as $$select public.prepare_offline_start_permit(md5('permit-quest-'||quest)::uuid,md5('permit-child')::uuid,md5(command)::uuid)$$;
set local role service_role;
select set_config('test.permit',pg_temp.prepare('first')->>'id',true);
select is(pg_temp.prepare('first')->>'id',current_setting('test.permit'),'повтор команды');
select is(pg_temp.prepare('second')->>'id',current_setting('test.permit'),'другая команда тот же резерв');
select throws_ok($$select pg_temp.prepare('first',2)$$,'22023','offline permit command conflict','ключ нельзя переназначить');
select set_config('request.jwt.claim.sub',md5('permit-user-1')::uuid::text,true);
select is(pg_temp.prepare('another-controller')->>'id',current_setting('test.permit'),'общий резерв двух контролёров');
reset role;
select is((select count(*) from public.offline_start_permits where organization_id=current_setting('test.org')::uuid),1::bigint,'один резерв');
select is((select count(*) from public.quest_attempts where quest_id=md5('permit-quest-1')::uuid),0::bigint,'таймер и попытка не созданы');
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.org')::uuid),0::bigint,'месячное потребление не создано');
update public.organization_subscriptions set status='expired',period_start=now()-interval '30 days',period_end=now()-interval '6 days' where organization_id=current_setting('test.org')::uuid;
select is(pg_temp.prepare('after-expiry')->>'id',current_setting('test.permit'),'старое право сохраняется после просрочки');
select throws_ok($$select pg_temp.prepare('new-after-expiry',2)$$,'P0001','offline permit billing unavailable','новое право при просрочке запрещено');
update public.participant_supervisions set status='revoked',revoked_at=now() where supervisor_user_id=md5('permit-user-1')::uuid and participant_profile_id=md5('permit-child')::uuid;
select throws_ok($$select pg_temp.prepare('another-controller')$$,'42501','quest access denied','retry после отзыва контроля закрыт');
select set_config('request.jwt.claim.sub',md5('permit-user-2')::uuid::text,true);
select throws_ok($$select pg_temp.prepare('stranger')$$,'42501','quest access denied','чужой профиль закрыт');
select set_config('request.jwt.claim.sub',md5('permit-user-0')::uuid::text,true);
update public.organization_subscriptions set status='free',period_start=null,period_end=null where organization_id=current_setting('test.org')::uuid;
update public.quests set is_open=false where id=md5('permit-quest-2')::uuid;
select throws_ok($$select pg_temp.prepare('closed',2)$$,'23514','quest is not available','закрытый квест не выдаёт новый резерв');
select public.start_quest_attempt_for_participant(md5('permit-quest-3')::uuid,md5('permit-child')::uuid);
select throws_ok($$select pg_temp.prepare('active',3)$$,'23514','quest attempt already active','для активной попытки не создаём резерв');
update public.quest_attempts set finished_at=now() where quest_id=md5('permit-quest-3')::uuid;
update public.quests set max_quest_attempts=1 where id=md5('permit-quest-3')::uuid;
select throws_ok($$select pg_temp.prepare('limit',3)$$,'23514','quest completion limit reached','лимит попыток проверен');
set local role authenticated;
select lives_ok($$select pg_temp.prepare('client')$$,'клиент получает свой существующий резерв');
select throws_ok($$select * from public.offline_start_permits$$,'42501',null,'таблица прав закрыта');
select throws_ok($$select * from public.offline_start_permit_requests$$,'42501',null,'команды закрыты');
reset role;
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.offline_start_permits'::regclass,'public.offline_start_permit_requests'::regclass)),'RLS включён');
select * from finish();
rollback;
