begin;
select no_plan();
insert into auth.users(id,email) values(md5('limit-owner')::uuid,'limit-owner@example.test'),(md5('limit-other')::uuid,'limit-other@example.test');
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public,max_quest_attempts)
select md5('limit-quest')::uuid,md5('limit-owner')::uuid,id,'Limit',true,true,1 from public.organizations where personal_owner_id=md5('limit-owner')::uuid;
insert into public.tasks(id,quest_id,title) values(md5('limit-task')::uuid,md5('limit-quest')::uuid,'Task');
select set_config('request.jwt.claim.sub',md5('limit-owner')::uuid::text,true);
select set_config('test.events',jsonb_build_array(jsonb_build_object('clientEventId',md5('limit-event')::uuid,'taskId',md5('limit-task')::uuid,'eventType','answer','submittedValue','input'))::text,true);
create function pg_temp.deliver() returns jsonb language sql as $$select public.preserve_limit_rejected_offline_events(md5('limit-quest')::uuid,md5('limit-owner')::uuid,'local-limit',current_setting('test.events')::jsonb)$$;
set local role authenticated;
select is(public.get_participant_quest_summary(md5('limit-quest')::uuid,md5('limit-owner')::uuid)->>'completion_limit_reached','false','до прохождения старт доступен');
select throws_ok($$select pg_temp.deliver()$$,'23514','quest completion limit not reached','клиент не назначает отказ самостоятельно');
reset role;
insert into public.quest_attempts(id,quest_id,user_id,participant_profile_id,finished_at,total_tasks) values(md5('limit-finished')::uuid,md5('limit-quest')::uuid,md5('limit-owner')::uuid,md5('limit-owner')::uuid,clock_timestamp(),1);
set local role authenticated;
select is(public.get_participant_quest_summary(md5('limit-quest')::uuid,md5('limit-owner')::uuid)->>'completion_limit_reached','true','после прохождения UI получает исчерпанный лимит');
select throws_ok($$select public.start_quest_attempt_for_participant(md5('limit-quest')::uuid,md5('limit-owner')::uuid)$$,'23514','quest completion limit reached','сервер запрещает повторный старт');
select is(pg_temp.deliver()->>'state','invalid_limit','отклонённое прохождение сохранено');
select set_config('test.receipt',pg_temp.deliver()::text,true);
select is(pg_temp.deliver(),current_setting('test.receipt')::jsonb,'retry возвращает тот же receipt');
select is(jsonb_array_length(public.search_participant_quest_history(md5('limit-owner')::uuid)->'items'),2,'история содержит зачтённую и недействительную попытку');
select is(public.search_participant_quest_history(md5('limit-owner')::uuid)->'items'->0->>'outcome','invalid_limit','недействительная попытка имеет явный статус');
select is(jsonb_array_length(public.search_participant_quest_history(md5('limit-owner')::uuid,(public.search_participant_quest_history(md5('limit-owner')::uuid,null,1)->'next_cursor'),1)->'items'),1,'пагинация включает старую зачтённую попытку');
select throws_ok($$select * from public.offline_event_reviews$$,'42501',null,'прямое чтение архива запрещено');
reset role;
select is((select count(*) from public.quest_attempts where quest_id=md5('limit-quest')::uuid),1::bigint,'архив не увеличил статистику попыток');
select is((select count(*) from public.offline_event_reviews where quest_id=md5('limit-quest')::uuid),1::bigint,'retry не дублирует событие');
update public.quests set max_quest_attempts=0 where id=md5('limit-quest')::uuid;
set local role authenticated;
select is(pg_temp.deliver(),current_setting('test.receipt')::jsonb,'изменение лимита не меняет подтверждённый отказ');
select throws_ok($$select public.register_offline_quest_attempt(md5('limit-quest')::uuid,md5('limit-owner')::uuid,'local-limit',null)$$,'P0001','offline attempt rejected by limit','архив не превращается в зачтённую попытку');
select set_config('test.events',replace(current_setting('test.events'),'input','changed'),true);
select throws_ok($$select pg_temp.deliver()$$,'23505','offline review event conflict','тот же event ID с другим payload запрещён');
select set_config('request.jwt.claim.sub',md5('limit-other')::uuid::text,true);
select throws_ok($$select pg_temp.deliver()$$,'42501','quest access denied','чужой профиль запрещён');
select throws_ok($$select public.search_participant_quest_history(md5('limit-owner')::uuid)$$,'42501','participant history access denied','чужая история закрыта');
reset role;
select * from finish();
rollback;
