begin;
select no_plan();
insert into auth.users(id,email) values(md5('redeem-owner')::uuid,'redeem@example.test');
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=md5('redeem-owner')::uuid),true);
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1) where organization_id=current_setting('test.org')::uuid;
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public,time_limit_minutes) select md5('redeem-quest-'||n)::uuid,md5('redeem-owner')::uuid,current_setting('test.org')::uuid,'Redeem fixture',true,true,30 from generate_series(1,3)n;
select set_config('request.jwt.claim.sub',md5('redeem-owner')::uuid::text,true);
select set_config('test.permit',public.prepare_offline_start_permit(md5('redeem-quest-1')::uuid,md5('redeem-owner')::uuid,md5('redeem-command')::uuid)->>'id',true);
select public.prepare_offline_start_permit(md5('redeem-quest-2')::uuid,md5('redeem-owner')::uuid,md5('redeem-command2')::uuid);
select public.prepare_offline_start_permit(md5('redeem-quest-3')::uuid,md5('redeem-owner')::uuid,md5('redeem-command3')::uuid);
update public.organization_subscriptions set status='expired',period_start=now()-interval '30 days',period_end=now()-interval '6 days' where organization_id=current_setting('test.org')::uuid;
create function pg_temp.redeem() returns jsonb language sql as $$select public.redeem_offline_start_permit(current_setting('test.permit')::uuid)$$;
savepoint first_try;
select pg_temp.redeem();
rollback to first_try;
select is((select state from public.offline_start_permits where id=current_setting('test.permit')::uuid),'reserved','rollback возвращает резерв');
select is((select count(*) from public.quest_attempts where quest_id=md5('redeem-quest-1')::uuid),0::bigint,'rollback не оставляет попытку');
set local role service_role;
select set_config('test.attempt',pg_temp.redeem()->>'id',true);
select is(pg_temp.redeem()->>'id',current_setting('test.attempt'),'retry после просрочки возвращает одну попытку');
reset role;
select is((select deadline_at from public.quest_attempts where id=current_setting('test.attempt')::uuid),(select started_at+interval '30 minutes' from public.quest_attempts where id=current_setting('test.attempt')::uuid),'таймер создаётся при старте');
select is((select count(*) from public.participant_usage_registrations where server_attempt_id=current_setting('test.attempt')::uuid),1::bigint,'одно потребление');
set local role authenticated;
select lives_ok($$select public.start_quest_attempt(md5('redeem-quest-2')::uuid)$$,'старый online RPC работает');
select lives_ok($$select public.start_quest_attempt_for_participant(md5('redeem-quest-3')::uuid,md5('redeem-owner')::uuid)$$,'профильный online RPC работает');
select throws_ok($$select pg_temp.redeem()$$,'42501',null,'клиентское погашение пока закрыто');
reset role;
select is((select count(*) from public.offline_start_permits where organization_id=current_setting('test.org')::uuid and state='redeemed'),3::bigint,'оба online пути погасили резервы');
update public.quest_attempts set finished_at=now() where id=current_setting('test.attempt')::uuid;
update public.quests set is_open=false where id=md5('redeem-quest-1')::uuid;
select is(pg_temp.redeem()->>'id',current_setting('test.attempt'),'retry закрытой попытки при закрытом квесте');
select ok(pg_temp.redeem()->>'finished_at' is not null,'закрытая попытка не возобновляется');
delete from public.quest_attempts where id=current_setting('test.attempt')::uuid;
select throws_ok($$select pg_temp.redeem()$$,'P0001','redeemed offline attempt removed','удалённая попытка не пересоздаётся');
select is((select state from public.offline_start_permits where id=current_setting('test.permit')::uuid),'redeemed','удаление не возвращает резерв');
select set_config('request.jwt.claim.sub',md5('redeem-stranger')::uuid::text,true);
select throws_ok($$select pg_temp.redeem()$$,'42501','offline permit access denied','чужой профиль закрыт');
select * from finish();
rollback;
