begin;
select no_plan();
insert into auth.users(id,email) values(md5('usage-owner')::uuid,'usage-owner@example.test');
select set_config('test.usage_org',(select id::text from public.organizations where personal_owner_id=md5('usage-owner')::uuid),true);
insert into public.quests(id,creator_id,organization_id,title,is_open) select md5('usage-quest-'||n)::uuid,md5('usage-owner')::uuid,current_setting('test.usage_org')::uuid,'Usage fixture',false from generate_series(1,2)n;
insert into public.quest_attempts(id,quest_id,user_id,total_tasks,started_at,finished_at)
select md5('usage-attempt-'||n)::uuid,md5('usage-quest-'||n)::uuid,md5('usage-owner')::uuid,0,'2000-01-01'::timestamptz,'2000-01-02'::timestamptz from generate_series(1,2)n;
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),2::bigint,'каждая новая попытка имеет факт регистрации');
select is((select count(distinct participant_profile_id) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),1::bigint,'два квеста одного профиля дают одного уникального участника');
select ok((select bool_and(period_start=date_trunc('month',statement_timestamp() at time zone 'Europe/Moscow') at time zone 'Europe/Moscow') from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),'месяц задаёт сервер, а не started_at');
select ok((select bool_and(period_end=(date_trunc('month',statement_timestamp() at time zone 'Europe/Moscow')+interval '1 month') at time zone 'Europe/Moscow') from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),'конец периода — начало следующего месяца Moscow');
update public.quest_attempts set total_tasks=2 where id=md5('usage-attempt-1')::uuid;
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),2::bigint,'обновление попытки не создаёт новый факт');
delete from public.quest_attempts where id=md5('usage-attempt-1')::uuid;
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),2::bigint,'удаление результатов не уменьшает журнал');
insert into public.quest_attempts(id,quest_id,user_id,total_tasks) values(md5('usage-attempt-1')::uuid,md5('usage-quest-1')::uuid,md5('usage-owner')::uuid,0);
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),2::bigint,'повтор server ID после удаления не учитывается снова');
select set_config('request.jwt.claim.sub',md5('usage-owner')::uuid::text,true);
set local role authenticated;
select throws_ok($$select * from public.participant_usage_registrations$$,'42501',null,'даже владелец не читает список фактов напрямую');
select throws_ok($$delete from public.participant_usage_registrations$$,'42501',null,'клиент не удаляет учёт');
select throws_ok($$insert into public.participant_usage_registrations default values$$,'42501',null,'клиент не создаёт учёт');
reset role;
set local role anon;
select throws_ok($$select * from public.participant_usage_registrations$$,'42501',null,'anon закрыт');
reset role;
savepoint usage_rollback;
insert into public.quest_attempts(id,quest_id,user_id,total_tasks,finished_at) values(md5('usage-rollback')::uuid,md5('usage-quest-2')::uuid,md5('usage-owner')::uuid,0,now());
rollback to savepoint usage_rollback;
select is((select count(*) from public.participant_usage_registrations where server_attempt_id=md5('usage-rollback')::uuid),0::bigint,'откат попытки откатывает регистрацию');
update public.quests set is_open=true,is_public=true where id=md5('usage-quest-2')::uuid;
set local role authenticated;
select lives_ok($$select * from public.start_quest_attempt_for_participant(md5('usage-quest-2')::uuid,md5('usage-owner')::uuid)$$,'профильный RPC создаёт попытку с учётом');
select lives_ok($$select * from public.start_quest_attempt_for_participant(md5('usage-quest-2')::uuid,md5('usage-owner')::uuid)$$,'повтор профильного RPC успешен');
select lives_ok($$select * from public.start_quest_attempt(md5('usage-quest-2')::uuid)$$,'совместимый RPC возвращает ту же активную попытку');
reset role;
select is((select count(*) from public.participant_usage_registrations where organization_id=current_setting('test.usage_org')::uuid),3::bigint,'три вызова RPC создают один новый факт');
select * from finish();
rollback;
