begin;
select no_plan();
insert into auth.users(id,email) values(md5('permit-reg-owner')::uuid,'permit-reg@example.test');
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=md5('permit-reg-owner')::uuid),true);
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1) where organization_id=current_setting('test.org')::uuid;
insert into public.quests(id,creator_id,organization_id,title,is_open,is_public) select md5('permit-reg-quest-'||n)::uuid,md5('permit-reg-owner')::uuid,current_setting('test.org')::uuid,'Permit reg',true,true from generate_series(1,2)n;
select set_config('request.jwt.claim.sub',md5('permit-reg-owner')::uuid::text,true);
select set_config('test.permit',public.prepare_offline_start_permit(md5('permit-reg-quest-1')::uuid,md5('permit-reg-owner')::uuid,md5('permit-reg-command')::uuid)->>'id',true);
create function pg_temp.register(local_id text) returns jsonb language sql as $$select public.register_permitted_offline_attempt(md5('permit-reg-quest-1')::uuid,md5('permit-reg-owner')::uuid,local_id,current_setting('test.permit')::uuid)$$;
savepoint initial;
select pg_temp.register('one');
rollback to initial;
select is((select state from public.offline_start_permits where id=current_setting('test.permit')::uuid),'reserved','rollback сохраняет резерв');
select is((select count(*) from public.offline_attempt_registrations where actor_user_id=md5('permit-reg-owner')::uuid),0::bigint,'rollback удаляет сопоставление');
set local role service_role;
select set_config('test.attempt',pg_temp.register('one')->>'id',true);
select is(pg_temp.register('one')->>'id',current_setting('test.attempt'),'retry возвращает прежний ID');
select throws_ok($$select pg_temp.register('two')$$,'23505','offline permit already bound','другая локальная история не присоединяется');
select throws_ok($$select public.register_permitted_offline_attempt(md5('permit-reg-quest-2')::uuid,md5('permit-reg-owner')::uuid,'one',current_setting('test.permit')::uuid)$$,'42501','offline permit scope mismatch','подмена квеста запрещена');
reset role;
select is((select count(*) from public.quest_attempts where quest_id=md5('permit-reg-quest-1')::uuid),1::bigint,'одна попытка');
select is((select count(*) from public.offline_attempt_registrations where permit_id=current_setting('test.permit')::uuid),1::bigint,'одна привязка');
update public.quest_attempts set finished_at=now() where id=current_setting('test.attempt')::uuid;
select ok(pg_temp.register('one')->>'finished_at' is not null,'завершение не возобновляется');
delete from public.quest_attempts where id=current_setting('test.attempt')::uuid;
select throws_ok($$select pg_temp.register('one')$$,'P0001','redeemed offline attempt removed','удалённая попытка не пересоздаётся');
select throws_ok($$select pg_temp.register('two')$$,'23505','offline permit already bound','удаление не разрешает другую историю');
select set_config('test.permit2',public.prepare_offline_start_permit(md5('permit-reg-quest-2')::uuid,md5('permit-reg-owner')::uuid,md5('permit-reg-command2')::uuid)->>'id',true);
select public.start_quest_attempt(md5('permit-reg-quest-2')::uuid);
select throws_ok($$select public.register_permitted_offline_attempt(md5('permit-reg-quest-2')::uuid,md5('permit-reg-owner')::uuid,'offline-after-online',current_setting('test.permit2')::uuid)$$,'23505','offline permit already bound','online-погашение не принимает независимую offline-историю');
set local role authenticated;
select throws_ok($$select pg_temp.register('one')$$,'P0001','redeemed offline attempt removed','клиентская регистрация проверяет отсутствие исходной попытки');
reset role;
select * from finish();
rollback;
