begin;
select no_plan();
insert into auth.users(id,email) values(md5('publish-owner')::uuid,'publish-owner@example.test');
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('publish-owner')::uuid,'owner','platform');
select set_config('request.jwt.claim.sub',md5('publish-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.source',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
select set_config('test.future',(now()+interval '2 days')::text,true);
set local role authenticated;
select public.save_platform_tariff_draft(md5('publish-save')::uuid,md5('publish-draft')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14);
select throws_ok($t$select public.publish_tariff_draft(md5('bad-date')::uuid,md5('publish-draft')::uuid,1,now())$t$,'22023','publication must be in future','past rejected');
select throws_ok($t$select public.publish_tariff_draft(md5('bad-revision')::uuid,md5('publish-draft')::uuid,2,now()+interval '2 days')$t$,'40001','draft revision conflict','stale revision rejected');
select set_config('test.published',public.publish_tariff_draft(md5('publish')::uuid,md5('publish-draft')::uuid,1,current_setting('test.future')::timestamptz)::text,true);

select set_config('test.page',public.read_platform_tariff_timeline(current_setting('test.source')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.page')::jsonb->'items'),2,'историческая и будущая версии видны вместе');
select is(current_setting('test.page')::jsonb#>>'{items,0,state}','current','первая версия актуальна');
select is(current_setting('test.page')::jsonb#>>'{items,1,state}','scheduled','следующая запланирована');
select is(current_setting('test.page')::jsonb#>>'{items,1,number}','2','номер определяется хронологией');
select is(current_setting('test.page')::jsonb#>>'{items,1,can_revoke}','true','будущая версия допускает отзыв');
select is(public.read_platform_tariff_catalog(null,(current_setting('test.published')::jsonb->>'version_id')::uuid)#>>'{items,0,timeline_number}','2','каталог показывает хронологический номер');
select is((select value->>'is_published' from jsonb_array_elements(public.read_platform_tariff_drafts(current_setting('test.source')::uuid)->'items') where value->>'id'=md5('publish-draft')::uuid::text),'true','опубликованный черновик только для чтения');
select is((select value#>>'{latest_publication,state}' from jsonb_array_elements(public.read_platform_tariff_drafts(current_setting('test.source')::uuid)->'items') where value->>'id'=md5('publish-draft')::uuid::text),'scheduled','список черновиков показывает публикацию');
select public.revoke_tariff_publication(md5('read-revoke')::uuid,(current_setting('test.published')::jsonb->>'version_id')::uuid);
select is(public.read_platform_tariff_timeline(current_setting('test.source')::uuid)#>>'{items,1,state}','revoked','после перезагрузки виден отзыв');
select is(public.read_platform_tariff_timeline(current_setting('test.source')::uuid)#>>'{items,1,number}',null::text,'отозванная версия без номера');
select is((select value->>'is_published' from jsonb_array_elements(public.read_platform_tariff_drafts(current_setting('test.source')::uuid)->'items') where value->>'id'=md5('publish-draft')::uuid::text),'false','после отзыва черновик доступен для правок');
select is(public.read_platform_tariff_catalog(null,(current_setting('test.published')::jsonb->>'version_id')::uuid)#>>'{items,0,timeline_number}',null::text,'отзыв сбрасывает отображаемый номер каталога');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select throws_ok($t$select public.read_platform_tariff_timeline(current_setting('test.source')::uuid)$t$,'42501',null,'чтение требует MFA');
reset role;
select ok(not has_function_privilege('anon','public.read_platform_tariff_timeline(uuid,jsonb)','execute'),'анонимное чтение закрыто');
select * from finish();rollback;
