begin;
select no_plan();
insert into auth.users(id,email) select md5('bootstrap-'||n)::uuid,'bootstrap-'||n||'@example.test' from generate_series(1,2)n;
select throws_ok($$select platform_private.bootstrap_owner(null,md5('bootstrap-1')::uuid)$$,'22023','invalid platform bootstrap','command ID обязателен');
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-missing')::uuid)$$,'22023','platform bootstrap account unavailable','отсутствующий аккаунт не назначается');
set local role anon;
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)$$,'42501',null,'anon закрыт');
reset role;
set local role authenticated;
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)$$,'42501',null,'authenticated закрыт');
reset role;
set local role service_role;
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)$$,'42501',null,'service role закрыт');
reset role;
select set_config('test.bootstrap_assignment',platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)::text,true);
select is(platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)::text,current_setting('test.bootstrap_assignment'),'повтор возвращает то же назначение');
select is((select count(*)::int from public.platform_access_assignments where role_key='owner'),1,'создан один владелец');
select is((select count(*)::int from public.platform_audit_events where action='assignment.created'),1,'одна запись аудита');
select is((select database_operator from platform_private.owner_bootstrap),session_user::text,'оператор БД сохранён');
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-other-command')::uuid,md5('bootstrap-1')::uuid)$$,'23514','platform bootstrap already completed','новая команда запрещена');
select throws_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-2')::uuid)$$,'23514','platform bootstrap already completed','подмена пользователя запрещена');
update public.platform_access_assignments set revoked_at=now() where id=current_setting('test.bootstrap_assignment')::uuid;
select lives_ok($$select platform_private.bootstrap_owner(md5('bootstrap-command')::uuid,md5('bootstrap-1')::uuid)$$,'исторический receipt доступен');
select ok((select revoked_at is not null from public.platform_access_assignments where id=current_setting('test.bootstrap_assignment')::uuid),'retry не восстанавливает отозванную роль');
select ok(not (select prosecdef from pg_proc where oid='platform_private.bootstrap_owner(uuid,uuid)'::regprocedure),'bootstrap не повышает SQL-привилегии');
select * from finish();
rollback;
