begin;
select no_plan();
insert into auth.users(id,email) values(md5('tariff-operator')::uuid,'tariff-operator@example.test');
select set_config('request.jwt.claim.sub',md5('tariff-operator')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','ordinary account denied');
select throws_ok('select * from public.platform_tariff_read_events','42501',null,'audit private');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('tariff-operator')::uuid,'sales','platform');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','MFA required');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
set local role authenticated;
select ok(jsonb_array_length(public.read_platform_tariff_catalog()->'items')>0,'platform sales reads');
reset role;
select ok((select count(*)>0 from public.platform_tariff_read_events where actor_id=md5('tariff-operator')::uuid),'read audited');
update public.platform_access_assignments set scope_kind='organization',organization_id=(select id from public.organizations where personal_owner_id=md5('tariff-operator')::uuid) where user_id=md5('tariff-operator')::uuid;
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','organization scope not global');
reset role;
update public.platform_access_assignments set scope_kind='platform',organization_id=null,role_key='operations' where user_id=md5('tariff-operator')::uuid;
insert into public.billing_plan_versions(plan_key,version,display_name,active_quests_limit,team_members_limit)
select 'catalog_test',n,'Catalog',0,1 from generate_series(1,30)n;
set local role authenticated;
select is(jsonb_array_length(public.read_platform_tariff_catalog()->'items'),25,'bounded page');
select ok(public.read_platform_tariff_catalog()->>'next_cursor' is not null,'cursor returned');
select is(jsonb_array_length(public.read_platform_tariff_catalog(null,(select id from public.billing_plan_versions where plan_key='catalog_test' and version=1))->'items'),1,'exact version');
select set_config('test.catalog.first',public.read_platform_tariff_catalog()::text,true);
select set_config('test.catalog.second',public.read_platform_tariff_catalog((current_setting('test.catalog.first')::jsonb->>'next_cursor')::uuid)::text,true);
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.catalog.first')::jsonb->'items') a join jsonb_array_elements(current_setting('test.catalog.second')::jsonb->'items') b on a->>'id'=b->>'id'),'pages do not overlap');
select is(jsonb_array_length(current_setting('test.catalog.first')::jsonb->'items')+jsonb_array_length(current_setting('test.catalog.second')::jsonb->'items'),(select count(*)::int from public.billing_plan_versions),'pages cover catalog');
select is(public.read_platform_tariff_catalog(null,md5('unknown-version')::uuid)->'items','[]'::jsonb,'missing version empty');
reset role;
update public.platform_access_assignments set valid_from=now()-interval '2 hours',expires_at=now()-interval '1 hour' where user_id=md5('tariff-operator')::uuid;
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','expired assignment denied');
reset role;
update public.platform_access_assignments set valid_from=now()+interval '1 hour',expires_at=null where user_id=md5('tariff-operator')::uuid;
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','future assignment denied');
reset role;
update public.platform_access_assignments set role_key='owner',valid_from=now() where user_id=md5('tariff-operator')::uuid;
set local role authenticated;
select lives_ok('select public.read_platform_tariff_catalog()','platform owner reads');
select throws_ok($$select public.read_platform_tariff_catalog(md5('a')::uuid,md5('b')::uuid)$$,'22023','invalid catalog cursor','ambiguous request rejected');
reset role;
update public.platform_access_assignments set revoked_at=now() where user_id=md5('tariff-operator')::uuid;
set local role authenticated;
select throws_ok('select public.read_platform_tariff_catalog()','42501','platform access denied','revoked immediately');
reset role;
set local role anon;
select throws_ok('select public.read_platform_tariff_catalog()','42501',null,'anon denied');
reset role;
set local role service_role;
select throws_ok('select public.read_platform_tariff_catalog()','42501',null,'service role denied');
reset role;
select * from finish();
rollback;
