begin;
select no_plan();
insert into auth.users(id,email) values(md5('payment-reader')::uuid,'payment-reader@example.test'),(md5('payment-other')::uuid,'payment-other@example.test');
select set_config('request.jwt.claim.sub',md5('payment-reader')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('payment-other')::uuid),true);
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501','platform access denied','membership не даёт системное право');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id) values(auth.uid(),'sales','organization',current_setting('test.org')::uuid);
insert into public.billing_sandbox_orders(id,organization_id,actor_id,command_id,plan_version_id,expected_revision,amount_minor,currency,shop_id,return_url,period_start,period_end,state,created_at)
select md5('payment-page-'||n)::uuid,current_setting('test.org')::uuid,auth.uid(),gen_random_uuid(),(select id from public.billing_plan_versions where plan_key='pro' and version=1),0,1000,'RUB','123','https://stage.qvesta.ru',now(),now()+interval '1 month','finished',now() from generate_series(1,30)n;
insert into public.billing_sandbox_payment_results(order_id,shop_id,payment_id,status,paid,requires_review)
values(md5('payment-page-1')::uuid,'123',md5('payment-id')::uuid,'succeeded',true,false);
insert into public.billing_sandbox_refunds(order_id,actor_id,command_id,amount_minor,payment_id,state)
select md5('payment-page-1')::uuid,auth.uid(),gen_random_uuid(),10,md5('payment-id')::uuid,state from unnest(array['succeeded','reserved','sending','pending','review','canceled','rejected'])state;
insert into public.billing_sandbox_fulfillments(order_id,state,reason) values
(md5('payment-page-1')::uuid,'deferred','future_period'),
(md5('payment-page-2')::uuid,'review','private-provider-diagnostic'),
(md5('payment-page-3')::uuid,'review','payment_conflict');
select set_config('test.expected_order',(select array_agg(id order by created_at desc,id desc)::text from public.billing_sandbox_orders where organization_id=current_setting('test.org')::uuid),true);
set local role authenticated;
select set_config('test.page',public.read_platform_organization_payments(current_setting('test.org')::uuid)::text,true);
select set_config('test.next',public.read_platform_organization_payments(current_setting('test.org')::uuid,(current_setting('test.page')::jsonb->>'next_cursor')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.page')::jsonb->'items'),25,'размер страницы');
select is(jsonb_array_length(current_setting('test.next')::jsonb->'items'),5,'остаток страницы');
select ok(current_setting('test.next')::jsonb->>'next_cursor' is null,'конец каталога');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.page')::jsonb->'items') a join jsonb_array_elements(current_setting('test.next')::jsonb->'items') b on a->>'id'=b->>'id'),'одинаковые даты не создают дубликаты');
select set_config('test.items',((current_setting('test.page')::jsonb->'items')||(current_setting('test.next')::jsonb->'items'))::text,true);
select is((select array_agg((x->>'id')::uuid order by ord) from jsonb_array_elements(current_setting('test.items')::jsonb) with ordinality a(x,ord)),current_setting('test.expected_order')::uuid[],'точный порядок при одинаковых датах');
select set_config('test.paid',(select x::text from jsonb_array_elements(current_setting('test.items')::jsonb)x where x->>'id'=md5('payment-page-1')::uuid::text),true);
select is(current_setting('test.paid')::jsonb->>'refunded_minor','10','возвращённая сумма');
select is(current_setting('test.paid')::jsonb->>'refund_pending_minor','30','ожидающие отдельно');
select is(current_setting('test.paid')::jsonb->>'refund_review_minor','10','неопределённые суммы не теряются');
select is(current_setting('test.paid')::jsonb->>'refund_requires_review','true','нужна проверка');
select is(current_setting('test.paid')::jsonb->>'payment_status','succeeded','подтверждённая оплата');
select is((select count(*) from jsonb_array_elements(current_setting('test.items')::jsonb)x where x->>'payment_status'='not_created'),29::bigint,'заказ без платежа не выдаётся за оплату');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.items')::jsonb)x where x ?| array['shop_id','actor_id','command_id','idempotency_key','confirmation_url','n']),'служебные поля скрыты');
select is(current_setting('test.paid')::jsonb->>'fulfillment_state','deferred','будущий период отделён от проверки');
select is(current_setting('test.paid')::jsonb->>'fulfillment_reason','future_period','безопасная причина ожидания');
select ok(current_setting('test.paid')::jsonb->>'period_start' is not null,'дата начала доступна');
select is((select x->>'fulfillment_reason' from jsonb_array_elements(current_setting('test.items')::jsonb)x where x->>'id'=md5('payment-page-2')::uuid::text),'other','неизвестная диагностика скрыта');
select is((select x->>'fulfillment_reason' from jsonb_array_elements(current_setting('test.items')::jsonb)x where x->>'id'=md5('payment-page-3')::uuid::text),'payment_conflict','конфликт платежа классифицирован');
select ok(position('private-provider' in current_setting('test.items'))=0,'нет утечки диагностики');
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.other')::uuid)$t$,'42501','platform access denied','чужая область');
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid,gen_random_uuid())$t$,'22023','invalid payment cursor','неизвестный курсор');
select throws_ok('select * from public.billing_sandbox_orders','42501',null,'заказы закрыты напрямую');
select throws_ok('select * from public.billing_sandbox_refunds','42501',null,'возвраты закрыты напрямую');
select throws_ok('select * from public.platform_payment_read_events','42501',null,'аудит закрыт напрямую');
reset role;
select is((select count(*) from public.platform_payment_read_events where actor_id=auth.uid()),2::bigint,'успешное чтение аудировано');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501','platform access denied','MFA обязательна');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
update public.platform_access_assignments set valid_from=now()-interval '2 days',expires_at=now()-interval '1 day' where user_id=auth.uid();
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501','platform access denied','истёкшее назначение');
reset role;
update public.platform_access_assignments set expires_at=null,revoked_at=now() where user_id=auth.uid();
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501','platform access denied','отзыв действует сразу');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
set local role authenticated;
select is(jsonb_array_length(public.read_platform_organization_payments(current_setting('test.other')::uuid)->'items'),0,'владелец видит пустую другую организацию');
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.other')::uuid,md5('payment-page-1')::uuid)$t$,'22023','invalid payment cursor','курсор чужой организации');
reset role;
set local role anon;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501',null,'анонимный доступ закрыт');
reset role;
set local role service_role;
select throws_ok($t$select public.read_platform_organization_payments(current_setting('test.org')::uuid)$t$,'42501',null,'service role не вызывает RPC пользователя');
reset role;
insert into public.billing_sandbox_application_scope(organization_id) values(current_setting('test.org')::uuid) on conflict do nothing;
set local role authenticated;
select is(public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)->>'available_minor','950','остаток удерживает успешные, ожидающие и review возвраты');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,50)$t$,'22023','refund provider amount limits','invalid partial boundary 50');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,99)$t$,'22023','refund provider amount limits','invalid partial boundary 99');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,851)$t$,'22023','refund provider amount limits','invalid partial boundary 851');
select is(public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,250)->>'requested_minor','250','частичный расчёт');
select is(public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)->>'access_effect','unchanged','доступ сохраняется');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,951)$t$,'22023','invalid refund amount','нельзя превысить остаток');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,0)$t$,'22023','invalid refund amount','нулевой возврат запрещён');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-2')::uuid)$t$,'22023','sandbox payment not refundable','нет подтверждённой оплаты');
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.other')::uuid,md5('payment-page-1')::uuid)$t$,'42501','sandbox refund scope denied','заказ другой карточки запрещён');
select throws_ok('select * from public.platform_refund_preview_events','42501',null,'журнал расчётов закрыт');
select throws_ok($t$select public.reserve_sandbox_refund(md5('payment-page-1')::uuid,gen_random_uuid(),10)$t$,'42501',null,'расчёт не разрешает резервирование');
reset role;
select is((select count(*) from public.billing_sandbox_refunds where order_id=md5('payment-page-1')::uuid),7::bigint,'preview не создаёт возвраты');
select is((select count(*) from public.platform_refund_preview_events where actor_id=auth.uid()),3::bigint,'расчёты аудированы');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($t$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)$t$,'42501','platform access denied','preview требует MFA');
reset role;
select set_config('test.refund_command',gen_random_uuid()::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
set local role authenticated;
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,100,'customer_request',current_setting('test.refund_command')::uuid)$t$,'42501','recent platform MFA required','подтверждение требует свежий MFA');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,50,'customer_request',gen_random_uuid())$t$,'22023','refund provider amount limits','confirmation rechecks provider limits');
select set_config('test.confirmed',public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,100,'customer_request',current_setting('test.refund_command')::uuid)::text,true);
select is(current_setting('test.confirmed')::jsonb->>'already_confirmed','false','новый резерв');
select is(public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,100,'customer_request',current_setting('test.refund_command')::uuid)->>'refund_id',current_setting('test.confirmed')::jsonb->>'refund_id','повтор возвращает тот же резерв');
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,101,'customer_request',current_setting('test.refund_command')::uuid)$t$,'22023','refund command conflict','смена суммы той же команды запрещена');
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,100,'service_issue',current_setting('test.refund_command')::uuid)$t$,'22023','refund command conflict','смена причины запрещена');
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,851,'customer_request',gen_random_uuid())$t$,'22023','invalid refund amount','остаток повторно проверен после резерва');
select throws_ok('select * from public.platform_refund_commands','42501',null,'журнал команд закрыт');
reset role;
select is((select count(*) from public.billing_sandbox_refunds where order_id=md5('payment-page-1')::uuid),8::bigint,'создан только один резерв');
select is((select state from public.billing_sandbox_refunds where id=(current_setting('test.confirmed')::jsonb->>'refund_id')::uuid),'reserved','не отправлен');
select is((select count(*) from public.platform_refund_commands where actor_id=auth.uid()),1::bigint,'команда аудирована один раз');
-- Только синтетическая БД: допускаем reconciliation snapshot для тестового заказа.
update public.billing_sandbox_orders set first_sent_at=now() where id=md5('payment-page-1')::uuid;
set local role authenticated;
select throws_ok($t$select public.begin_sandbox_refund((current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)$t$,'42501',null,'браузер не вызывает отправку напрямую');
reset role;
set local role service_role;
select is(public.begin_sandbox_refund((current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)->>'can_send','true','сервер с владельцем допускает подтверждённый резерв без operator allowlist');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
set local role service_role;
select throws_ok($t$select public.begin_sandbox_refund((current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)$t$,'42501','recent platform MFA required','повтор требует свежий MFA');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.gateway_actor',auth.uid()::text,true);
set local role authenticated;
select throws_ok($t$select public.sandbox_refund_from_gateway(current_setting('test.gateway_actor')::uuid,extract(epoch from now())::bigint,extract(epoch from now())::bigint+100,'read',(current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)$t$,'42501',null,'браузер не может подставить MFA в gateway');
reset role;
select set_config('test.previous_claims',current_setting('request.jwt.claims'),true);
set local role service_role;
select is(public.sandbox_refund_from_gateway(current_setting('test.gateway_actor')::uuid,floor(extract(epoch from clock_timestamp()))::bigint,floor(extract(epoch from clock_timestamp()))::bigint+100,'read',(current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)->'refund'->>'id',current_setting('test.confirmed')::jsonb->>'refund_id','gateway читает подтверждённый резерв');
select is(current_setting('request.jwt.claims'),current_setting('test.previous_claims'),'gateway восстанавливает claims');
select throws_ok($t$select public.sandbox_refund_from_gateway(current_setting('test.gateway_actor')::uuid,1,2,'begin',(current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)$t$,'42501','invalid refund gateway context','старый контекст не принимается');
select throws_ok($t$select public.sandbox_refund_from_gateway(current_setting('test.gateway_actor')::uuid,floor(extract(epoch from clock_timestamp()))::bigint,floor(extract(epoch from clock_timestamp()))::bigint+100,'read',gen_random_uuid())$t$,'42501','confirmed refund required','неподтверждённый резерв закрыт');
select is(current_setting('request.jwt.claims'),current_setting('test.previous_claims'),'claims сохранены после ошибки');
reset role;
set local role authenticated;
select set_config('test.refund_history',public.read_platform_order_refunds(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.refund_history')::jsonb->'items'),8,'восстановление видит журнал возвратов');
select is((select count(*) from jsonb_array_elements(current_setting('test.refund_history')::jsonb->'items')x where (x->>'can_resume')::boolean),1::bigint,'продолжить можно только подтверждённую незавершённую операцию');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.refund_history')::jsonb->'items')x where x ?| array['actor_id','command_id','payment_id','provider_refund_id']),'история не раскрывает служебные поля');
select throws_ok($t$select public.read_platform_order_refunds(current_setting('test.other')::uuid,md5('payment-page-1')::uuid)$t$,'42501','order unavailable','заказ другой организации запрещён');
select throws_ok($t$select public.read_platform_order_refunds(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,gen_random_uuid())$t$,'22023','invalid refund cursor','неизвестный курсор запрещён');
reset role;
insert into public.billing_sandbox_refunds(id,order_id,actor_id,command_id,amount_minor,payment_id,state,created_at)
select md5('history-page-'||n)::uuid,md5('payment-page-1')::uuid,auth.uid(),gen_random_uuid(),1,md5('payment-id')::uuid,'rejected',now()+interval '1 day'
from generate_series(1,30)n;
select set_config('test.history_expected',(select array_agg(id order by created_at desc,id desc)::text from public.billing_sandbox_refunds where order_id=md5('payment-page-1')::uuid),true);
set local role authenticated;
select set_config('test.history_first',public.read_platform_order_refunds(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)::text,true);
select set_config('test.history_next',public.read_platform_order_refunds(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,(current_setting('test.history_first')::jsonb->>'next_cursor')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.history_first')::jsonb->'items'),25,'история первая страница 25');
select is(jsonb_array_length(current_setting('test.history_next')::jsonb->'items'),13,'история остаток 13');
select ok(current_setting('test.history_next')::jsonb->>'next_cursor' is null,'история конец страниц');
select is((select array_agg((x->>'id')::uuid order by ord) from jsonb_array_elements((current_setting('test.history_first')::jsonb->'items')||(current_setting('test.history_next')::jsonb->'items')) with ordinality a(x,ord)),current_setting('test.history_expected')::uuid[],'порядок истории при одинаковых датах без потерь и дублей');
reset role;
insert into public.billing_sandbox_refund_operators(actor_id) values(auth.uid());
update public.platform_access_assignments set revoked_at=now() where user_id=auth.uid() and role_key='owner';
set local role authenticated;
select throws_ok($t$select public.confirm_platform_sandbox_refund(current_setting('test.org')::uuid,md5('payment-page-1')::uuid,100,'customer_request',current_setting('test.refund_command')::uuid)$t$,'42501','platform owner required','отзыв блокирует даже повтор');
reset role;
set local role service_role;
select throws_ok($t$select public.begin_sandbox_refund((current_setting('test.confirmed')::jsonb->>'refund_id')::uuid)$t$,'42501','platform owner required','operator allowlist не обходит отзыв владельца');
select throws_ok($t$select public.record_sandbox_refund((current_setting('test.confirmed')::jsonb->>'refund_id')::uuid,gen_random_uuid(),'succeeded')$t$,'42501','platform owner required','запись результата также проверяет полномочия');
reset role;
set local role authenticated;
select throws_ok($t$select public.read_platform_order_refunds(current_setting('test.org')::uuid,md5('payment-page-1')::uuid)$t$,'42501','platform access denied','история закрыта после отзыва');
reset role;
select * from finish();
rollback;
