begin;
select no_plan();
insert into auth.users(id,email) values(md5('quest-admin')::uuid,'quest-admin@example.test'),(md5('quest-other')::uuid,'quest-other@example.test');
select set_config('request.jwt.claim.sub',md5('quest-admin')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('quest-other')::uuid),true);
insert into public.quests(id,organization_id,creator_id,title,description,created_at,is_open,is_public)
select md5('admin-quest-'||n)::uuid,current_setting('test.org')::uuid,auth.uid(),'Quest '||n,'PRIVATE',now(),n%2=0,false from generate_series(1,30)n;
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501','platform access denied','membership alone denied');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id) values(auth.uid(),'operations','organization',current_setting('test.org')::uuid);
set local role authenticated;
select set_config('test.page',public.read_platform_organization_quests(current_setting('test.org')::uuid)::text,true);
select set_config('test.next',public.read_platform_organization_quests(current_setting('test.org')::uuid,'','all',current_setting('test.page')::jsonb->'next_cursor')::text,true);
select is(jsonb_array_length(current_setting('test.page')::jsonb->'items'),25,'first page');
select is(jsonb_array_length(current_setting('test.next')::jsonb->'items'),5,'second page equal dates');
select is((select count(distinct x->>'id') from jsonb_array_elements((current_setting('test.page')::jsonb->'items')||(current_setting('test.next')::jsonb->'items')) x),30::bigint,'no duplicates');
select is(current_setting('test.page')::jsonb->'summary', '{"total":30,"open":15,"closed":15}'::jsonb,'summary');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.page')::jsonb->'items')x, jsonb_object_keys(x) k where k not in ('id','title','is_open','is_public','created_at','start_at','end_at')),'explicit fields only');
select is(jsonb_array_length(public.read_platform_organization_quests(current_setting('test.org')::uuid,'','open')->'items'),15,'open filter');
select is(jsonb_array_length(public.read_platform_organization_quests(current_setting('test.org')::uuid,'%')->'items'),0,'literal search');
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.other')::uuid)$t$,'42501','platform access denied','foreign scope denied');
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid,'changed','all',current_setting('test.page')::jsonb->'next_cursor')$t$,'22023','invalid quest cursor','filter-bound cursor');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501','platform access denied','MFA required');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
update public.platform_access_assignments set revoked_at=now() where user_id=auth.uid();
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501','platform access denied','revoked denied');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id,valid_from,expires_at) values(auth.uid(),'operations','organization',current_setting('test.org')::uuid,now()-interval '2 days',now()-interval '1 day');
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501','platform access denied','expired denied');
reset role;
select is((select count(*) from public.platform_role_permissions where permission_key='organization.quests.read' and role_key in ('sales','support','regional')),0::bigint,'other roles excluded');
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
set local role authenticated;
select is(jsonb_array_length(public.read_platform_organization_quests(current_setting('test.other')::uuid)->'items'),0,'platform owner empty organization');
select throws_ok('select * from public.platform_audit_events','42501',null,'audit private');
reset role;
select ok(exists(select 1 from public.platform_audit_events where actor_id=auth.uid() and action='organization.quests.read'),'reads audited');
set local role anon;
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501',null,'anon denied');
reset role;
set local role service_role;
select throws_ok($t$select public.read_platform_organization_quests(current_setting('test.org')::uuid)$t$,'42501',null,'server role denied');
reset role;
select * from finish();
rollback;