begin;
select no_plan();
insert into auth.users(id,email) select md5('support-case-'||n)::uuid,'support-case-'||n||'@example.test' from generate_series(1,3)n;
select platform_private.bootstrap_owner(md5('support-bootstrap')::uuid,md5('support-case-1')::uuid);
select set_config('test.support_org',(select id::text from public.organizations where personal_owner_id=md5('support-case-1')::uuid),true);
select set_config('test.support_other',(select id::text from public.organizations where personal_owner_id=md5('support-case-3')::uuid),true);
select set_config('request.jwt.claim.sub',md5('support-case-1')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.support_expiry',(now()+interval '1 hour')::text,true);
set local role authenticated;
select set_config('test.support_case',public.manage_platform_support_case(md5('support-open')::uuid,'open',current_setting('test.support_org')::uuid,p_reason_code=>'support_request')::text,true);
select is(public.manage_platform_support_case(md5('support-open')::uuid,'open',current_setting('test.support_org')::uuid,p_reason_code=>'support_request')::text,current_setting('test.support_case'),'открытие идемпотентно');
select throws_ok($$select public.manage_platform_support_case(md5('support-open')::uuid,'open',current_setting('test.support_other')::uuid,p_reason_code=>'support_request')$$,'22023','platform command conflict','подмена организации отклоняется');
select set_config('test.support_assignment',public.grant_platform_support_access(md5('support-grant')::uuid,current_setting('test.support_case')::uuid,md5('support-case-2')::uuid,current_setting('test.support_expiry')::timestamptz,p_reason_code=>'support_request')::text,true);
select is(public.grant_platform_support_access(md5('support-grant')::uuid,current_setting('test.support_case')::uuid,md5('support-case-2')::uuid,current_setting('test.support_expiry')::timestamptz,p_reason_code=>'support_request')::text,current_setting('test.support_assignment'),'выдача идемпотентна');
select throws_ok($$select public.grant_platform_support_access(md5('support-infinite')::uuid,current_setting('test.support_case')::uuid,md5('support-case-2')::uuid,'infinity',p_reason_code=>'support_request')$$,'22023','invalid support assignment','бессрочный допуск запрещён');
select throws_ok('select * from public.platform_support_cases','42501',null,'таблица обращений закрыта');
reset role;
select set_config('request.jwt.claim.sub',md5('support-case-2')::uuid::text,true);
set local role authenticated;
select lives_ok($$select public.get_platform_organization_summary(current_setting('test.support_org')::uuid)$$,'поддержка читает организацию обращения');
select throws_ok($$select public.get_platform_organization_summary(current_setting('test.support_other')::uuid)$$,'42501','platform access denied','чужая организация закрыта');
select throws_ok($$select public.manage_platform_support_case(md5('support-self')::uuid,'open',current_setting('test.support_other')::uuid,p_reason_code=>'support_request')$$,'42501','platform owner required','поддержка не расширяет свою область');
reset role;
select set_config('request.jwt.claim.sub',md5('support-case-1')::uuid::text,true);
set local role authenticated;
select lives_ok($$select public.manage_platform_support_case(md5('support-close')::uuid,'close',current_setting('test.support_case')::uuid,p_reason_code=>'request_resolved')$$,'владелец закрывает обращение');
select lives_ok($$select public.manage_platform_support_case(md5('support-close')::uuid,'close',current_setting('test.support_case')::uuid,p_reason_code=>'request_resolved')$$,'retry закрытия');
select throws_ok($$select public.grant_platform_support_access(md5('support-after-close')::uuid,current_setting('test.support_case')::uuid,md5('support-case-2')::uuid,current_setting('test.support_expiry')::timestamptz,p_reason_code=>'support_request')$$,'22023','support case unavailable','новый допуск закрытого обращения запрещён');
reset role;
select set_config('request.jwt.claim.sub',md5('support-case-2')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.get_platform_organization_summary(current_setting('test.support_org')::uuid)$$,'42501','platform access denied','закрытие сразу прекращает доступ без замены JWT');
reset role;
select is((select count(*)::int from public.platform_audit_events where action in ('support.open','support.close')),2,'открытие и закрытие в аудите без дублей');
select throws_ok($$update public.platform_access_assignments set organization_id=current_setting('test.support_other')::uuid where id=current_setting('test.support_assignment')::uuid$$,'23503',null,'FK не допускает другую организацию обращения');
select * from finish();
rollback;
