begin;
select no_plan();
insert into auth.users(id,email) values(md5('campaign-sales')::uuid,'campaign-sales@example.test'),(md5('campaign-owner')::uuid,'campaign-owner@example.test');
select set_config('request.jwt.claim.sub',md5('campaign-sales')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('campaign-owner')::uuid),true);
select set_config('test.deadline',(now()+interval '1 day')::text,true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id) values(auth.uid(),'sales','organization',current_setting('test.org')::uuid);
set local role authenticated;
select throws_ok($t$select public.save_platform_discount_campaign(md5('save1')::uuid,md5('campaign1')::uuid,null,0,'Акция','pro',10000,2,1,current_setting('test.deadline')::timestamptz)$t$,'42501','platform access denied','доступ к организации не даёт изменения общей акции');
select throws_ok($t$select public.read_platform_discount_campaigns(null)$t$,'42501','platform access denied','общий каталог черновиков закрыт локальной роли');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'sales','platform');
set local role authenticated;
select set_config('test.saved',public.save_platform_discount_campaign(md5('save1')::uuid,md5('campaign1')::uuid,null,0,'Акция','pro',10000,2,1,current_setting('test.deadline')::timestamptz)::text,true);
select is(current_setting('test.saved')::jsonb->>'organization_id',null,'акция не принадлежит организации');
select is(public.read_platform_discount_campaigns(null)->'items'->0->>'title','Акция','общий каталог содержит черновик');
select is(jsonb_array_length(public.read_platform_discount_campaigns(current_setting('test.org')::uuid)->'items'),0,'при выдаче кода черновики скрыты');
select throws_ok($t$select public.read_platform_discount_campaigns(null,null,md5('campaign1')::uuid,2)$t$,'40001','campaign revision conflict','предпросмотр защищён редакцией');
select is(public.save_platform_discount_campaign(md5('save1')::uuid,md5('campaign1')::uuid,null,0,'Акция','pro',10000,2,1,current_setting('test.deadline')::timestamptz),current_setting('test.saved')::jsonb,'идемпотентное сохранение');
select throws_ok($t$select public.save_platform_discount_campaign(md5('save1')::uuid,md5('campaign1')::uuid,null,0,'Другие условия','pro',5000,2,1,current_setting('test.deadline')::timestamptz)$t$,'22023','campaign command conflict','подмена команды запрещена');
select throws_ok($t$select public.approve_platform_discount_campaign(md5('approve1')::uuid,md5('campaign1')::uuid,1)$t$,'42501',null,'продажи не утверждают');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('campaign1')::uuid,1,md5('issue1')::uuid)$t$,'55000','campaign not approved','черновик не выпускает код');
select throws_ok('select * from public.platform_discount_campaigns','42501',null,'таблица закрыта');
select throws_ok('select * from public.platform_discount_campaign_commands','42501',null,'журнал закрыт');
reset role;
select set_config('request.jwt.claim.sub',md5('campaign-owner')::uuid::text,true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
set local role authenticated;
select set_config('test.approved',public.approve_platform_discount_campaign(md5('approve1')::uuid,md5('campaign1')::uuid,1)::text,true);
select is(public.approve_platform_discount_campaign(md5('approve1')::uuid,md5('campaign1')::uuid,1),current_setting('test.approved')::jsonb,'идемпотентное утверждение');
reset role;
select is((select count(*) from public.billing_discount_codes),0::bigint,'утверждение не выпускает код');
update public.platform_access_assignments set revoked_at=now() where user_id=md5('campaign-sales')::uuid and scope_kind='platform';
select set_config('request.jwt.claim.sub',md5('campaign-sales')::uuid::text,true);
set local role authenticated;
select is(public.read_platform_discount_campaigns(current_setting('test.org')::uuid)->'items'->0->>'state','approved','локальные продажи видят общую утверждённую акцию');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.other')::uuid,md5('campaign1')::uuid,1,md5('issue1')::uuid)$t$,'42501','platform access denied','выдача ограничена организацией');
select set_config('test.issued',public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('campaign1')::uuid,1,md5('issue1')::uuid)::text,true);
select is(length(current_setting('test.issued')::jsonb->>'code'),32,'код показан при выпуске');
select is(public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('campaign1')::uuid,1,md5('issue2')::uuid)->>'code',null,'другая команда не создаёт второй код организации');
reset role;
select set_config('request.jwt.claim.sub',md5('campaign-owner')::uuid::text,true);
set local role authenticated;
select set_config('test.issued2',public.issue_platform_campaign_discount(current_setting('test.other')::uuid,md5('campaign1')::uuid,1,md5('issue-other')::uuid)::text,true);
select isnt(current_setting('test.issued2')::jsonb->>'code',current_setting('test.issued')::jsonb->>'code','у организаций разные персональные коды общей акции');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('campaign1')::uuid,1,md5('issue-other')::uuid)$t$,'22023','discount command conflict','нельзя повторить команду для другой организации');
reset role;
select is((select count(*) from public.billing_discount_codes where campaign_id=md5('campaign1')::uuid),2::bigint,'одна акция обслуживает две организации');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.other')::uuid,md5('campaign1')::uuid,1,md5('issue-other')::uuid)$t$,'42501','platform access denied','даже повтор требует MFA');
reset role;
select * from finish();rollback;
