begin;
select no_plan();
insert into auth.users(id,email) select md5('search-user-'||n)::uuid,'search-user-'||n||'@example.test' from generate_series(1,4)n;
update public.organizations set name='SearchFixture '||case personal_owner_id when md5('search-user-1')::uuid then 'Alpha' when md5('search-user-2')::uuid then 'Beta' else '100%_Gamma' end
 where personal_owner_id in (md5('search-user-1')::uuid,md5('search-user-2')::uuid,md5('search-user-3')::uuid);
select set_config('test.search_org',(select id::text from public.organizations where personal_owner_id=md5('search-user-1')::uuid),true);
select set_config('test.search_other',(select id::text from public.organizations where personal_owner_id=md5('search-user-2')::uuid),true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('search-user-1')::uuid,'owner','platform');
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id) values(md5('search-user-2')::uuid,'sales','organization',current_setting('test.search_org')::uuid);
insert into public.platform_support_cases(id,organization_id,created_by) values(md5('search-case')::uuid,current_setting('test.search_other')::uuid,md5('search-user-1')::uuid);
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id,support_case_id,expires_at)
 values(md5('search-user-3')::uuid,'support','support_case',current_setting('test.search_other')::uuid,md5('search-case')::uuid,now()+interval '1 hour');
select set_config('request.jwt.claim.sub',md5('search-user-1')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
set local role authenticated;
select set_config('test.search_page1',public.search_platform_organizations('searchfixture',null,2)::text,true);
select is(jsonb_array_length(current_setting('test.search_page1')::jsonb->'items'),2,'первая страница ограничена');
select ok(current_setting('test.search_page1')::jsonb->>'next_cursor' is not null,'есть курсор продолжения');
select set_config('test.search_page2',public.search_platform_organizations('searchfixture',(current_setting('test.search_page1')::jsonb->>'next_cursor')::uuid,2)::text,true);
select is(jsonb_array_length(current_setting('test.search_page2')::jsonb->'items'),1,'последняя страница содержит остаток');
select ok(current_setting('test.search_page2')::jsonb->>'next_cursor' is null,'последняя страница без курсора');
select is((select count(distinct item->>'id')::int from jsonb_array_elements((current_setting('test.search_page1')::jsonb->'items')||(current_setting('test.search_page2')::jsonb->'items')) item),3,'страницы не теряют и не дублируют организации');
select is((select array_agg(k order by k) from jsonb_object_keys(current_setting('test.search_page1')::jsonb->'items'->0) k),array['created_at','id','name'],'ответ содержит только минимальную карточку');
select is(jsonb_array_length(public.search_platform_organizations('100%_')->'items'),1,'проценты и подчёркивание не wildcard');
select is(public.search_platform_organizations(current_setting('test.search_other'))->'items'->0->>'id',current_setting('test.search_other'),'поиск по точному UUID');
select is(public.search_platform_organizations('missing-search-fixture')->'items','[]'::jsonb,'пустая выдача — массив');
select throws_ok($$select public.search_platform_organizations('',null,101)$$,'22023','invalid platform search','большая страница запрещена');
select throws_ok($$select public.search_platform_organizations('',null,0)$$,'22023','invalid platform search','нулевая страница запрещена');
select throws_ok($$select public.search_platform_organizations('',null,null)$$,'22023','invalid platform search','null limit запрещён');
select throws_ok($$select public.search_platform_organizations(repeat('x',161))$$,'22023','invalid platform search','ограничена длина поиска');
reset role;
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($$select public.search_platform_organizations()$$,'42501','platform access denied','без MFA поиск запрещён');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('request.jwt.claim.sub',md5('search-user-4')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.search_platform_organizations()$$,'42501','platform access denied','владелец личной организации не администратор');
reset role;
select set_config('request.jwt.claim.sub',md5('search-user-2')::uuid::text,true);
set local role authenticated;
select is(jsonb_array_length(public.search_platform_organizations()->'items'),1,'продажи видят только назначенную организацию');
select is(public.search_platform_organizations(current_setting('test.search_other'))->'items','[]'::jsonb,'точный UUID не обходит область доступа');
reset role;
update public.platform_access_assignments set revoked_at=now() where user_id=md5('search-user-2')::uuid;
set local role authenticated;
select throws_ok($$select public.search_platform_organizations()$$,'42501','platform access denied','отзыв действует без нового JWT');
reset role;
select set_config('request.jwt.claim.sub',md5('search-user-3')::uuid::text,true);
set local role authenticated;
select is(public.search_platform_organizations()->'items'->0->>'id',current_setting('test.search_other'),'поддержка видит организацию обращения');
reset role;
update public.platform_support_cases set closed_at=now() where id=md5('search-case')::uuid;
set local role authenticated;
select throws_ok($$select public.search_platform_organizations()$$,'42501','platform access denied','закрытое обращение исключает доступ');
reset role;
select ok(exists(select 1 from public.platform_audit_events where action='organization.search'),'чтение списка журналируется');
select ok(not has_function_privilege('anon','public.search_platform_organizations(text,uuid,integer)','EXECUTE'),'анонимный вызов запрещён');
select * from finish();
rollback;
