begin;
select no_plan();
insert into auth.users(id,email) values(md5('discount-reader')::uuid,'discount-reader@example.test'),(md5('discount-other')::uuid,'discount-other@example.test');
select set_config('request.jwt.claim.sub',md5('discount-reader')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.other',(select id::text from public.organizations where personal_owner_id=md5('discount-other')::uuid),true);
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501','platform access denied','организационный владелец не администратор');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind,organization_id) values(auth.uid(),'sales','organization',current_setting('test.org')::uuid);
insert into public.billing_discount_codes(id,organization_id,plan_key,code_hash,discount_bps,eligible_periods,period_months,activate_before,issuer_id,issue_command_id,created_at)
select md5('discount-catalog-'||n)::uuid,current_setting('test.org')::uuid,'pro',encode(extensions.digest('discount-catalog-'||n,'sha256'),'hex'),10000,3,1,now()+interval '1 day',auth.uid(),md5('discount-command-'||n)::uuid,now()-n*interval '1 minute' from generate_series(1,30)n;
insert into public.billing_discount_reservations(order_id,discount_id,organization_id,request,quote,state)
select md5('catalog-reservation-'||n)::uuid,md5('discount-catalog-1')::uuid,current_setting('test.org')::uuid,'{}','{}',case n when 1 then 'consumed' when 2 then 'reserved' else 'released' end from generate_series(1,3)n;
set local role authenticated;
select set_config('test.page',public.read_platform_organization_discounts(current_setting('test.org')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.page')::jsonb->'items'),25,'страница ограничена');
select is(current_setting('test.page')::jsonb->'items'->0->>'id',md5('discount-catalog-1')::uuid::text,'сначала новые');
select is(current_setting('test.page')::jsonb->'items'->0->>'remaining_periods','1','отмена освобождает резерв');
select is(current_setting('test.page')::jsonb->'items'->0->>'consumed_periods','1','использованные периоды');
select is(current_setting('test.page')::jsonb->'items'->0->>'reserved_periods','1','резервы отдельно');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.page')::jsonb->'items') x where x ?| array['code_hash','code','issuer_id','issue_command_id']),'нет секретов и данных выпускающего');
select set_config('test.next',public.read_platform_organization_discounts(current_setting('test.org')::uuid,(current_setting('test.page')::jsonb->>'next_cursor')::uuid)::text,true);
select is(jsonb_array_length(current_setting('test.next')::jsonb->'items'),5,'остаток на второй странице');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('test.page')::jsonb->'items') a join jsonb_array_elements(current_setting('test.next')::jsonb->'items') b on a->>'id'=b->>'id'),'нет повторов страниц');
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.other')::uuid)$t$,'42501','platform access denied','чужая организация закрыта');
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid,gen_random_uuid())$t$,'22023','invalid discount cursor','неизвестный курсор отклонён');
select throws_ok('select * from public.billing_discount_codes','42501',null,'прямой доступ закрыт');
select throws_ok('select * from public.platform_discount_read_events','42501',null,'аудит закрыт');
reset role;
select is((select count(*) from public.platform_discount_read_events where actor_id=auth.uid()),2::bigint,'чтения аудированы');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501','platform access denied','нужна MFA');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
savepoint before_expiry;
update public.platform_access_assignments set valid_from=now()-interval '2 hours',expires_at=now()-interval '1 hour' where user_id=auth.uid();
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501','platform access denied','истёкшее назначение закрыто');
reset role;
rollback to before_expiry;
update public.platform_access_assignments set revoked_at=now() where user_id=auth.uid();
set local role authenticated;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501','platform access denied','отзыв применяется сразу');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
set local role authenticated;
select is(public.read_platform_organization_discounts(current_setting('test.other')::uuid)->'items','[]'::jsonb,'владелец видит пустую организацию');
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.other')::uuid,md5('discount-catalog-1')::uuid)$t$,'22023','invalid discount cursor','курсор связан с организацией');
reset role;
set local role anon;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501',null,'анонимный доступ запрещён');
reset role;
set local role service_role;
select throws_ok($t$select public.read_platform_organization_discounts(current_setting('test.org')::uuid)$t$,'42501',null,'service role не вызывает пользовательский RPC');
reset role;
select * from finish();
rollback;