begin;
select no_plan();
insert into auth.users(id,email) values(md5('window-owner')::uuid,'window-owner@example.test');
select set_config('request.jwt.claim.sub',md5('window-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
select public.save_platform_discount_campaign(md5('w-save')::uuid,md5('w')::uuid,null,0,'Период','pro',5000,2,1,now()+interval '10 days',now()+interval '1 day');
select public.approve_platform_discount_campaign(md5('w-approve')::uuid,md5('w')::uuid,1);
select is(public.save_platform_discount_campaign(md5('w-edit')::uuid,md5('w')::uuid,null,1,'Новые условия','pro',2500,2,1,now()+interval '10 days',now()+interval '1 day')->>'state','draft','изменение до выпуска возвращает черновик');
select is((select approved_at from public.platform_discount_campaigns where id=md5('w')::uuid),null::timestamptz,'утверждение сброшено');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('w')::uuid,2,md5('w-issue')::uuid)$t$,'55000','campaign not approved','нужно повторное утверждение');
select public.approve_platform_discount_campaign(md5('w-approve2')::uuid,md5('w')::uuid,2);
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('w')::uuid,2,md5('w-issue')::uuid,now()+interval '11 days')$t$,'22023','invalid activation window','нельзя выйти за окончание акции');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('w')::uuid,2,md5('w-issue')::uuid,now()+interval '1 day')$t$,'22023','invalid activation window','пустой период запрещён');
select set_config('test.issue',public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('w')::uuid,2,md5('w-issue')::uuid,now()+interval '5 days')::text,true);
select is((select activate_before from public.billing_discount_codes where campaign_id=md5('w')::uuid),now()+interval '5 days','сокращённый срок записан');
select is((select activate_from from public.billing_discount_codes where campaign_id=md5('w')::uuid),now()+interval '1 day','начало взято из акции');
select is(public.preview_organization_discount(current_setting('test.org')::uuid,current_setting('test.issue')::jsonb->>'code','pro',1)->>'ok','false','до начала код не активируется');
select throws_ok($t$select platform_private.reserve_discount_period(md5('w-order')::uuid,current_setting('test.org')::uuid,(current_setting('test.issue')::jsonb->>'discount_id')::uuid,'pro',1,10000)$t$,'22023','discount activation deadline expired','прямой резерв до начала запрещён');
select throws_ok($t$select public.save_platform_discount_campaign(md5('w-edit-issued')::uuid,md5('w')::uuid,null,2,'Нельзя','pro',5000,2,1,now()+interval '10 days',now())$t$,'55000','issued campaign immutable','первый выпуск блокирует правки');
select throws_ok($t$update public.platform_discount_campaigns set title='Нельзя' where id=md5('w')::uuid$t$,'55000','issued campaign immutable','триггер защищает условия после выпуска');
select throws_ok($t$select public.issue_platform_campaign_discount(current_setting('test.org')::uuid,md5('w')::uuid,2,md5('w-issue')::uuid,now()+interval '6 days')$t$,'22023','discount command conflict','повтор не меняет срок');
select is(public.read_platform_discount_campaigns(null,null,md5('w')::uuid,2)->'items'->0->>'has_issued_codes','true','интерфейс видит блокировку');
select * from finish();rollback;
