begin;
select no_plan();
insert into auth.users(id,email) select md5('platform-command-'||n)::uuid,'platform-command-'||n||'@example.test' from generate_series(0,2)n;
insert into public.platform_access_assignments(id,user_id,role_key,scope_kind)
values(md5('platform-first')::uuid,md5('platform-command-0')::uuid,'owner','platform');
select set_config('request.jwt.claim.sub',md5('platform-command-0')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select throws_ok($$select public.revoke_platform_assignment(md5('revoke-last')::uuid,md5('platform-first')::uuid,p_reason_code=>'role_change')$$,'23514','last platform owner protected','последнего владельца нельзя отозвать');
select set_config('test.platform_second',public.grant_platform_assignment(md5('grant-second')::uuid,md5('platform-command-1')::uuid,'owner',p_reason_code=>'role_change')::text,true);
select is(public.grant_platform_assignment(md5('grant-second')::uuid,md5('platform-command-1')::uuid,'owner',p_reason_code=>'role_change')::text,current_setting('test.platform_second'),'retry выдачи возвращает назначение');
select throws_ok($$select public.grant_platform_assignment(md5('grant-second')::uuid,md5('platform-command-2')::uuid,'owner',p_reason_code=>'role_change')$$,'22023','platform command conflict','повтор не подменяет адресата');
select throws_ok($$select public.grant_platform_assignment(md5('grant-support')::uuid,md5('platform-command-2')::uuid,'support',p_reason_code=>'role_change')$$,'22023','invalid platform assignment','поддержка не включается без обращения');
select throws_ok($$select public.grant_platform_assignment(md5('grant-region')::uuid,md5('platform-command-2')::uuid,'regional',p_reason_code=>'role_change')$$,'22023','invalid platform assignment','регион пока не включается');
select is(public.revoke_platform_assignment(md5('revoke-second')::uuid,current_setting('test.platform_second')::uuid,p_reason_code=>'role_change')::text,current_setting('test.platform_second'),'отзыв второго владельца');
select lives_ok($$select public.revoke_platform_assignment(md5('revoke-second')::uuid,current_setting('test.platform_second')::uuid,p_reason_code=>'role_change')$$,'retry отзыва');
select throws_ok($$select public.revoke_platform_assignment(md5('revoke-last')::uuid,md5('platform-first')::uuid,p_reason_code=>'role_change')$$,'23514','last platform owner protected','после отзыва снова защищён последний');
select throws_ok('select * from public.platform_assignment_commands','42501',null,'receipt закрыт от браузера');
reset role;
select is((select count(*)::int from public.platform_access_assignments where user_id=md5('platform-command-1')::uuid),1,'retry не дублирует назначение');
select is((select count(*)::int from public.platform_audit_events where assignment_id=current_setting('test.platform_second')::uuid),4,'изменения и команды выдачи/отзыва в аудите');
select set_config('request.jwt.claim.sub',md5('platform-command-1')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.grant_platform_assignment(md5('grant-evil')::uuid,md5('platform-command-2')::uuid,'owner',p_reason_code=>'role_change')$$,'42501','platform owner required','отозванный владелец не выдаёт права');
reset role;
select set_config('request.jwt.claim.sub',md5('platform-command-0')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
select throws_ok($$select public.grant_platform_assignment(md5('grant-no-mfa')::uuid,md5('platform-command-2')::uuid,'sales',p_reason_code=>'role_change')$$,'42501','platform owner required','MFA требуется для выдачи');
reset role;
select * from finish();
rollback;
