begin;
select no_plan();
insert into auth.users(id,email) values(md5('activity-owner')::uuid,'activity-owner@example.test');
select set_config('request.jwt.claim.sub',md5('activity-owner')::uuid::text,true);
insert into public.quests(id,creator_id,title,is_open,is_public) values(md5('activity-quest')::uuid,auth.uid(),'Activity fixture',true,true);
insert into public.tasks(id,quest_id,title,order_index) values(md5('activity-task')::uuid,md5('activity-quest')::uuid,'Activity task',1);
insert into public.quest_attempts(id,quest_id,user_id,total_tasks,started_at) values(md5('activity-attempt')::uuid,md5('activity-quest')::uuid,auth.uid(),1,now()-interval '3 days');
select ok((select last_activity_at>now()-interval '1 minute' and not is_estimated from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'start receipt uses server time even for past offline start');
update public.quest_attempt_activity set last_activity_at=now()-interval '2 days',is_estimated=true where quest_attempt_id=md5('activity-attempt')::uuid;
update public.quest_attempts set total_tasks=total_tasks where id=md5('activity-attempt')::uuid;
select ok((select last_activity_at<now()-interval '1 day' from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'no-op does not revive activity');
update public.quest_attempts set total_attempts=1 where id=md5('activity-attempt')::uuid;
select ok((select last_activity_at>now()-interval '1 minute' and not is_estimated from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'real change revives stalled attempt');
update public.quest_attempt_activity set last_activity_at=now()-interval '2 days' where quest_attempt_id=md5('activity-attempt')::uuid;
insert into public.task_attempts(quest_attempt_id,task_id,opened) values(md5('activity-attempt')::uuid,md5('activity-task')::uuid,true);
select ok((select last_activity_at>now()-interval '1 minute' from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'task change records activity');
update public.quest_attempt_activity set last_activity_at=now()-interval '2 days' where quest_attempt_id=md5('activity-attempt')::uuid;
insert into public.task_submission_events(client_event_id,quest_attempt_id,task_id,event_type,server_state) values(md5('activity-rejected')::uuid,md5('activity-attempt')::uuid,md5('activity-task')::uuid,'open','{"accepted":false}');
select ok((select last_activity_at<now()-interval '1 day' from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'rejected unchanged event does not revive activity');
insert into public.task_submission_events(client_event_id,quest_attempt_id,task_id,event_type,server_state) values(md5('activity-accepted')::uuid,md5('activity-attempt')::uuid,md5('activity-task')::uuid,'open','{"accepted":true}');
select ok((select last_activity_at>now()-interval '1 minute' from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'accepted event records activity');
update public.quest_attempt_activity set last_activity_at=now()-interval '2 days' where quest_attempt_id=md5('activity-attempt')::uuid;
insert into public.task_submission_events(client_event_id,quest_attempt_id,task_id,event_type,server_state) values(md5('activity-accepted')::uuid,md5('activity-attempt')::uuid,md5('activity-task')::uuid,'open','{"accepted":true}') on conflict(client_event_id) do nothing;
select ok((select last_activity_at<now()-interval '1 day' from public.quest_attempt_activity where quest_attempt_id=md5('activity-attempt')::uuid),'duplicate event does not refresh clock');
set local role authenticated;
select throws_ok('select * from public.quest_attempt_activity','42501',null,'private activity cannot be read directly');
select throws_ok('update public.quest_attempt_activity set last_activity_at=now()','42501',null,'client cannot forge activity');
reset role;
set local role anon;
select throws_ok('select * from public.quest_attempt_activity','42501',null,'anon denied');
reset role;
select ok((select relrowsecurity from pg_class where oid='public.quest_attempt_activity'::regclass),'activity RLS enabled');
select * from finish();
rollback;
