begin;
select no_plan();
insert into auth.users(id,email) values(md5('draft-sales')::uuid,'draft-sales@example.test');
select set_config('request.jwt.claim.sub',md5('draft-sales')::uuid::text,true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('test.source',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
set local role authenticated;
select throws_ok($t$select public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14)$t$,'42501','platform access denied','ordinary account denied');
select throws_ok('select * from public.platform_tariff_drafts','42501',null,'drafts private');
select throws_ok('select * from public.platform_tariff_draft_commands','42501',null,'audit private');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('draft-sales')::uuid,'sales','platform');
set local role authenticated;
select set_config('test.result',public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14)::text,true);
select is((current_setting('test.result')::jsonb->>'revision')::int,1,'created revision 1');
select is(public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14),current_setting('test.result')::jsonb,'retry identical');
select throws_ok($t$select public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Changed',5,3,14)$t$,'22023','command conflict','same command different payload denied');
select throws_ok($t$select public.save_platform_tariff_draft(md5('command2')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Changed',5,3,14)$t$,'40001','draft revision conflict','stale edit denied');
select is((public.save_platform_tariff_draft(md5('command2')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,1,'Changed',0,1,7)->>'revision')::int,2,'current revision updated with zero quest limit');
select throws_ok($t$select public.save_platform_tariff_draft(md5('command3')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,2,'Changed',5,0,14)$t$,'22023','invalid tariff draft','invalid limits denied');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select throws_ok($t$select public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14)$t$,'42501','platform access denied','MFA required even on retry');
reset role;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select is((select count(*)::int from public.platform_tariff_draft_commands where actor_id=md5('draft-sales')::uuid),2,'one audit receipt per successful command');
select ok(not exists(select 1 from public.billing_plan_versions where id=md5('draft1')::uuid),'draft absent from catalog');
update public.platform_access_assignments set role_key='operations' where user_id=md5('draft-sales')::uuid;
set local role authenticated;
select throws_ok($t$select public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14)$t$,'42501','platform access denied','operations cannot prepare drafts');
reset role;
update public.platform_access_assignments set role_key='sales',scope_kind='organization',organization_id=(select id from public.organizations where personal_owner_id=md5('draft-sales')::uuid) where user_id=md5('draft-sales')::uuid;
set local role authenticated;
select throws_ok($t$select public.save_platform_tariff_draft(md5('command1')::uuid,md5('draft1')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14)$t$,'42501','platform access denied','organization sales cannot edit platform');
reset role;
set local role authenticated;
select throws_ok('select public.read_platform_tariff_drafts(current_setting(''test.source'')::uuid)','42501','platform access denied','draft list requires global role');
reset role;
update public.platform_access_assignments set scope_kind='platform',organization_id=null where user_id=md5('draft-sales')::uuid;
set local role authenticated;
select ok(exists(select 1 from jsonb_array_elements(public.read_platform_tariff_drafts(current_setting('test.source')::uuid)->'items') x where x->>'id'=md5('draft1')::uuid::text),'reads saved drafts');
select is(jsonb_array_length(public.read_platform_tariff_drafts(current_setting('test.source')::uuid,'ffffffff-ffff-ffff-ffff-ffffffffffff')->'items'),0,'cursor excludes earlier drafts');
reset role;
set local role authenticated;
select is(public.preview_platform_tariff_draft(md5('draft1')::uuid,2)->'changes'->>'active_quests_limit','true','preview detects saved limit change');
select is(public.preview_platform_tariff_draft(md5('draft1')::uuid,2)->'draft'->>'active_quests_limit','0','preview preserves zero');
select throws_ok($t$select public.preview_platform_tariff_draft(md5('draft1')::uuid,1)$t$,'40001','draft revision conflict','stale preview denied');
select throws_ok($t$select public.preview_platform_tariff_draft(md5('unknown')::uuid,1)$t$,'40001','draft revision conflict','missing preview denied');
reset role;
update public.platform_access_assignments set revoked_at=now() where user_id=md5('draft-sales')::uuid;
set local role authenticated;
select throws_ok($t$select public.preview_platform_tariff_draft(md5('draft1')::uuid,2)$t$,'42501','platform access denied','preview denied after revocation');
reset role;
select * from finish();
rollback;
