begin;
select no_plan();
insert into auth.users(id,email) values(md5('publish-owner')::uuid,'publish-owner@example.test');
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(md5('publish-owner')::uuid,'owner','platform');
select set_config('request.jwt.claim.sub',md5('publish-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
select set_config('test.source',(select id::text from public.billing_plan_versions where plan_key='pro' and version=1),true);
select set_config('test.future',(now()+interval '2 days')::text,true);
set local role authenticated;
select public.save_platform_tariff_draft(md5('publish-save')::uuid,md5('publish-draft')::uuid,current_setting('test.source')::uuid,0,'Draft',5,3,14);
select throws_ok($t$select public.publish_tariff_draft(md5('bad-date')::uuid,md5('publish-draft')::uuid,1,now())$t$,'22023','publication must be in future','past rejected');
select throws_ok($t$select public.publish_tariff_draft(md5('bad-revision')::uuid,md5('publish-draft')::uuid,2,now()+interval '2 days')$t$,'40001','draft revision conflict','stale revision rejected');
select set_config('test.published',public.publish_tariff_draft(md5('publish')::uuid,md5('publish-draft')::uuid,1,current_setting('test.future')::timestamptz)::text,true);
select is(public.publish_tariff_draft(md5('publish')::uuid,md5('publish-draft')::uuid,1,current_setting('test.future')::timestamptz),current_setting('test.published')::jsonb,'publication retry stable');
select throws_ok($t$select public.save_platform_tariff_draft(md5('edit')::uuid,md5('publish-draft')::uuid,current_setting('test.source')::uuid,1,'Changed',6,3,14)$t$,'55000','published draft is read only','published draft cannot change');
select throws_ok($t$select public.fix_platform_tariff_version(md5('old')::uuid,md5('publish-draft')::uuid,1)$t$,'42501',null,'old fixation RPC closed');
select throws_ok($t$select public.publish_tariff_draft(md5('duplicate-draft')::uuid,md5('publish-draft')::uuid,1,now()+interval '3 days')$t$,'55000','draft already published','second publication of locked draft rejected');
select throws_ok($t$select public.publish_tariff_draft(md5('publish')::uuid,md5('publish-draft')::uuid,1,now()+interval '3 days')$t$,'22023','command conflict','retry cannot change date');
select public.save_platform_tariff_draft(md5('second-save')::uuid,md5('second-draft')::uuid,current_setting('test.source')::uuid,0,'Second',5,3,14);
select throws_ok($t$select public.publish_tariff_draft(md5('duplicate-date')::uuid,md5('second-draft')::uuid,1,current_setting('test.future')::timestamptz)$t$,'23505',null,'equal effective date rejected');
select throws_ok($t$select count(*) from public.platform_tariff_publication_commands$t$,'42501',null,'receipts not readable directly');
select throws_ok($t$select public.enable_fixed_tariff_version(md5('old-enable')::uuid,(current_setting('test.published')::jsonb->>'version_id')::uuid,current_setting('test.source')::uuid)$t$,'42501',null,'old immediate activation RPC closed');
select set_config('test.revoked',public.revoke_tariff_publication(md5('revoke')::uuid,(current_setting('test.published')::jsonb->>'version_id')::uuid)::text,true);
select is(public.revoke_tariff_publication(md5('revoke')::uuid,(current_setting('test.published')::jsonb->>'version_id')::uuid),current_setting('test.revoked')::jsonb,'revocation retry stable');
select lives_ok($t$select public.save_platform_tariff_draft(md5('edit')::uuid,md5('publish-draft')::uuid,current_setting('test.source')::uuid,1,'Changed',6,3,14)$t$,'revoked draft editable');
select isnt(public.publish_tariff_draft(md5('republish')::uuid,md5('publish-draft')::uuid,2,current_setting('test.future')::timestamptz)->>'version_id',current_setting('test.published')::jsonb->>'version_id','republish new snapshot and reuses freed date');
select throws_ok($t$select public.revoke_tariff_publication(md5('revoke-old')::uuid,current_setting('test.source')::uuid)$t$,'55000','publication cannot be revoked','effective version irrevocable');
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select throws_ok($t$select public.publish_tariff_draft(md5('publish')::uuid,md5('publish-draft')::uuid,1,current_setting('test.future')::timestamptz)$t$,'42501','platform owner required','retry still requires MFA');
reset role;
select is(platform_private.tariff_timeline_number((current_setting('test.published')::jsonb->>'version_id')::uuid),null::bigint,'revoked snapshot no number');
select is((select count(*) from public.billing_plan_versions where id=(current_setting('test.published')::jsonb->>'version_id')::uuid),1::bigint,'публикация материализована в каталоге');
select is((select display_name from public.billing_plan_versions where id=(current_setting('test.published')::jsonb->>'version_id')::uuid),'Draft','снимок каталога не изменён редактированием отозванного черновика');
select ok(not platform_private.tariff_allows_renewal((current_setting('test.published')::jsonb->>'version_id')::uuid,now(),false),'отозванный снимок нельзя купить');
select is((select count(*) from public.billing_plan_versions p join public.billing_tariff_timeline t on t.version_id=p.id where t.fixed_version_id is not null and t.revoked_at is null),1::bigint,'повторная публикация имеет отдельную версию каталога');
select ok((select not platform_private.tariff_allows_renewal(version_id,now(),false) from public.billing_tariff_timeline where fixed_version_id is not null and revoked_at is null),'будущая версия пока недоступна для покупки');
select ok((select platform_private.tariff_allows_renewal(version_id,effective_at,false) from public.billing_tariff_timeline where fixed_version_id is not null and revoked_at is null),'на границе опубликованная версия доступна для покупки');
select ok(not has_table_privilege('authenticated','public.billing_plan_versions','insert'),'клиент не вставляет версии напрямую');
select * from finish();
rollback;
