begin;
select no_plan();
insert into auth.users(id,email) select md5('reason-user-'||n)::uuid,'reason-user-'||n||'@example.test' from generate_series(1,2)n;
select platform_private.bootstrap_owner(md5('reason-bootstrap')::uuid,md5('reason-user-1')::uuid);
select set_config('test.reason_org',(select id::text from public.organizations where personal_owner_id=md5('reason-user-1')::uuid),true);
select set_config('request.jwt.claim.sub',md5('reason-user-1')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select throws_ok($$select public.grant_platform_assignment(md5('missing-reason')::uuid,md5('reason-user-2')::uuid,'sales')$$,'22023','invalid platform command reason','без основания команда отклонена');
select throws_ok($$select public.grant_platform_assignment(md5('wrong-reason')::uuid,md5('reason-user-2')::uuid,'sales',p_reason_code=>'request_resolved')$$,'22023','invalid platform command reason','основание не подходит действию');
select throws_ok($$select public.grant_platform_assignment(md5('text-reason')::uuid,md5('reason-user-2')::uuid,'sales',p_reason_code=>'произвольный текст')$$,'22023','invalid platform command reason','свободный текст запрещён');
select set_config('test.reason_assignment',public.grant_platform_assignment(md5('valid-reason')::uuid,md5('reason-user-2')::uuid,'sales',p_reason_code=>'staff_onboarding')::text,true);
select is(public.grant_platform_assignment(md5('valid-reason')::uuid,md5('reason-user-2')::uuid,'sales',p_reason_code=>'staff_onboarding')::text,current_setting('test.reason_assignment'),'retry с тем же основанием');
select throws_ok($$select public.grant_platform_assignment(md5('valid-reason')::uuid,md5('reason-user-2')::uuid,'sales',p_reason_code=>'role_change')$$,'22023','platform command conflict','основание выполненной команды не меняется');
select throws_ok($$select * from public.platform_command_reasons$$,'42501',null,'таблица оснований закрыта для API');
select throws_ok($$select platform_private.grant_platform_assignment(md5('bypass')::uuid,md5('reason-user-2')::uuid,'sales')$$,'42501',null,'внутренняя реализация не обходит основание');
reset role;
select is((select count(*)::int from public.platform_command_reasons),1,'retry не создаёт новое основание');
select is((select reason_code from public.platform_audit_events where command_id=md5('valid-reason')::uuid),'staff_onboarding','аудит команды содержит основание');
select ok((select relrowsecurity from pg_class where oid='public.platform_command_reasons'::regclass),'RLS включена');
select set_config('test.reason_owner',(select id::text from public.platform_access_assignments where role_key='owner'),true);
set local role authenticated;
select throws_ok($$select public.revoke_platform_assignment(md5('failed-reason')::uuid,current_setting('test.reason_owner')::uuid,p_reason_code=>'security_response')$$,'23514','last platform owner protected','основание не отменяет защиту последнего владельца');
reset role;
select is((select count(*)::int from public.platform_command_reasons where command_id=md5('failed-reason')::uuid),0,'ошибка откатывает основание вместе с командой');
-- Историческая команда до появления оснований: не приписываем ей причину при retry.
select platform_private.grant_platform_assignment(md5('historical-reason')::uuid,md5('reason-user-2')::uuid,'operations');
set local role authenticated;
select throws_ok($$select public.grant_platform_assignment(md5('historical-reason')::uuid,md5('reason-user-2')::uuid,'operations',p_reason_code=>'role_change')$$,'22023','historical platform command reason unavailable','истории не приписывается новое основание');
select set_config('test.reason_case',public.manage_platform_support_case(md5('reason-open')::uuid,'open',current_setting('test.reason_org')::uuid,p_reason_code=>'support_request')::text,true);
select lives_ok($$select public.grant_platform_support_access(md5('reason-support')::uuid,current_setting('test.reason_case')::uuid,md5('reason-user-2')::uuid,now()+interval '1 hour',p_reason_code=>'support_request')$$,'допуск поддержки с основанием');
select lives_ok($$select public.manage_platform_support_case(md5('reason-close')::uuid,'close',current_setting('test.reason_case')::uuid,p_reason_code=>'request_resolved')$$,'закрытие обращения с основанием');
reset role;
select is((select reason_code from public.platform_audit_events where command_id=md5('reason-close')::uuid),'request_resolved','основание закрытия в аудите');
select is((select reason_code from public.platform_audit_events where command_id=md5('reason-support')::uuid),'support_request','основание допуска в аудите');
select is((select count(*)::int from public.platform_command_reasons where command_id=md5('historical-reason')::uuid),0,'историческая запись не изменена');
select * from finish();
rollback;
