begin;
select plan(14);
insert into public.purchase_document_versions(id,kind,body) select 'draft-'||lpad(i::text,3,'0'),'agreement','Draft' from generate_series(1,51) i;
insert into public.purchase_document_versions(id,kind,body,status) values('old','agreement','Old text','published');
insert into public.purchase_document_versions(id,kind,body,status,effective_at) values('current','agreement','Text','published',null),('future','agreement','Text','published',now()+interval '1 day');
set local role anon;
select throws_ok($$select public.list_platform_purchase_documents('agreement')$$,'42501',null,'anonymous list denied');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000004','aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from now())))))::text,true);
set local role authenticated;
select throws_ok($$select public.list_platform_purchase_documents('agreement')$$,'42501',null,'non-owner denied');
reset role;
insert into public.platform_access_assignments values('00000000-0000-4000-8000-000000000003','owner','platform',null,now()-interval '1 day',null);
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000003','aal','aal1')::text,true);
set local role authenticated;
select throws_ok($$select public.list_platform_purchase_documents('agreement')$$,'42501',null,'AAL1 denied');
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000003','aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from now())))))::text,true);
select throws_ok($$select public.list_platform_purchase_documents('agreement','{}'::jsonb)$$,'22023',null,'invalid cursor denied');
select is(jsonb_array_length(public.list_platform_purchase_documents('agreement')->'items'),50,'bounded page');
select is(public.list_platform_purchase_documents('agreement')->'items'->0->>'display_status','draft','drafts first');
select is(public.list_platform_purchase_documents('agreement')->'items'->0->>'body',null::text,'list omits bodies');
select is(jsonb_array_length(public.list_platform_purchase_documents('agreement',public.list_platform_purchase_documents('agreement')->'next_cursor')->'items'),4,'keyset page no duplicates');
select is(public.list_platform_purchase_documents('agreement',public.list_platform_purchase_documents('agreement')->'next_cursor')->'items'->1->>'display_status','scheduled','future status');
select is(public.list_platform_purchase_documents('agreement',public.list_platform_purchase_documents('agreement')->'next_cursor')->'items'->2->>'display_status','current','current remains correct on later page');
select is(public.list_platform_purchase_documents('agreement',public.list_platform_purchase_documents('agreement')->'next_cursor')->'items'->3->>'display_status','superseded','older publication is archived');
select is(jsonb_array_length(public.list_platform_purchase_documents('payment_terms')->'items'),0,'kind isolated');
select throws_ok($$select public.list_platform_purchase_documents('invalid')$$,'22023',null,'kind validated');
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000003','aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from now()-interval '1 day')))))::text,true);
select throws_ok($$select public.list_platform_purchase_documents('agreement')$$,'42501',null,'stale MFA denied');
reset role;
select * from finish();
rollback;
