begin;
select plan(7);
insert into public.platform_access_assignments values('00000000-0000-4000-8000-000000000002','owner','platform',null,now()-interval '1 day',null);
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000002','aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from now())))))::text,true);
set local role authenticated;
select public.save_purchase_document_draft('audit-draft','agreement','synthetic');
select public.save_purchase_document_draft('audit-draft','agreement','synthetic');
select set_config('test.audit_hash',public.save_purchase_document_draft('audit-draft','agreement','synthetic')->>'sha256',true);
select set_config('test.audit_start',(now()+interval '1 day')::text,true);
select public.publish_purchase_document('audit-draft',current_setting('test.audit_hash'),current_setting('test.audit_start')::timestamptz);
select public.publish_purchase_document('audit-draft',current_setting('test.audit_hash'),current_setting('test.audit_start')::timestamptz);
select throws_ok($$select * from public.purchase_document_audit$$,'42501',null,'client cannot read audit directly');
reset role;
select is((select count(*)::int from public.purchase_document_audit where document_id='audit-draft'),2,'retries do not duplicate audit');
select is((select actor_id::text from public.purchase_document_audit where document_id='audit-draft' and action='published'),'00000000-0000-4000-8000-000000000002','actor recorded');
select is((select after_sha256 from public.purchase_document_audit where document_id='audit-draft' and action='published'),current_setting('test.audit_hash'),'published digest recorded');
select throws_ok($$delete from public.purchase_document_audit where document_id='audit-draft'$$,'55000','purchase document audit is immutable','audit cannot be deleted');
set local role anon;
select throws_ok($$select * from public.purchase_document_audit$$,'42501',null,'anonymous audit denied');
reset role;
select ok((select relrowsecurity from pg_class where oid='public.purchase_document_audit'::regclass),'audit RLS enabled');
select * from finish();
rollback;
