begin;
select plan(10);
insert into public.purchase_document_versions(id,kind,body) values('read-draft','agreement','Private draft');
insert into public.purchase_document_versions(id,kind,body,status) values('read-current','agreement','Public text','published');
insert into public.purchase_document_versions(id,kind,body,status,effective_at) values('read-future','agreement','Future text','published',now()+interval '1 day');
set local role anon;
select is(public.read_purchase_document('agreement','read-draft'),null::jsonb,'draft hidden');
select is(public.read_purchase_document('agreement','read-future'),null::jsonb,'future hidden');
select is(public.read_purchase_document('agreement','read-current')->>'body','Public text','published text available');
select is(public.read_purchase_document('payment_terms','read-current'),null::jsonb,'wrong type returns no document');
select is(jsonb_array_length(public.list_current_purchase_documents()),1,'only current document listed');
select throws_ok($$select public.read_platform_purchase_document('read-draft')$$,'42501',null,'anonymous admin read denied');
reset role;
insert into public.platform_access_assignments values('00000000-0000-4000-8000-000000000003','owner','platform',null,now()-interval '1 day',null);
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000003','aal','aal1')::text,true);
set local role authenticated;
select throws_ok($$select public.read_platform_purchase_document('read-draft')$$,'42501','platform owner required','AAL1 admin read denied');
select set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-000000000003','aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from now())))))::text,true);
select is(public.read_platform_purchase_document('read-draft')->>'body','Private draft','owner may review draft');
select is(jsonb_array_length(public.read_platform_purchase_document_audit('read-draft')),1,'owner sees audit');
select is(jsonb_array_length(public.read_platform_purchase_document_audit('read-draft',1)),0,'cursor excludes later events');
reset role;
select * from finish();
rollback;
