begin;
select plan(12);
insert into public.purchase_document_versions(id,kind,body) values('draft','agreement','Synthetic draft');
insert into public.purchase_document_versions(id,kind,body,status) values('current','agreement','Synthetic agreement','published');
insert into public.purchase_document_versions(id,kind,body,status,effective_at) values('future','payment_terms','Synthetic future','published',now()+interval '1 day');
select ok((select relrowsecurity from pg_class where oid='public.purchase_document_versions'::regclass),'RLS enabled');
select is((select sha256 from public.purchase_document_versions where id='current'),encode(sha256(convert_to('Synthetic agreement','UTF8')),'hex'),'digest computed by database');
select throws_ok($$update public.purchase_document_versions set body='changed' where id='current'$$,'55000','published purchase document is immutable','published text immutable');
select throws_ok($$delete from public.purchase_document_versions where id='current'$$,'55000','published purchase document is immutable','published deletion blocked');
select lives_ok($$update public.purchase_document_versions set body='revised draft' where id='draft'$$,'draft editable');
set local role anon;
select is((select count(*)::int from public.purchase_document_versions),1,'anonymous sees only effective publication');
select throws_ok($$insert into public.purchase_document_versions(id,kind,body) values('attack','agreement','x')$$,'42501',null,'anonymous cannot publish');
reset role;
set local role authenticated;
select is((select count(*)::int from public.purchase_document_versions),1,'signed-in user cannot read drafts or future versions');
select throws_ok($$update public.purchase_document_versions set body='x'$$,'42501',null,'signed-in user cannot edit');
reset role;
select throws_ok($$insert into public.purchase_document_versions(id,kind,body,status,effective_at) values('past','agreement','x','published',now()-interval '1 day')$$,'23514',null,'backdating blocked');
select throws_ok($$insert into public.purchase_document_versions(id,kind,body,status,effective_at) select 'duplicate',kind,body,status,effective_at from public.purchase_document_versions where id='future'$$,'23505',null,'ambiguous start blocked');
select throws_ok($$update public.purchase_document_versions set status='draft',published_at=null,effective_at=null where id='current'$$,'55000','published purchase document is immutable','cannot turn publication back into draft');
select * from finish();
rollback;
