begin;
select no_plan();
insert into auth.users(id,email) values(md5('create-owner')::uuid,'create-owner@example.test'),(md5('create-outsider')::uuid,'create-outsider@example.test');
select set_config('test.create_org',(select id::text from public.organizations where personal_owner_id=md5('create-owner')::uuid),true);
select set_config('request.jwt.claim.sub',md5('create-owner')::uuid::text,true);
set local role authenticated;
select set_config('test.created',public.create_organization_quest(current_setting('test.create_org')::uuid,md5('create-op')::uuid,'{"title":"Draft"}')::text,true);
select is(public.create_organization_quest(current_setting('test.create_org')::uuid,md5('create-op')::uuid,'{"title":"Draft"}'),current_setting('test.created')::uuid,'retry returns same quest');
select is((select is_open from public.quests where id=current_setting('test.created')::uuid),false,'created closed');
select throws_ok($$select public.create_organization_quest(current_setting('test.create_org')::uuid,md5('create-op')::uuid,'{"title":"Changed"}')$$,'22023','quest creation request conflict','changed request cannot reuse key');
select throws_ok($$select public.create_organization_quest(current_setting('test.create_org')::uuid,md5('bad-op')::uuid,'{"title":"Draft","is_open":true}')$$,'22023','unsupported quest creation field','cannot override protected fields');
select throws_ok('select * from public.quest_creation_requests','42501',null,'journal not readable');
select throws_ok($$insert into public.quest_creation_requests(actor_id,operation_id,organization_id,request,quest_id) values(auth.uid(),gen_random_uuid(),current_setting('test.create_org')::uuid,'{}',gen_random_uuid())$$,'42501',null,'journal not writable');
insert into public.tasks(quest_id,title,description,order_index,media,show_location_on_map)
values(current_setting('test.created')::uuid,'Task','Content',4,'[]',true);
select set_config('test.copy',public.create_organization_quest(current_setting('test.create_org')::uuid,md5('copy-op')::uuid,'{}',current_setting('test.created')::uuid)::text,true);
select is(public.create_organization_quest(current_setting('test.create_org')::uuid,md5('copy-op')::uuid,'{}',current_setting('test.created')::uuid),current_setting('test.copy')::uuid,'copy retry returns same quest');
select is((select count(*) from public.tasks where quest_id=current_setting('test.copy')::uuid),1::bigint,'copy task once');
select is((select description from public.tasks where quest_id=current_setting('test.copy')::uuid),'Content','copy task content');
select is((select show_location_on_map from public.tasks where quest_id=current_setting('test.copy')::uuid),true,'copy additional task settings');
select is((select is_open from public.quests where id=current_setting('test.copy')::uuid),false,'copy closed');
delete from public.quests where id=current_setting('test.copy')::uuid;
select throws_ok($$select public.create_organization_quest(current_setting('test.create_org')::uuid,md5('copy-op')::uuid,'{}',current_setting('test.created')::uuid)$$,'P0001','created quest no longer available','deleted copy not recreated');
reset role;
select set_config('request.jwt.claim.sub',md5('create-outsider')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.create_organization_quest(current_setting('test.create_org')::uuid,md5('create-op')::uuid,'{"title":"Draft"}')$$,'42501','quest creation access denied','foreign org denied');
select throws_ok($$select public.create_organization_quest((select id from public.organizations where personal_owner_id=auth.uid()),md5('foreign-copy')::uuid,'{}',current_setting('test.created')::uuid)$$,'42501','quest copy access denied','cannot copy foreign private content');
reset role;
select set_config('request.jwt.claim.sub',md5('create-owner')::uuid::text,true);
create function pg_temp.fail_copied_task() returns trigger language plpgsql as $$
begin if new.quest_id<>current_setting('test.created')::uuid then raise exception 'synthetic task failure'; end if; return new; end $$;
create trigger test_copy_failure before insert on public.tasks for each row execute function pg_temp.fail_copied_task();
select set_config('test.quest_count',(select count(*)::text from public.quests where organization_id=current_setting('test.create_org')::uuid),true);
set local role authenticated;
select throws_ok($$select public.create_organization_quest(current_setting('test.create_org')::uuid,md5('failed-copy')::uuid,'{}',current_setting('test.created')::uuid)$$,'P0001','synthetic task failure','task failure aborts copy');
select is((select count(*) from public.quests where organization_id=current_setting('test.create_org')::uuid),current_setting('test.quest_count')::bigint,'failed copy leaves no partial quest');
reset role;
select is((select count(*) from public.quest_creation_requests where operation_id=md5('failed-copy')::uuid),0::bigint,'failed copy leaves no receipt');
select ok((select relrowsecurity from pg_class where oid='public.quest_creation_requests'::regclass),'journal RLS enabled');
select * from finish();
rollback;
