begin;
select plan(8);
select set_config('test.actor','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
insert into public.platform_access_assignments values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','owner','platform',null,now()-interval '1 day',null);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select lives_ok($$select public.create_sandbox_fiscal_policy('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','123',now()+interval '1 day',1,'service','full_prepayment')$$,'owner creates future policy');
select lives_ok($$select public.create_sandbox_fiscal_policy('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','123',now()+interval '1 day',1,'service','full_prepayment')$$,'retry succeeds');
select throws_ok($$select public.create_sandbox_fiscal_policy('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','123',now()+interval '1 day',2,'service','full_prepayment')$$,'22023','fiscal policy command conflict','changed retry rejected');
select throws_ok($$select public.create_sandbox_fiscal_policy('ffffffff-ffff-4fff-8fff-ffffffffffff','123',now()-interval '1 day',1,'service','full_prepayment')$$,'22023','future fiscal policy required','no backdating');
reset role;
select is((select count(*) from public.billing_fiscal_policy_audit),1::bigint,'one audit');
select set_config('request.jwt.claims','{"aal":"aal2","amr":[{"method":"totp","timestamp":1}]}',true);
set local role authenticated;
select throws_ok($$select public.create_sandbox_fiscal_policy('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','123',now()+interval '1 day',1,'service','full_prepayment')$$,'42501','recent platform MFA required','expired MFA denied even for retry');
select set_config('test.actor','dddddddd-dddd-4ddd-8ddd-dddddddddddd',true);
select throws_ok($$select public.create_sandbox_fiscal_policy('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','123',now()+interval '1 day',1,'service','full_prepayment')$$,'42501','platform owner required','non-owner denied');
select throws_ok($$select * from public.billing_fiscal_policy_audit$$,'42501',null,'audit closed');
reset role;
select * from finish();
rollback;
