begin;
select no_plan();
select ok((select relrowsecurity from pg_class where oid='public.billing_sandbox_settlement_schedule'::regclass),'schedule has RLS');
select is((select count(*) from public.billing_sandbox_settlement_schedule),0::bigint,'migration provisions no targets');
select is((select active from cron.job where jobname='quest-stage-subscription-settlement'),false,'cron disabled by default');
set local role anon;
select throws_ok($t$select * from public.billing_sandbox_settlement_schedule$t$,'42501',null,'anonymous cannot read targets');
select throws_ok($t$select public.claim_scheduled_subscription_settlement('11111111-1111-4111-8111-111111111111')$t$,'42501',null,'anonymous cannot claim');
set local role authenticated;
select throws_ok($t$select * from public.billing_sandbox_settlement_schedule$t$,'42501',null,'browser cannot read targets');
select throws_ok($t$insert into public.billing_sandbox_settlement_schedule(order_id,amount_minor,period_end,expires_at) values('11111111-1111-4111-8111-111111111111',100,now(),now()+interval '1 hour')$t$,'42501',null,'browser cannot authorize target');
select throws_ok($t$select public.claim_scheduled_subscription_settlement('11111111-1111-4111-8111-111111111111')$t$,'42501',null,'browser cannot claim');
set local role service_role;
select throws_ok($t$select * from public.billing_sandbox_settlement_schedule$t$,'42501',null,'worker cannot enumerate targets');
select throws_ok($t$update public.billing_sandbox_settlement_schedule set enabled=true$t$,'42501',null,'worker cannot authorize itself');
select throws_ok($t$select public.claim_scheduled_subscription_settlement('11111111-1111-4111-8111-111111111111')$t$,'55000','scheduled settlement denied','unlisted target rejected');
reset role;
select is(platform_private.run_scheduled_subscription_settlements()->>'sent','0','empty schedule sends nothing');
select is(platform_private.run_scheduled_subscription_settlements()->>'sent','0','repeat empty schedule sends nothing');
select * from finish();
rollback;
