-- Runs inside the real paid checkout transaction, with the full Auth/RLS schema.
reset role;
select set_config('request.jwt.claim.sub',md5('discount-checkout-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('sub',auth.uid(),'aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select throws_ok($t$select public.create_sandbox_subscription_fiscal_policy(md5('model-policy')::uuid,'123',clock_timestamp()+interval '1 day')$t$,'42501','platform owner required','workspace owner cannot publish subscription model');
reset role;
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
select set_config('test.model.effective',(clock_timestamp()+interval '2 seconds')::text,true);
set local role authenticated;
select lives_ok($t$select public.create_sandbox_subscription_fiscal_policy(md5('model-policy')::uuid,'123',current_setting('test.model.effective')::timestamptz)$t$,'real owner/MFA publishes future model');
select lives_ok($t$select public.create_sandbox_subscription_fiscal_policy(md5('model-policy')::uuid,'123',current_setting('test.model.effective')::timestamptz)$t$,'real policy retry');
reset role;
select pg_sleep(2.1);
set local role authenticated;
select set_config('test.model.receipt',public.prepare_sandbox_receipt(current_setting('test.payment')::uuid,'model@example.test')::text,true);
select is(current_setting('test.model.receipt')::jsonb->>'amount_minor','6172','modeled receipt retains discounted checkout amount');
select is(current_setting('test.model.receipt')::jsonb->>'payment_mode','full_prepayment','model uses prepayment');
select is(public.prepare_sandbox_receipt(current_setting('test.payment')::uuid,'model@example.test')::text,current_setting('test.model.receipt'),'modeled retry returns same contract');
select throws_ok($t$select * from public.billing_subscription_fiscal_terms$t$,'42501',null,'terms inaccessible to browser');
reset role;
select is((select count(*) from public.billing_subscription_fiscal_terms where order_id=current_setting('test.payment')::uuid),1::bigint,'one terms row with real checkout');
select ok((select t.period_start=o.period_start and t.period_end=o.period_end and t.policy_id=md5('model-policy')::uuid from public.billing_subscription_fiscal_terms t join public.billing_sandbox_orders o on o.id=t.order_id where o.id=current_setting('test.payment')::uuid),'real order determines model and period');
insert into auth.users(id,email) values(md5('model-other-user')::uuid,'model-other@example.test');
select set_config('request.jwt.claim.sub',md5('model-other-user')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('sub',auth.uid(),'aal','aal2')::text,true);
set local role authenticated;
select throws_ok($t$select public.prepare_sandbox_receipt(current_setting('test.payment')::uuid,'model@example.test')$t$,'42501','receipt access denied','real other organization cannot recover modeled receipt');
reset role;
