-- Appended after the modeled paid checkout / resultPrefix, in a disposable DB.
reset role;
insert into public.billing_sandbox_application_scope select organization_id from public.billing_sandbox_orders where id=current_setting('test.payment')::uuid on conflict do nothing;
select set_config('test.worker.refund',platform_private.reserve_subscription_fiscal_operation(current_setting('test.payment')::uuid,md5('worker-refund')::uuid,0,'refund',1000)::text,true);
select platform_private.claim_subscription_fiscal_operation(md5('worker-refund')::uuid);
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','due')),0,'unresolved refund blocks due worker');
select platform_private.record_subscription_fiscal_result(md5('worker-refund')::uuid,md5('fiscal-payment')::uuid,'123',current_setting('test.worker.refund')::jsonb->>'sha256',1000,'succeeded',md5('worker-refund-provider')::uuid,'ra-'||md5('worker-refund-receipt')::uuid::text,'succeeded');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','due')),1,'confirmed partial refund discovers remaining settlement');
select is(jsonb_array_length(public.list_subscription_fiscal_order_work('123',current_setting('test.payment')::uuid,'due',1)),1,'scoped due finds target before limit');
select is(jsonb_array_length(public.list_subscription_fiscal_order_work('123',gen_random_uuid(),'due',1)),0,'scoped due excludes other orders');
select throws_ok($$select public.list_subscription_fiscal_order_work('123',null,'due')$$,'22023','invalid fiscal batch','scoped queue requires target');
select throws_ok($$select public.subscription_fiscal_order_worker_gateway('123',gen_random_uuid(),'claim_settlement',current_setting('test.payment')::uuid)$$,'42501','fiscal worker target denied','wrong target cannot reserve');
select is(jsonb_array_length(public.list_due_subscription_settlements('123')),0,'legacy due queue excludes owned ledger');
select is(jsonb_array_length(public.list_subscription_fiscal_work('456','due')),0,'worker queue isolates shop');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','reconcile')),0,'unlinked refund is not a worker reconciliation target');
select throws_ok($$select public.subscription_fiscal_worker_gateway('456','claim_settlement',current_setting('test.payment')::uuid)$$,'42501','fiscal worker scope denied','foreign shop cannot claim');
select throws_ok($$select public.subscription_fiscal_worker_gateway('123','read',null,md5('worker-refund')::uuid)$$,'55000','fiscal worker operation unavailable','worker cannot process unlinked refund');
set local role anon;
select throws_ok($$select public.list_subscription_fiscal_order_work('123',current_setting('test.payment')::uuid,'due')$$,'42501',null,'anonymous scoped queue denied');
select throws_ok($$select public.subscription_fiscal_order_worker_gateway('123',current_setting('test.payment')::uuid,'claim_settlement',current_setting('test.payment')::uuid)$$,'42501',null,'anonymous scoped gateway denied');
select throws_ok($$select public.list_subscription_fiscal_work('123','due')$$,'42501',null,'anonymous worker discovery denied');
set local role authenticated;
select throws_ok($$select public.subscription_fiscal_worker_gateway('123','claim_settlement',null)$$,'42501',null,'browser worker gateway denied');
reset role;
set local role service_role;
select set_config('test.worker.claim',public.subscription_fiscal_worker_gateway('123','claim_settlement',current_setting('test.payment')::uuid)::text,true);
select is(current_setting('test.worker.claim')::jsonb->>'action','send','worker claims one settlement send');
select is(current_setting('test.worker.claim')::jsonb->>'amountMinor','5172','worker settles only remaining amount');
select is(current_setting('test.worker.claim')::jsonb#>>'{body,items,0,quantity}','0.837978','worker retains exact remaining quantity');
select is(public.subscription_fiscal_worker_gateway('123','claim_settlement',current_setting('test.payment')::uuid)->>'action','reconcile','second worker claim only reconciles');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','due')),0,'claimed settlement removed from due queue');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','reconcile')),1,'unknown settlement enters reconciliation');
select throws_ok($$select public.subscription_fiscal_order_worker_gateway('123',gen_random_uuid(),'read',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid)$$,'42501','fiscal worker target denied','cross-order command rejected');
select is(public.subscription_fiscal_order_worker_gateway('123',current_setting('test.payment')::uuid,'read',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid)->>'action','reconcile','scoped gateway reuses reconcile-only claim');
select is(jsonb_array_length(public.list_subscription_fiscal_order_work('123',current_setting('test.payment')::uuid,'reconcile')),1,'scoped reconciliation includes target');
select is(jsonb_array_length(public.list_subscription_fiscal_order_work('123',gen_random_uuid(),'reconcile')),0,'scoped reconciliation excludes other target');
select is(public.subscription_fiscal_worker_gateway('123','before_send',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid,current_setting('test.worker.claim')::jsonb)->>'authorized','true','worker send authorization rechecks exact saved request');
select throws_ok($$select public.subscription_fiscal_worker_gateway('123','before_send',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid,current_setting('test.worker.claim')::jsonb||jsonb_build_object('sha256','wrong'))$$,'55000','fiscal worker send denied','worker send rejects changed hash');
select public.subscription_fiscal_worker_gateway('123','poll',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid,'{"resolved":false}');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','reconcile')),0,'failed poll backs off instead of looping');
reset role;
select is((select poll_failures from public.billing_subscription_fiscal_operation_status where command_id=(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid),1,'failure count persisted');
select ok((select next_check_at>clock_timestamp()+interval '50 seconds' from public.billing_subscription_fiscal_operation_status where command_id=(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid),'first backoff is at least one minute');
select set_config('test.worker.result',jsonb_build_object('commandId',current_setting('test.worker.claim')::jsonb->>'commandId','paymentId',md5('fiscal-payment')::uuid,'shopId','123','bodySha256',current_setting('test.worker.claim')::jsonb->>'sha256','amountMinor',5172,'state','succeeded','refundId',null,'receiptId','ra-'||md5('worker-settlement-receipt')::uuid::text,'receiptStatus','succeeded')::text,true);
set local role service_role;
select is(public.subscription_fiscal_worker_gateway('123','record',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid,current_setting('test.worker.result')::jsonb)->>'state','succeeded','worker persists confirmed settlement');
select throws_ok($$select public.subscription_fiscal_worker_gateway('123','before_send',null,(current_setting('test.worker.claim')::jsonb->>'commandId')::uuid,current_setting('test.worker.claim')::jsonb)$$,'55000','fiscal worker send denied','confirmed settlement cannot be sent again');
select is(jsonb_array_length(public.list_subscription_fiscal_work('123','reconcile')),0,'confirmed settlement leaves polling queue');
reset role;
select set_config('request.jwt.claim.sub',md5('discount-checkout-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
set local role authenticated;
select set_config('test.worker.history',public.read_platform_order_receipts(current_setting('test.org')::uuid,current_setting('test.payment')::uuid)::text,true);
select is((select count(*) from jsonb_array_elements(current_setting('test.worker.history')::jsonb->'items') i where i->>'kind'='settlement' and i->>'status'='succeeded' and i->>'amountMinor'='5172'),1::bigint,'payment receipt history includes exact settled remainder');
select ok(not(current_setting('test.worker.history')::jsonb::text like '%@%'),'receipt history omits customer contact');
select throws_ok($$select public.read_platform_order_receipts(gen_random_uuid(),current_setting('test.payment')::uuid)$$,'42501',null,'foreign organization receipt history denied');
reset role;
