begin;
select no_plan();
insert into auth.users(id,email) values(md5('subscription-refund-owner')::uuid,'subscription-refund@example.test');
select set_config('request.jwt.claim.sub',md5('subscription-refund-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
select set_config('test.order',public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,gen_random_uuid(),0,platform_private.current_tariff_version('pro',clock_timestamp()),1000,'123','https://stage.qvesta.ru',now()+interval '1 day',now()+interval '31 days')->>'id',true);
select public.begin_sandbox_payment_send(current_setting('test.order')::uuid);
select public.record_sandbox_payment_result(current_setting('test.order')::uuid,md5('subscription-refund-payment')::uuid,'succeeded',true,true,null);
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
select set_config('test.receipt',public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,md5('subscription-refund-command')::uuid)::text,true);
select is((current_setting('test.receipt')::jsonb->>'amount_minor'),'1000','future period fully refundable');
select is((current_setting('test.receipt')::jsonb->>'reserved'),'false','receipt does not reserve money');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,md5('subscription-refund-command')::uuid)::text,current_setting('test.receipt'),'retry preserves receipt and time');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,gen_random_uuid())->>'id',current_setting('test.receipt')::jsonb->>'id','new command cannot create second request for same order');
select throws_ok($$select public.request_platform_subscription_refund(gen_random_uuid(),current_setting('test.order')::uuid,md5('subscription-refund-command')::uuid)$$,'22023','subscription refund request conflict','cannot change organization on retry');
select is((select count(*)::integer from public.billing_sandbox_refunds where order_id=current_setting('test.order')::uuid),0,'no payment reserve created');
select ok((select relrowsecurity from pg_class where oid='public.subscription_refund_requests'::regclass),'RLS enabled');
set local role authenticated;
select throws_ok($$select * from public.subscription_refund_requests$$,'42501',null,'direct reads denied');
select throws_ok($$select public.request_platform_subscription_refund(null,null,null)$$,'42501',null,'RPC not enabled before integration');
set local role anon;
select throws_ok($$select * from public.subscription_refund_requests$$,'42501',null,'anonymous read denied');

set local role service_role;
select throws_ok($$select public.request_platform_subscription_refund(null,null,null)$$,'42501',null,'service RPC not prematurely enabled');
reset role;
-- A payment alone is not a license to change an arbitrary subscription.
select throws_ok($$select public.reserve_platform_subscription_refund((current_setting('test.receipt')::jsonb->>'id')::uuid)$$,'55000','subscription refund period not issued','unissued period cannot be reserved by termination flow');
select is((select count(*)::integer from public.subscription_refund_period_bindings),0,'failed binding leaves no row');
-- Trusted fixture: immutable confirmation for exactly the paid order.
update public.organization_subscriptions s set status='active',plan_version_id=o.plan_version_id,period_start=o.period_start,period_end=o.period_end from public.billing_sandbox_orders o where o.id=current_setting('test.order')::uuid and s.organization_id=o.organization_id;
insert into public.billing_period_confirmations(confirmation_id,organization_id,request,before_state,result)
select id,organization_id,jsonb_build_object('plan',plan_version_id,'start',period_start,'end',period_end),'{}',jsonb_build_object('revision',(select revision from public.organization_subscriptions where organization_id=public.billing_sandbox_orders.organization_id))
from public.billing_sandbox_orders where id=current_setting('test.order')::uuid;
savepoint before_reserve;
select set_config('test.reserve',public.reserve_platform_subscription_refund((current_setting('test.receipt')::jsonb->>'id')::uuid)::text,true);
select is(public.reserve_platform_subscription_refund((current_setting('test.receipt')::jsonb->>'id')::uuid)::text,current_setting('test.reserve'),'retry uses one reserve');
select is((select amount_minor from public.billing_sandbox_refunds where id=current_setting('test.reserve')::uuid),1000::bigint,'shared journal receives exact quote');
select throws_ok($$select public.preview_platform_sandbox_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,1)$$,'22023','invalid refund amount','manual refund cannot spend reserved amount');
select throws_ok($$update public.billing_sandbox_refunds set state='sending' where id=current_setting('test.reserve')::uuid$$,'55000','subscription refund execution not enabled','new reserve cannot be sent before integration');
set local role authenticated;
select throws_ok($$select public.reserve_platform_subscription_refund(null)$$,'42501',null,'reserve RPC remains closed');
select throws_ok($$select * from public.subscription_refund_reservations$$,'42501',null,'reservation links not exposed');
reset role;
select is((select kind from public.subscription_refund_period_bindings where request_id=(current_setting('test.receipt')::jsonb->>'id')::uuid),'confirmed','binding is to issued confirmation');
select is((select period_order_id::text from public.subscription_refund_period_bindings where request_id=(current_setting('test.receipt')::jsonb->>'id')::uuid),current_setting('test.order'),'binding retains exact order');
set local role authenticated;
select throws_ok($$select * from public.subscription_refund_period_bindings$$,'42501',null,'period binding is private');
reset role;
select throws_ok($$select platform_private.apply_current_subscription_refund((current_setting('test.receipt')::jsonb->>'id')::uuid)$$,'55000','subscription refund not confirmed','pending reserve cannot terminate access');
rollback to savepoint before_reserve;
-- Trusted provider-success fixture; no triggers are disabled.
select platform_private.bind_subscription_refund_period((current_setting('test.receipt')::jsonb->>'id')::uuid);
insert into public.billing_sandbox_refunds(id,order_id,actor_id,command_id,amount_minor,payment_id,state,provider_refund_id,first_sent_at)
values(md5('confirmed-subscription-refund')::uuid,current_setting('test.order')::uuid,auth.uid(),gen_random_uuid(),1000,md5('subscription-refund-payment')::uuid,'pending',md5('refund-provider')::uuid,clock_timestamp());
insert into public.subscription_refund_reservations values((current_setting('test.receipt')::jsonb->>'id')::uuid,md5('confirmed-subscription-refund')::uuid,clock_timestamp());
select set_config('test.refund',md5('confirmed-subscription-refund')::uuid::text,true);
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'pending')->>'access_state','not_applied','pending does not terminate access');
select throws_ok($$select platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,gen_random_uuid(),'succeeded')$$,'22023','invalid verified refund','foreign provider result rejected');
update public.organization_subscriptions set period_end=period_end+interval '1 day' where organization_id=current_setting('test.org')::uuid;
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'succeeded')->>'access_state','review_required','access mismatch requires review');
select is((select state from public.billing_sandbox_refunds where id=current_setting('test.refund')::uuid),'succeeded','monetary success persists despite access failure');
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.org')::uuid),'active','unrelated access preserved');
select is((select count(*)::integer from public.subscription_refund_applications),0,'failed application not acknowledged');
select is(jsonb_array_length(public.list_sandbox_subscription_refund_applications('123')),1,'unapplied success enters retry queue');
select is(jsonb_array_length(public.list_sandbox_subscription_refund_applications('other')),0,'queue scoped to shop');
select throws_ok($$select public.retry_sandbox_subscription_refund_application('other',current_setting('test.refund')::uuid)$$,'42501','subscription refund scope denied','foreign shop retry denied');
set local role authenticated;
select throws_ok($$select public.list_sandbox_subscription_refund_applications('123')$$,'42501',null,'organizer cannot enumerate queue');
reset role;
set local role service_role;
select is(public.retry_sandbox_subscription_refund_application('123',current_setting('test.refund')::uuid)->>'access_state','review_required','worker can retry reviewed access');
reset role;
update public.organization_subscriptions s set period_end=o.period_end from public.billing_sandbox_orders o where o.id=current_setting('test.order')::uuid and s.organization_id=o.organization_id;
select set_config('test.result',public.retry_sandbox_subscription_refund_application('123',current_setting('test.refund')::uuid)::text,true);
select is(jsonb_array_length(public.list_sandbox_subscription_refund_applications('123')),0,'applied success leaves retry queue');
select is(current_setting('test.result')::jsonb->>'access_state','applied','retry applies corrected access');
select is((select status from public.organization_subscriptions where organization_id=current_setting('test.org')::uuid),'free','retry terminates exact period');
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'succeeded')->'application',current_setting('test.result')::jsonb->'application','success replay is stable');
select is((select count(*)::integer from public.billing_sandbox_refunds where order_id=current_setting('test.order')::uuid),1,'retry uses same refund');
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'pending')->>'access_state','applied','late pending does not regress success');
select throws_ok($$update public.billing_sandbox_refunds set amount_minor=amount_minor+1 where id=current_setting('test.refund')::uuid$$,'55000','subscription refund execution not enabled','reconciliation cannot change amount');
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'canceled')#>>'{refund,state}','review','contradictory terminal result goes to review');
select is(platform_private.reconcile_subscription_refund(current_setting('test.refund')::uuid,md5('refund-provider')::uuid,'succeeded')->>'access_state','applied_review_required','review preserves knowledge of applied access');
set local role service_role;
select throws_ok($$select platform_private.reconcile_subscription_refund(null,null,null)$$,'42501',null,'new reconciliation remains closed until gateway integration');
reset role;
select * from finish();
rollback;