begin;
select no_plan();
insert into auth.users(id,email) values(md5('received-at-owner')::uuid,'receipt-owner@example.test'),(md5('received-at-other')::uuid,'receipt-other@example.test');
select set_config('request.jwt.claim.sub',md5('received-at-owner')::uuid::text,true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from clock_timestamp())))))::text,true);
insert into public.platform_access_assignments(user_id,role_key,scope_kind) values(auth.uid(),'owner','platform');
select set_config('test.org',(select id::text from public.organizations where personal_owner_id=auth.uid()),true);
create function pg_temp.paid_order(tag text) returns uuid language plpgsql as $$
declare paid_id uuid;
begin
 paid_id:=(public.reserve_sandbox_payment_order(current_setting('test.org')::uuid,md5(tag)::uuid,0,platform_private.current_tariff_version('pro',clock_timestamp()),1000,'123','https://stage.qvesta.ru','2026-09-01T00:00:00Z','2026-10-01T00:00:00Z')->>'id')::uuid;
 perform public.begin_sandbox_payment_send(paid_id);
 perform public.record_sandbox_payment_result(paid_id,md5(tag||'-payment')::uuid,'succeeded',true,true,null);
 -- Trusted paid fixture closes only its synthetic order; no fulfillment/provider call.
 update public.billing_sandbox_orders set state='finished' where billing_sandbox_orders.id=paid_id;
 return paid_id;
end; $$;
insert into public.billing_sandbox_application_scope values(current_setting('test.org')::uuid);
select set_config('test.order',pg_temp.paid_order('email-delay')::text,true);
select set_config('test.receipt',public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,md5('email-delay-command')::uuid,'email','2026-09-16T03:00:00+03:00')::text,true);
select is((current_setting('test.receipt')::jsonb->>'amount_minor')::bigint,500::bigint,'delayed registration calculates at email receipt, not expired registration period');
select is((current_setting('test.receipt')::jsonb->>'received_at')::timestamptz,'2026-09-16T00:00:00Z'::timestamptz,'explicit timezone denotes exact receipt instant');
select ok((current_setting('test.receipt')::jsonb->>'requested_at')::timestamptz>(current_setting('test.receipt')::jsonb->>'received_at')::timestamptz,'server registration remains separate and later');
select is(current_setting('test.receipt')::jsonb#>>'{snapshot,registered_by}',auth.uid()::text,'immutable audit retains registering actor');
select is(current_setting('test.receipt')::jsonb#>>'{snapshot,receipt_source}','email','immutable audit retains source');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,md5('email-delay-command')::uuid,'email','2026-09-16T00:00:00Z')::text,current_setting('test.receipt'),'retry same instant in another timezone returns original result');
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,md5('email-delay-command')::uuid,'email','2026-09-17T00:00:00Z')$$,'PT409','subscription refund receipt conflict','changed time at same command conflicts');
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.order')::uuid,gen_random_uuid(),'inapp',null)$$,'PT409','subscription refund receipt conflict','new command cannot replace existing source/time');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,pg_temp.paid_order('at-start'),gen_random_uuid(),'email','2026-09-01T00:00:00Z')->>'amount_minor','1000','receipt at start fully refundable');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,pg_temp.paid_order('at-end'),gen_random_uuid(),'email','2026-10-01T00:00:00Z')->>'amount_minor','0','receipt at end zero');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,pg_temp.paid_order('early'),gen_random_uuid(),'email','2026-08-01T00:00:00Z')->>'received_at','2026-08-01T00:00:00+00:00','early date preserved, no silent clipping or minimum-date policy');
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,pg_temp.paid_order('last-ms'),gen_random_uuid(),'email','2026-09-30T23:59:59.999Z')->>'amount_minor','0','last-millisecond rounding remains unchanged');
select set_config('test.inapp',public.request_platform_subscription_refund(current_setting('test.org')::uuid,pg_temp.paid_order('inapp'),gen_random_uuid())::text,true);
select is(current_setting('test.inapp')::jsonb->>'received_at',current_setting('test.inapp')::jsonb->>'requested_at','compatible in-app path uses server receipt time');
select is(current_setting('test.inapp')::jsonb->>'receipt_source','inapp','server receipt source is explicit');
select set_config('test.invalid',pg_temp.paid_order('invalid-time')::text,true);
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),'email',clock_timestamp()+interval '1 day')$$,'PT400','invalid refund receipt time','future receipt denied');
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),'email','infinity')$$,'PT400','invalid refund receipt time','nonfinite receipt denied');
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),'email',null)$$,'PT400','invalid refund receipt time','missing email receipt denied');
select throws_ok($$select public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),'inapp','2026-09-01')$$,'PT400','invalid refund receipt time','in-app cannot be backdated');
select set_config('test.balance',pg_temp.paid_order('previous-refund')::text,true);
insert into public.billing_sandbox_refunds(order_id,actor_id,command_id,amount_minor,payment_id,state,provider_refund_id,first_sent_at)
 values(current_setting('test.balance')::uuid,auth.uid(),gen_random_uuid(),700,md5('previous-refund-payment')::uuid,'succeeded',gen_random_uuid(),clock_timestamp());
select is(public.request_platform_subscription_refund(current_setting('test.org')::uuid,current_setting('test.balance')::uuid,gen_random_uuid(),'email','2026-09-16T00:00:00Z')->>'amount_minor','300','prior successful refunds retain remaining balance cap');
select is((select count(*) from public.subscription_refund_reservations),0::bigint,'registration creates no reservations');
select is((select count(*) from public.subscription_refund_applications),0::bigint,'registration changes no subscription access');
select is((select count(*) from public.billing_sandbox_refunds where state<>'succeeded'),0::bigint,'registration sends no money');
select throws_ok($$update public.subscription_refund_requests set received_at=clock_timestamp()$$,'55000',null,'receipt audit cannot be edited');
set local role authenticated;
select throws_ok($$select * from public.subscription_refund_requests$$,'42501',null,'RLS/private table not exposed');
select throws_ok($$select public.request_platform_subscription_refund(null,null,null,'email',now())$$,'42501',null,'ordinary client cannot backdate via core RPC');
select throws_ok($$select public.prepare_subscription_refund_from_gateway(null,null,null,'request',null,null,null,null,'email',now())$$,'42501',null,'ordinary client cannot invoke service gateway');
set local role anon;
select throws_ok($$select * from public.subscription_refund_requests$$,'42501',null,'anonymous receipt audit read denied');
reset role;
select throws_ok($$select public.prepare_subscription_refund_from_gateway(md5('received-at-owner')::uuid,floor(extract(epoch from now()))::bigint-600,floor(extract(epoch from now()))::bigint+300,'request',current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),null,'email','2026-09-16')$$,'42501','invalid refund preparation context','stale MFA denied');
select throws_ok($$select public.prepare_subscription_refund_from_gateway(md5('received-at-other')::uuid,floor(extract(epoch from clock_timestamp()))::bigint,floor(extract(epoch from clock_timestamp()))::bigint+300,'request',current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),null,'email','2026-09-16')$$,'42501','platform owner required','non-owner cannot record email time');
select set_config('test.gateway',public.prepare_subscription_refund_from_gateway(auth.uid(),floor(extract(epoch from clock_timestamp()))::bigint,floor(extract(epoch from clock_timestamp()))::bigint+300,'request',current_setting('test.org')::uuid,current_setting('test.invalid')::uuid,gen_random_uuid(),null,'email','2026-09-16')::text,true);
select is(current_setting('test.gateway')::jsonb->>'registered_at',current_setting('test.gateway')::jsonb->>'requested_at','gateway separates compatibility and registration labels');
select is(current_setting('test.gateway')::jsonb->>'receipt_source','email','fresh owner gateway exposes confirmed source only');
select ok(not(current_setting('test.gateway')::jsonb?'actor_id'),'gateway does not expose internal audit author');
select * from finish();
rollback;
