begin;
select no_plan();
insert into auth.users(id,email) select md5('team-invite-'||n)::uuid,'team-invite-'||n||'@example.test' from generate_series(0,3)n;
select set_config('test.invite_org',(select id::text from public.organizations where personal_owner_id=md5('team-invite-0')::uuid),true);
update public.organization_subscriptions set status='active',plan_version_id=(select id from public.billing_plan_versions where plan_key='pro' and version=1),period_start=now()-interval '1 day',period_end=now()+interval '1 day',team_member_quota_enabled=true where organization_id=current_setting('test.invite_org')::uuid;
insert into public.organization_memberships(organization_id,user_id,status) select current_setting('test.invite_org')::uuid,md5('team-invite-'||n)::uuid,'active' from generate_series(1,2)n;
select set_config('request.jwt.claim.sub',md5('team-invite-0')::uuid::text,true);
set local role authenticated;
-- Токен существует только внутри откатываемой тестовой транзакции.
select set_config('test.invite_token',invitation_token,true) is not null from public.create_organization_invitation(current_setting('test.invite_org')::uuid,'team-invite-3@example.test',array['host']);
reset role;
select is((select count(*) from public.organization_memberships where organization_id=current_setting('test.invite_org')::uuid and status='active'),3::bigint,'приглашение не резервирует дополнительное место');
select set_config('request.jwt.claim.sub',md5('team-invite-3')::uuid::text,true);
set local role authenticated;
select throws_ok($$select * from public.accept_organization_invitation(current_setting('test.invite_token'))$$,'P0001','team member quota exceeded','RPC принятия не обходит заполненную квоту');
reset role;
select is((select status from public.organization_invitations where organization_id=current_setting('test.invite_org')::uuid),'pending','отказ сохраняет приглашение pending');
select is((select count(*) from public.organization_memberships where organization_id=current_setting('test.invite_org')::uuid and user_id=md5('team-invite-3')::uuid),0::bigint,'отказ не создаёт частичного членства');
select is((select count(*) from public.organization_audit_events where organization_id=current_setting('test.invite_org')::uuid and action='invitation.accepted'),0::bigint,'отказ не пишет успешное принятие в аудит');
update public.organization_memberships set status='revoked' where organization_id=current_setting('test.invite_org')::uuid and user_id=md5('team-invite-2')::uuid;
set local role authenticated;
select lives_ok($$select * from public.accept_organization_invitation(current_setting('test.invite_token'))$$,'retry после освобождения места успешен');
select lives_ok($$select * from public.accept_organization_invitation(current_setting('test.invite_token'))$$,'повтор принятия идемпотентен');
reset role;
select is((select count(*) from public.organization_memberships where organization_id=current_setting('test.invite_org')::uuid and status='active'),3::bigint,'после retry и повтора ровно три активных аккаунта');
select is((select status from public.organization_invitations where organization_id=current_setting('test.invite_org')::uuid),'accepted','приглашение принято');
select is((select count(*) from public.organization_audit_events where organization_id=current_setting('test.invite_org')::uuid and action='invitation.accepted'),1::bigint,'единственное событие успешного принятия');
select is((select count(*) from public.membership_roles mr join public.organization_memberships m on m.id=mr.membership_id join public.roles r on r.id=mr.role_id where m.organization_id=current_setting('test.invite_org')::uuid and m.user_id=md5('team-invite-3')::uuid and r.key='host'),1::bigint,'роль выдана один раз');
select * from finish();
rollback;
