begin;
select no_plan();
insert into auth.users(id,email) select md5('team-quota-'||n)::uuid,'team-quota-'||n||'@example.test' from generate_series(0,3)n;
select set_config('test.team_org',(select id::text from public.organizations where personal_owner_id=md5('team-quota-0')::uuid),true);
select is((select team_member_quota_enabled from public.organization_subscriptions where organization_id=current_setting('test.team_org')::uuid),false,'квота по умолчанию выключена');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1),team_member_quota_enabled=true where organization_id=current_setting('test.team_org')::uuid;
select throws_ok($$insert into public.organization_memberships(organization_id,user_id) values(current_setting('test.team_org')::uuid,md5('team-quota-1')::uuid)$$,'P0001','team member quota exceeded','владелец уже занимает слот Free');
insert into public.organization_memberships(organization_id,user_id,status) values(current_setting('test.team_org')::uuid,md5('team-quota-1')::uuid,'invited');
select throws_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-1')::uuid$$,'P0001','team member quota exceeded','активация приглашённого проверяет лимит');
select lives_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-0')::uuid$$,'повтор активации владельца безопасен');
update public.organization_subscriptions set status='active',plan_version_id=(select id from public.billing_plan_versions where plan_key='pro' and version=1),period_start=now()-interval '1 day',period_end=now()+interval '1 day' where organization_id=current_setting('test.team_org')::uuid;
update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid;
select lives_ok($$insert into public.organization_memberships(organization_id,user_id) values(current_setting('test.team_org')::uuid,md5('team-quota-2')::uuid)$$,'последний слот Pro доступен');
select throws_ok($$insert into public.organization_memberships(organization_id,user_id) values(current_setting('test.team_org')::uuid,md5('team-quota-3')::uuid)$$,'P0001','team member quota exceeded','четвёртый аккаунт запрещён');
update public.organization_memberships set status='suspended' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-2')::uuid;
select lives_ok($$insert into public.organization_memberships(organization_id,user_id) values(current_setting('test.team_org')::uuid,md5('team-quota-3')::uuid)$$,'приостановка освобождает слот');
select throws_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-2')::uuid$$,'P0001','team member quota exceeded','восстановление проверяет лимит');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1),period_start=null,period_end=null where organization_id=current_setting('test.team_org')::uuid;
select is((select count(*) from public.organization_memberships where organization_id=current_setting('test.team_org')::uuid and status='active'),3::bigint,'downgrade не отзывает существующие членства');
select lives_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-1')::uuid$$,'повтор сверх лимита не блокирует существующего сотрудника');
select set_config('request.jwt.claim.sub',md5('team-quota-0')::uuid::text,true);
set local role authenticated;
select throws_ok($$update public.organization_subscriptions set team_member_quota_enabled=false$$,'42501',null,'клиент не отключает квоту');
reset role;
update public.organization_subscriptions set status='transition',plan_version_id=null where organization_id=current_setting('test.team_org')::uuid;
select lives_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid$$,'transition исключён из ограничения');
update public.organization_memberships set status='suspended' where organization_id=current_setting('test.team_org')::uuid and user_id<>md5('team-quota-0')::uuid;
update public.organization_subscriptions set status='active',plan_version_id=(select id from public.billing_plan_versions where plan_key='pro' and version=1),period_start=now()-interval '1 day',period_end=now()+interval '1 day' where organization_id=current_setting('test.team_org')::uuid;
select throws_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid$$,'P0001','team member quota exceeded','multi-row активация отклоняется атомарно');
select is((select count(*) from public.organization_memberships where organization_id=current_setting('test.team_org')::uuid and status='active'),1::bigint,'после отказа multi-row активен только владелец');
select lives_ok($$insert into public.organization_memberships(organization_id,user_id,status) values(current_setting('test.team_org')::uuid,md5('team-quota-1')::uuid,'active') on conflict(organization_id,user_id) do update set status='active'$$,'upsert активирует свободное место');
select lives_ok($$insert into public.organization_memberships(organization_id,user_id,status) values(current_setting('test.team_org')::uuid,md5('team-quota-1')::uuid,'active') on conflict(organization_id,user_id) do update set status='active'$$,'повтор upsert не дублирует место');
insert into public.organizations(id,name) values(md5('team-quota-target')::uuid,'Team quota target');
update public.organization_subscriptions set status='free',plan_version_id=(select id from public.billing_plan_versions where plan_key='free' and version=1),team_member_quota_enabled=true where organization_id=md5('team-quota-target')::uuid;
select lives_ok($$update public.organization_memberships set organization_id=md5('team-quota-target')::uuid where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-1')::uuid$$,'перенос занимает свободное место назначения');
update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-2')::uuid;
select throws_ok($$update public.organization_memberships set organization_id=md5('team-quota-target')::uuid where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-2')::uuid$$,'P0001','team member quota exceeded','перенос в заполненную организацию запрещён');
select is((select organization_id from public.organization_memberships where user_id=md5('team-quota-2')::uuid and organization_id=current_setting('test.team_org')::uuid),current_setting('test.team_org')::uuid,'отказ сохраняет исходное членство');
select is(public.get_organization_billing_overview(current_setting('test.team_org')::uuid)->'enforcement'->>'team_members','true','кабинет отражает включённую квоту команды');
update public.organization_subscriptions set period_end=now()-interval '1 hour' where organization_id=current_setting('test.team_org')::uuid;
select throws_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-3')::uuid$$,'P0001','team quota unavailable','истечение блокирует новую активацию');
select lives_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-2')::uuid$$,'истечение не блокирует повтор существующего членства');
update public.organization_subscriptions set status='unconfigured',plan_version_id=null,period_start=null,period_end=null where organization_id=current_setting('test.team_org')::uuid;
select throws_ok($$update public.organization_memberships set status='active' where organization_id=current_setting('test.team_org')::uuid and user_id=md5('team-quota-3')::uuid$$,'P0001','team quota unavailable','ненастроенный тариф с opt-in закрывает увеличение команды');
update public.organization_subscriptions set status='transition' where organization_id=current_setting('test.team_org')::uuid;
select is(public.get_organization_billing_overview(current_setting('test.team_org')::uuid)->'enforcement'->>'team_members','false','transition отражается без ограничения команды');
select * from finish();
rollback;
