import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, expect, test, vi } from 'vitest'
const api = vi.hoisted(() => ({ readRecurringConsent: vi.fn(), requestRecurringConsent: vi.fn(), revokeRecurringConsent: vi.fn() }))
vi.mock('../services/recurringConsentApi', () => api)
import RecurringConsent from './RecurringConsent'
beforeEach(() => { vi.resetAllMocks(); api.readRecurringConsent.mockResolvedValue({ state: 'none', canRequest: true }) })
test('требует явное согласие и защищает от двойного клика', async () => {
  api.requestRecurringConsent.mockReturnValue(new Promise(() => {}))
  render(<RecurringConsent organizationId="org" orderId="order" />)
  const button = await screen.findByRole('button', { name: 'Сохранить согласие' })
  expect(button).toBeDisabled()
  expect(api.requestRecurringConsent).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('checkbox')); fireEvent.click(button); fireEvent.click(button)
  expect(api.requestRecurringConsent).toHaveBeenCalledTimes(1)
})
test('показывает сохранённое состояние и отзыв без обещания списаний', async () => {
  api.readRecurringConsent.mockResolvedValue({ state: 'saved', consentId: 'consent', canRequest: false })
  api.revokeRecurringConsent.mockResolvedValue({ state: 'revoked', consentId: 'consent', canRequest: false })
  render(<RecurringConsent organizationId="org" orderId="order" />)
  fireEvent.click(await screen.findByRole('button', { name: 'Отозвать согласие' }))
  await screen.findByText('Согласие отозвано. Этот заказ не включает автопродление.')
  expect(api.revokeRecurringConsent).toHaveBeenCalledWith('org', 'order', 'consent')
  expect(screen.queryByRole('checkbox')).toBeNull()
})
test('сбой после записи восстанавливается чтением, без вывода исходной ошибки', async () => {
  api.requestRecurringConsent.mockRejectedValue(new Error('private-provider-detail'))
  render(<RecurringConsent organizationId="org" orderId="order" />)
  fireEvent.click(await screen.findByRole('checkbox'))
  fireEvent.click(screen.getByRole('button', { name: 'Сохранить согласие' }))
  await screen.findByRole('alert')
  expect(screen.queryByText('private-provider-detail')).toBeNull()
  api.readRecurringConsent.mockResolvedValue({ state: 'pending', consentId: 'consent', canRequest: false })
  fireEvent.click(screen.getByRole('button', { name: 'Обновить согласие' }))
  await screen.findByText('Согласие сохранено. Способ оплаты ещё не подтверждён.')
  await waitFor(() => expect(screen.queryByRole('alert')).toBeNull())
})

test('смена заказа сбрасывает галочку и не принимает поздний ответ предыдущего заказа', async () => {
  let finishOldRequest
  api.requestRecurringConsent.mockReturnValue(new Promise(resolve => { finishOldRequest = resolve }))
  const { rerender } = render(<RecurringConsent organizationId="org" orderId="first" />)
  fireEvent.click(await screen.findByRole('checkbox'))
  fireEvent.click(screen.getByRole('button', { name: 'Сохранить согласие' }))
  rerender(<RecurringConsent organizationId="org" orderId="second" />)
  expect(await screen.findByRole('checkbox')).not.toBeChecked()
  expect(screen.getByRole('button', { name: 'Сохранить согласие' })).toBeDisabled()
  await act(async () => finishOldRequest({ state: 'saved', canRequest: false, consentId: 'old' }))
  expect(screen.getByRole('checkbox')).not.toBeChecked()
  expect(screen.queryByRole('button', { name: 'Отозвать согласие' })).toBeNull()
  fireEvent.click(screen.getByRole('checkbox'))
  api.requestRecurringConsent.mockResolvedValue({ state: 'pending', canRequest: false, consentId: 'new' })
  fireEvent.click(screen.getByRole('button', { name: 'Сохранить согласие' }))
  await screen.findByText('Согласие сохранено. Способ оплаты ещё не подтверждён.')
  expect(api.requestRecurringConsent).toHaveBeenLastCalledWith('org', 'second')
})